export const LOGIC_CLIPS = {
 logic_play_menu: 'Játsszunk a macival, menjünk Meseligetbe, vagy keressük a kirakós képét! Az a Furfangliget, ahol fejtörők várnak.',
 logic_menu: 'Itt Furfangliget! Rendezzük be az erdei boltot, találjuk ki a gép szabályát, vagy tervezzünk egy csomagszállító utat!',
 logic_shop_1: 'Készítsd össze a két kosarat! A képek mutatják a rendelést. A plusz gombbal tehetsz bele, a mínusszal visszavehetsz. Ha elkészültél, koppints a Kész gombra!',
 logic_shop_2: 'Változtasd meg a kosarak tartalmát a rendelés szerint! A plusz hozzáadást, a mínusz elvételt jelent. Mindkét kosarat készítsd el!',
 logic_shop_3: 'Két dolgot tudunk a rendelésről: hány termés kell összesen, és mennyivel több alma kell, mint gesztenye. Állítsd össze mindkét kosarat!',
 logic_change: 'Változott a rendelés! Alakítsd át a kosarakat az új kérés szerint!',
 logic_apple: 'Alma.', logic_nut: 'Gesztenye.', logic_total: 'Összesen ennyi termés kell.', logic_difference: 'Ennyivel több alma kell, mint gesztenye.',
 logic_plus: 'Meg', logic_minus: 'Mínusz', logic_equals: 'Egyenlő',
 logic_shop_hint1: 'Nézd meg külön a két kosarat! Mindegyikben pontosan annyi legyen, amennyit a rendelés kér.',
 logic_shop_hint2: 'A pöttyök segítenek számolni. Tegyél hozzá, vagy vegyél el! A változtatást vissza is vonhatod.',
 logic_shop_hint3: 'Most megmutatom, mennyi kell a két kosárba. Számold meg, és igazítsd hozzá a kosaraidat!',
 logic_shop_more: 'Az egyik kosárba még kell termés. Nézd meg a kiemelt kosarat!',
 logic_shop_less: 'Az egyik kosárban több van a kelleténél. Vegyél ki belőle a mínusz gombbal!',
 logic_shop_done: 'Mindkét rendelés elkészült! A barátaink elvitték a kosarakat. Köszönik a segítségedet!',
 logic_machine_1: 'Figyeld a példákat! Mi történik a gépben? Válassz egy műveletet, és próbáld ki! Utána állítsd be, mi jön ki a két új számból!',
 logic_machine_2: 'Figyeld a három példát! Ugyanaz a szabály működik minden sorban. Építsd meg a gépet! A próbagombbal kísérletezhetsz. A két új szám eredményét te állítsd be!',
 logic_machine_3: 'Ebben a gépben két művelet követi egymást. A sorrend is számít! Koppints egy helyre, majd válassz bele műveletet! Próbáld ki, és oldd meg a két új esetet!',
 logic_input: 'Bemenet.', logic_output: 'Kimenet.', logic_predict: 'Mennyi jön ki a gépből?',
 logic_machine_hint1: 'Hasonlítsd össze, mi megy be, és mi jön ki! Mindhárom példában ugyanaz a szabály működik.',
 logic_machine_hint2: 'Az első műveletet megmutatom. Próbáld ki a többi példán is!',
 logic_machine_hint3: 'Megmutatom a gép műveleteit. A két új eredményt továbbra is te állítsd be!',
 logic_machine_retry: 'Ez a gép még másképp dolgozik, mint a példák. Változtass a műveleteken, és próbáld újra!',
 logic_machine_fit: 'A géped minden példához illik! Most állítsd be a két új eredményt!',
 logic_machine_guess: 'A gép jó! Nézd meg újra a két új szám eredményét!',
 logic_machine_empty: 'Előbb tegyél műveletet a gép minden helyére!',
 logic_machine_done: 'Megfejtetted a szabályt, és a két új feladatot is megoldottad! Működik a gép!',
 logic_route_1: 'Tervezz utat a rókának! Vedd fel a csomagot, majd menj a házhoz! Koppints egymás melletti mezőkre, vagy húzd végig az ujjad! A próbagomb indítja a rókát.',
 logic_route_2: 'Vidd el a csomagot a házhoz! A köveket kerüld meg! Tervezd meg az egész utat, aztán próbáld ki! Visszavonással javíthatsz.',
 logic_route_3: 'Gyűjtsd össze mindkét csomagot, és vidd a házhoz! Gondold végig, merre kerülsz! Figyelj, hogy beleférj a megadott lépésszámba! Több jó út is lehet.',
 logic_route_hint1: 'Előbb a csomagokhoz tervezz utat, aztán a házhoz! Csak egymás melletti mezőkre léphetsz.',
 logic_route_hint2: 'A kiemelt mezőre lépve még célba érhetsz. Koppints rá, ha arra szeretnél menni!',
 logic_route_hint3: 'Megmutatok egy teljes lehetséges utat. Kövesd a számozott mezőket, vagy találj másikat!',
 logic_route_restart_hint: 'Ez az út már túl hosszú lenne. Vonj vissza néhány lépést! A pöttyök egy rövidebb utat mutatnak.',
 logic_route_adjacent: 'A róka csak szomszédos mezőre léphet. Átlósan nem tud menni.',
 logic_route_full: 'Megtelt az útiterv. Vonj vissza egy lépést, ha másfelé mennél!',
 logic_route_missing: 'Még maradt csomag az ösvényen. Módosítsd az útitervet, és próbáld újra!',
 logic_route_home: 'A csomag megvan, de még el kell jutni a házhoz. Folytasd az útitervet!',
 logic_route_done: 'Megérkezett minden csomag! A barátaink már vártak. Szép útiterv volt!',
 logic_saved: 'Itt folytathatod a félbehagyott feladatot.',
 logic_op_add1: 'Adj hozzá egyet!', logic_op_sub1: 'Vegyél el egyet!', logic_op_add2: 'Adj hozzá kettőt!', logic_op_sub2: 'Vegyél el kettőt!', logic_op_double: 'Duplázd meg!', logic_op_add3: 'Adj hozzá hármat!', logic_op_sub3: 'Vegyél el hármat!',
};
const numbers = ['nulla','egy','kettő','három','négy','öt','hat','hét','nyolc','kilenc','tíz','tizenegy','tizenkettő','tizenhárom','tizennégy','tizenöt','tizenhat','tizenhét','tizennyolc','tizenkilenc','húsz'];
numbers.forEach((text,n)=>LOGIC_CLIPS[`logic_n_${n}`]=text);
