import { LOGIC_GAMES, LOGIC_NAMES, LEVEL_NAMES, OPS, generateTask, newSession, normalizeLogic, completeLogic, applyRule, neighbours, routeSolution, remember, undoMove } from './logic-data.js';

export function setupLogic({getProgress,updateProgress,getOptions,speak,stopPlayback}) {
  const root=document.querySelector('#furfangliget');
  let active=false,kind=null,session=null,task=null,slot=0,trial=false,busy=false,animation=0,status='',ghost=[],fox=null,walked=0,dragging=false,dragged=false,dragStart=null;
  const foxArt='<img class="logic-fox" src="./assets/furfang-fox.png" alt="" draggable="false">';
  const $=selector=>root.querySelector(selector);
  const say=(...ids)=>{if(active&&!document.hidden)speak(ids.flat());};
  const bind=(selector,fn)=>$(selector)?.addEventListener('click',fn);
  const allowed=()=>active&&!document.hidden&&!busy&&session&&!session.done;
  function save(reward=false){const p=normalizeLogic(getProgress());p.sessions[kind]=structuredClone(session);updateProgress(p,reward);}
  function stop(){active=false;animation++;busy=false;dragging=false;stopPlayback();}
  function menu(){animation++;busy=false;stopPlayback();kind=null;root.dataset.game='menu'; const p=normalizeLogic(getProgress());
    root.innerHTML=`<div class="logic-intro"><span class="logic-eyebrow">GONDOLKODJ · PRÓBÁLD KI · ALAKÍTSD ÁT</span><h2 tabindex="-1">Furfangliget</h2><p>Ma melyik fejtörőt választod?</p></div><div class="logic-places">${LOGIC_GAMES.map((k,i)=>{const s=p.sessions[k],level=getOptions()[`${k}Level`]||1;return `<button class="logic-place" data-game="${k}"><span class="logic-place-icon" aria-hidden="true">${i===2?foxArt:['🧺','⚙️'][i]}</span><strong>${LOGIC_NAMES[k]}</strong><span>${['Két rendelés, két kosár','Találd ki, építsd meg!','Előbb tervezz, aztán indulj!'][i]}</span><small>${LEVEL_NAMES[level-1]}${s&&!s.done&&s.level===level&&(k!=='shop'||s.limit===getOptions().mathLimit)?' · Folytatható':''}</small></button>`;}).join('')}</div><p class="logic-footer">A nehézséget a szülői beállításokban választhatjátok ki.</p>`;
    root.querySelectorAll('[data-game]').forEach(b=>b.addEventListener('click',()=>startGame(b.dataset.game)));
    $('h2').focus({preventScroll:true});say('logic_menu');
  }
  function startGame(game,fresh=false){kind=game; const options=getOptions(),level=options[`${kind}Level`]||1,limit=options.mathLimit||5,p=normalizeLogic(getProgress()),previous=p.sessions[kind];
    session=!fresh&&previous&&previous.level===level&&(kind!=='shop'||previous.limit===limit)?previous:newSession(kind,level,limit);
    task=generateTask(kind,session.level,session.limit,session.seed);slot=0;trial=false;ghost=[];fox=session.done&&kind==='route'?task.end:null;walked=0;status='';busy=false;save();render();repeat();
  }
  function repeat(){
    if(!kind){say('logic_menu');return;}
    if(session.done){say(`logic_${kind}_done`);return;}
    if(kind==='shop'){
      const target=task.orders[session.stage],base=session.stage?task.orders[0]:task.initial;
      const ids=[session.stage?'logic_change':`logic_shop_${session.level}`];
      if(session.level===3)ids.push('logic_total',`logic_n_${target[0]+target[1]}`,'logic_difference',`logic_n_${target[0]-target[1]}`);
      else for(let i=0;i<2;i++){ids.push(i?'logic_nut':'logic_apple');if(session.level===2)ids.push(`logic_n_${base[i]}`,target[i]>=base[i]?'logic_plus':'logic_minus',`logic_n_${Math.abs(target[i]-base[i])}`);else ids.push(`logic_n_${target[i]}`);}
      say(ids);
    } else say(`logic_${kind}_${session.level}`);
  }
  const dots=(n,emoji='●')=>`<span class="logic-dots" aria-hidden="true">${Array.from({length:n},()=>`<i>${emoji}</i>`).join('')||'<i>∅</i>'}</span>`;
  const quantity=(n,level=1)=>`<span class="logic-quantity"><b>${n}</b>${level===1?dots(n):''}</span>`;
  function render(focus){
    const hadFocus=focus||document.activeElement?.id; root.dataset.game=kind;root.dataset.done=session.done;root.dataset.level=session.level;
    root.innerHTML=`<div class="logic-toolbar"><button id="logic-back">↶ Liget</button><span>${LEVEL_NAMES[session.level-1]}${kind==='shop'?` · ${session.stage+1}/2`:''}</span><button id="logic-repeat" aria-label="Feladat meghallgatása">🔊 Újra</button></div><div class="logic-heading"><h2 tabindex="-1">${LOGIC_NAMES[kind]}</h2><p>${session.done?'Elkészült! Jöhet új fejtörő?':kind==='shop'?(session.stage?'Változott a rendelés. Alakítsd át!':'Készítsd össze mindkét kosarat!'):kind==='machine'?'Figyeld meg, építsd meg, majd számolj!':'Csomagok felvétele, aztán irány a ház!'}</p></div><div id="logic-work"></div><p id="logic-status" class="logic-status" role="status" aria-live="polite">${status}</p><div class="logic-actions"><button id="logic-undo" ${session.done||busy||!session.history.length?'disabled':''}>↶ Visszavonás</button><button id="logic-hint" ${session.done||busy?'disabled':''}>💡 Segíts!</button>${session.done?'<button id="logic-next" class="logic-primary">Új feladat</button>':`<button id="logic-check" class="logic-primary" ${busy?'disabled':''}>${kind==='route'?'▶ Kipróbálom':'Kész! ✓'}</button>`}</div>`;
    bind('#logic-back',menu);bind('#logic-repeat',repeat);bind('#logic-undo',()=>{if(!allowed())return;undoMove(session);trial=false;ghost=[];fox=null;status='';save();render('logic-undo');});bind('#logic-hint',hint);bind('#logic-check',check);bind('#logic-next',()=>startGame(kind,true));
    if(kind==='shop')renderShop();else if(kind==='machine')renderMachine();else renderRoute();
    if(hadFocus)document.getElementById(hadFocus)?.focus({preventScroll:true});
  }
  function stepper(index,label){return `<div class="logic-stepper"><button id="logic-minus-${index}" data-amount="${index}" data-delta="-1" aria-label="${label}: egy visszavétele" ${session.values[index]===0||session.done?'disabled':''}>−</button><output aria-label="${label} mennyisége">${session.values[index]}</output><button id="logic-plus-${index}" data-amount="${index}" data-delta="1" aria-label="${label}: egy hozzáadása" ${session.values[index]>=task.limit||session.done?'disabled':''}>+</button></div>`;}
  function bindAmounts(){root.querySelectorAll('[data-amount]').forEach(b=>b.addEventListener('click',()=>{if(!allowed())return;const i=+b.dataset.amount,n=session.values[i]+(+b.dataset.delta);if(n<0||n>task.limit)return;remember(session);session.values[i]=n;status='';save();render(b.id);}));}
  function renderShop(){const targets=task.orders[session.stage],base=session.stage?task.orders[0]:task.initial;
    $('#logic-work').innerHTML=`${session.done?'<div class="logic-delivery" aria-label="A nyuszi és a mókus átvette a két kosarat">🐰 🧺 ✓ 🐿️ 🧺</div>':''}<div class="logic-order" aria-label="Rendelés">${session.level===3?`<div><strong>🍎 + 🌰 = ${targets[0]+targets[1]}</strong><span>Összesen</span></div><div><strong>🍎 = 🌰 + ${targets[0]-targets[1]}</strong><span>Ennyivel több alma</span></div>`:targets.map((n,i)=>`<div><span>${i?'🌰 Gesztenye':'🍎 Alma'}</span><strong>${session.level===2?`${base[i]} ${n>=base[i]?'+':'−'} ${Math.abs(n-base[i])} = ?`:n}</strong>${session.level===1?dots(n,i?'🌰':'🍎'):''}</div>`).join('')}</div><div class="logic-baskets">${targets.map((n,i)=>`<section class="logic-basket ${status&&session.values[i]!==n?'logic-attention':''}"><h3>${i?'🌰 Gesztenyés kosár':'🍎 Almás kosár'}</h3><div class="logic-fruit" aria-label="${session.values[i]} ${i?'gesztenye':'alma'} a kosárban">${dots(session.values[i],i?'🌰':'🍎')}</div>${stepper(i,i?'Gesztenye':'Alma')}${session.help>=3?`<p class="logic-hint-text">Ennyi kell: ${n} ${i?'🌰':'🍎'}</p>`:''}</section>`).join('')}</div>${session.help===2?`<p class="logic-hint-text">${session.level===3?'Készíts egyenlő párokat, majd tedd hozzá a különbséget!':'Számolj a kosárban lévő termésekkel!'}</p>`:''}`;bindAmounts();}
  function renderMachine(){const ready=session.program.every(Boolean),fits=ready&&task.examples.every(([a,b])=>applyRule(a,session.program)===b);
    $('#logic-work').innerHTML=`<div class="logic-machine-layout"><section class="logic-examples"><h3>Így dolgozik a titkos gép</h3>${task.examples.map(([a,b],i)=>`<button class="logic-example" data-example="${i}" aria-label="Példa meghallgatása: ${a} bemenet, ${b} kimenet">${quantity(a,session.level)}<span aria-hidden="true">⇢ ⚙️ ⇢</span>${quantity(b,session.level)}${trial?`<small class="${applyRule(a,session.program)===b?'logic-match':'logic-mismatch'}">A te géped: ${Number.isFinite(applyRule(a,session.program))?applyRule(a,session.program):'?'} ${applyRule(a,session.program)===b?'✓':'≠'}</small>`:''}</button>`).join('')}</section><section class="logic-build"><h3>Az én gépem</h3><div class="logic-slots">${session.program.map((op,i)=>`<button id="logic-slot-${i}" data-slot="${i}" class="${slot===i?'selected':''}" aria-label="${i+1}. művelet: ${OPS[op]?.label||'üres'}" aria-pressed="${slot===i}" ${session.done?'disabled':''}><small>${i+1}.</small> ${OPS[op]?.label||'?'}</button>`).join('<span aria-hidden="true">⇢</span>')}</div><div class="logic-ops">${task.choices.map(op=>`<button id="logic-op-${op}" data-op="${op}" ${session.done?'disabled':''}>${OPS[op].label}</button>`).join('')}</div><button id="logic-trial" class="logic-test" ${session.done?'disabled':''}>⚙️ Géppróba</button>${session.help>=2?`<p class="logic-hint-text">${session.help===2?'Az első művelet: '+OPS[task.program[0]].label:'Egy jó szabály: '+task.program.map(op=>OPS[op].label).join(' ⇢ ')}</p>`:''}</section></div><section class="logic-predictions"><h3>${session.done?'⚙️ ✓ Működik a géped!':'Most te számolj!'}</h3><div class="logic-prediction-pair">${task.questions.map((n,i)=>`<div class="logic-prediction"><button data-question="${i}" aria-label="${n} megy a gépbe. Mennyi jön ki?">${quantity(n,session.level)} <span aria-hidden="true">⇢ ⚙️ ⇢</span> ? 🔊</button>${stepper(i,`${i+1}. eredmény`)}${session.level===1?dots(session.values[i]):''}</div>`).join('')}</div></section>`;
    root.querySelectorAll('[data-slot]').forEach(b=>b.addEventListener('click',()=>{if(!allowed())return;slot=+b.dataset.slot;render(b.id);}));
    root.querySelectorAll('[data-op]').forEach(b=>b.addEventListener('click',()=>{if(!allowed())return;remember(session);session.program[slot]=b.dataset.op;slot=(slot+1)%task.slots;trial=false;status='';save();render(b.id);say(`logic_op_${b.dataset.op}`);}));
    root.querySelectorAll('[data-example]').forEach(b=>b.addEventListener('click',()=>{const [a,c]=task.examples[+b.dataset.example];say('logic_input',`logic_n_${a}`,'logic_output',`logic_n_${c}`);}));
    root.querySelectorAll('[data-question]').forEach(b=>b.addEventListener('click',()=>say('logic_input',`logic_n_${task.questions[+b.dataset.question]}`,'logic_predict')));
    bind('#logic-trial',()=>{if(!allowed())return;if(!ready){status='Tegyél műveletet minden üres helyre!';say('logic_machine_empty');}else{trial=true;status=fits?'Minden példa illik! Mi lesz a két új eredmény?':'Hasonlítsd össze a példák kimenetét a te gépeddel!';say(fits?'logic_machine_fit':'logic_machine_retry');}render('logic-trial');});bindAmounts();
  }
  function renderRoute(){const end=session.path.at(-1),visited=session.path;
    $('#logic-work').innerHTML=`<div class="logic-route-layout"><div class="logic-board" role="group" aria-label="Csomagösvény, ${task.size} sor és ${task.size} oszlop" style="--size:${task.size}">${Array.from({length:task.size**2},(_,c)=>{const pathIndex=visited.indexOf(c),hintIndex=ghost.indexOf(c),parcel=task.parcels.indexOf(c),isFox=c===(fox??task.start);return `<button id="logic-cell-${c}" data-cell="${c}" class="logic-cell ${task.blocked.includes(c)?'blocked':''} ${pathIndex>=0?'on-path':''} ${c===end?'path-end':''} ${hintIndex>=0?'hint-cell':''}" aria-label="${Math.floor(c/task.size)+1}. sor, ${c%task.size+1}. oszlop${c===task.start?', indulás':''}${c===task.end?', ház':''}${parcel>=0?', csomag':''}${task.blocked.includes(c)?', kő':''}${pathIndex>=0?`, az út ${pathIndex}. lépése`:''}" ${busy||session.done?'disabled':''}><span aria-hidden="true">${isFox?foxArt:task.blocked.includes(c)?'🪨':c===task.end?'🏡':parcel>=0?((session.done||(fox!==null&&session.path.slice(0,walked+1).includes(c)))?'✓':'📦'):pathIndex>=0?'●':''}</span>${pathIndex>0?`<small>${pathIndex}</small>`:hintIndex>0?`<small>${hintIndex}</small>`:''}</button>`;}).join('')}</div><div class="logic-route-plan">${ghost.length>2?`<div class="logic-hint-route" aria-label="Segítő útvonal">${ghost.slice(1).map((c,i)=>`<span>${i+1}. ${{[-task.size]:'↑',[task.size]:'↓',[-1]:'←',[1]:'→'}[c-ghost[i]]}</span>`).join('')}</div>`:''}<div class="logic-parcels" aria-label="${task.parcels.filter(c=>visited.includes(c)).length} csomag szerepel az útitervben">${task.parcels.map(c=>`<span>${visited.includes(c)?'📦 ✓':'📦 ?'}</span>`).join('')}</div><strong>${visited.length-1} / ${task.maxSteps} lépés</strong><p>${session.done?'Minden csomag megérkezett! 🎉':'Koppints szomszédos mezőkre! Az utolsó mezőre koppintva visszaléphetsz.'}</p><div class="logic-directions" aria-label="Útvonal építése nyilakkal">${[['up','↑','Fel'],['left','←','Balra'],['down','↓','Le'],['right','→','Jobbra']].map(([d,s,l])=>`<button data-direction="${d}" aria-label="${l}" ${busy||session.done?'disabled':''}>${s}</button>`).join('')}</div><button id="logic-clear" ${busy||session.done||visited.length===1?'disabled':''}>↺ Újratervezés</button></div></div>`;
    root.querySelectorAll('[data-cell]').forEach(b=>b.addEventListener('click',()=>{if(dragged){dragged=false;return;}move(+b.dataset.cell);}));
    root.querySelectorAll('[data-direction]').forEach(b=>b.addEventListener('click',()=>{const d=b.dataset.direction,next=end+({up:-task.size,down:task.size,left:-1,right:1}[d]);move(next);}));
    bind('#logic-clear',()=>{if(!allowed())return;remember(session);session.path=[task.start];ghost=[];fox=null;status='';save();render('logic-clear');});
  }
  function move(cell,drag=false){if(!allowed())return;const last=session.path.at(-1);if(cell===last){if(drag||session.path.length===1)return;remember(session);session.path.pop();}else if(neighbours(last,task.size).includes(cell)&&!task.blocked.includes(cell)){if(session.path.length>task.maxSteps){status='Megtelt az útiterv. Vonj vissza egy lépést!';if(!drag)say('logic_route_full');render();return;}remember(session);session.path.push(cell);}else{if(!drag){status='Csak szomszédos, szabad mezőre léphetsz.';say('logic_route_adjacent');render();}return;}ghost=[];fox=null;status='';save();render(`logic-cell-${cell}`);}
  // Delegated pointer listeners survive rendering. Taps and keyboard buttons offer the same actions.
  root.addEventListener('pointerdown',event=>{const cell=event.target.closest('[data-cell]');if(kind!=='route'||!allowed()||!cell)return;dragging=true;dragged=false;dragStart={cell:+cell.dataset.cell,x:event.clientX,y:event.clientY,id:event.pointerId};root.setPointerCapture(event.pointerId);});
  root.addEventListener('pointermove',event=>{if(!dragging||!allowed())return;const b=document.elementFromPoint(event.clientX,event.clientY)?.closest('[data-cell]');if(b&&Math.hypot(event.clientX-dragStart.x,event.clientY-dragStart.y)>8&&+b.dataset.cell!==session.path.at(-1)){dragged=true;move(+b.dataset.cell,true);}});
  root.addEventListener('pointerup',event=>{if(!dragging||dragStart?.id!==event.pointerId)return;dragging=false;const wasDragged=dragged;if(root.hasPointerCapture(event.pointerId))root.releasePointerCapture(event.pointerId);if(!wasDragged)move(dragStart.cell);dragged=true;});window.addEventListener('pointercancel',()=>{dragging=false;dragged=false;});
  function hint(){if(!allowed())return;session.help=Math.min(3,session.help+1);const h=session.help;
    if(kind==='route'&&h>=2){const solution=routeSolution(task,session.path);if(!solution||solution.length-1>task.maxSteps){ghost=routeSolution(task);status='Érdemes rövidebb utat tervezni. Vonj vissza, vagy kezdd újra!';say('logic_route_restart_hint');}else{ghost=h===2?[session.path.at(-1),solution[session.path.length]].filter(c=>c!==undefined):solution;status=h===2?'A kiemelt mező felé még célba érhetsz.':'Ez egy lehetséges út. Más jó út is lehet.';say(`logic_route_hint${h}`);}}
    else {status=kind==='shop'?(h===3?'A kosarak alatt megmutattuk a célmennyiségeket.':h===2?'Számold meg a terméseket, és változtass a kosarakon!':'Nézd meg külön az almás és a gesztenyés rendelést!'):kind==='machine'?(h===1?'Ugyanaz a szabály illik mindhárom példára.':h===2?'Segítség az első művelethez lent, a géped alatt.':'A műveleteket megmutattuk. A két eredményt te számold ki!'):'Előbb csomag, aztán ház. Tervezd meg az egész utat!';say(`logic_${kind}_hint${h}`);}
    save();render('logic-hint');
  }
  function resolve(){
    const p=normalizeLogic(getProgress());p.sessions[kind]=session;const result=completeLogic(p,kind);
    if(result.changed){session=result.progress.sessions[kind];updateProgress(result.progress,result.reward);trial=false;ghost=[];status=result.reward?'✓ Sikerült! Szép munka.':'✓ Az első kosarak készek. Most változott a rendelés!';render();if(result.reward)say(`logic_${kind}_done`);else repeat();return;}
    session.misses=Math.min(9999,session.misses+1);
    if(kind==='shop'){const i=session.values.findIndex((n,j)=>n!==task.orders[session.stage][j]),more=session.values[i]<task.orders[session.stage][i];status=`${i?'A gesztenyés':'Az almás'} kosárban ${more?'még kevés':'most sok'} a termés. Módosíthatsz rajta.`;say(more?'logic_shop_more':'logic_shop_less');}
    else if(kind==='machine'){const ready=session.program.every(Boolean),fits=ready&&task.examples.every(([a,b])=>applyRule(a,session.program)===b);trial=ready;status=!ready?'Előbb töltsd ki a gép üres helyeit!':fits?'A géped jó. Nézd meg újra a két új eredményt!':'Próbálj más műveletet! A példák segítenek.';say(!ready?'logic_machine_empty':fits?'logic_machine_guess':'logic_machine_retry');}
    else {const missing=task.parcels.some(c=>!session.path.includes(c));status=missing?'Még maradt csomag. Javíts az útiterven!':'Még el kell jutni a házhoz. Folytasd az útitervet!';say(missing?'logic_route_missing':'logic_route_home');}
    save();render('logic-check');
  }
  function check(){if(!allowed())return;if(kind!=='route'){resolve();return;}busy=true;const token=++animation;let index=0;status='A róka kipróbálja az útitervedet.';
    const tick=()=>{if(!active||token!==animation||document.hidden){busy=false;return;}walked=index;fox=session.path[index++];render();if(index<session.path.length)window.setTimeout(tick,matchMedia('(prefers-reduced-motion: reduce)').matches?0:260);else{busy=false;resolve();}};tick();
  }
  document.addEventListener('visibilitychange',()=>{if(document.hidden){animation++;busy=false;dragging=false;stopPlayback();}else if(active&&kind)render();});
  return {start(){active=true;menu();},stop,repeat};
}
