// Generated by npm run build-offline. Do not edit this file directly.
const CACHE_VERSION = "815e3402f006879c";
const ASSETS = [
  {
    "file": "app.js",
    "sha256": "476500234dfd255844716b18427a98f1a24d8bbaecc9bee267bfc646db95f8ea"
  },
  {
    "file": "app.webmanifest",
    "sha256": "7c72744d874f72772abd70675cf71419db4f9b73954b56a75d18c86130993170"
  },
  {
    "file": "assets/furfang-fox.png",
    "sha256": "ba7e0fea9fed0fefc1f5caa2088d9e031e09b03b1efb4431e0c6a4b9a1ba70e1"
  },
  {
    "file": "audio/alma.mp3",
    "sha256": "4c15875a03cb601932dd497aa80331c245b8c7b696326f65825f3f3648eb164e"
  },
  {
    "file": "audio/anya.mp3",
    "sha256": "8238d02e87ea9568800e90db7f57aa579dbd668d3b4fd9c090e5f423a39e3554"
  },
  {
    "file": "audio/apa.mp3",
    "sha256": "6cf6745ee3dce03782df169e6077174a2852a534d5ce21282ec9d8c5080a7ec7"
  },
  {
    "file": "audio/auto.mp3",
    "sha256": "25c2fc9369e57352f3cdddd423222be5f45818f8d513e33832302b681d2789e1"
  },
  {
    "file": "audio/baba.mp3",
    "sha256": "0957d2067d39117d2fefb350cdc594671f78876c77f052e09aefaff5f7b5b5d4"
  },
  {
    "file": "audio/busz.mp3",
    "sha256": "68d819a050e34831f191f0d787053a2ffb0ed22fdaf9861702551e96cb5ee13d"
  },
  {
    "file": "audio/cica.mp3",
    "sha256": "b0864eb57142ec605af6a15d0b39f14d7ba2a9e1bebaa9cf87cc1d363d7b12c4"
  },
  {
    "file": "audio/cipo.mp3",
    "sha256": "7de5a236096c847366741287fbdc848deb5d174d8a9dd0e45aa4d20ee1687ae0"
  },
  {
    "file": "audio/fa.mp3",
    "sha256": "7dd68fba16068e4dc4d2082bc88421b881038ecdc33bd9c9924700e14c3d68c5"
  },
  {
    "file": "audio/furdokad.mp3",
    "sha256": "078f4ea1a6a31af0a9efe2fc07fb558790728f94da2eab71c574920fb9cfc8f9"
  },
  {
    "file": "audio/hold.mp3",
    "sha256": "ed7012d36fb4adf502c8e91be2eadeb3ede1dd0c81d3287b699e270c520d46c0"
  },
  {
    "file": "audio/kanal.mp3",
    "sha256": "3179910e8fc69e25e9577ffdf01652b290f374898dae6f3e1deb836afe377c17"
  },
  {
    "file": "audio/kenyer.mp3",
    "sha256": "eeaf0fe379ef5e1de800d9c6a7e7e9f70062d8ffe2e2da74c68948179d4f82c5"
  },
  {
    "file": "audio/kifli.mp3",
    "sha256": "13c217b2842abb74ade4cb82cfddc46abbc4cb628bc5bbace2e20a8fee4c3f6b"
  },
  {
    "file": "audio/kutya.mp3",
    "sha256": "e546af267dd7642a3c52c3504b39edd6324e3c5122fe4638e672a1e29317be46"
  },
  {
    "file": "audio/labda.mp3",
    "sha256": "0613c9bb41f9a7ba038d6b5f8029104d71625e5c27f84b5e3a2f6a1b0cbd60aa"
  },
  {
    "file": "audio/maci.mp3",
    "sha256": "7a1621baa490765dd21aa293585648ac0c7fdd2832bd6fb7c5910eec2b4e14a1"
  },
  {
    "file": "audio/nap.mp3",
    "sha256": "55665e77ead0ab9de03ec8f57ec220662644a2f22aece666b2de24a4a16d4e3b"
  },
  {
    "file": "audio/sapka.mp3",
    "sha256": "5ba8d03dcd17da4e5479a64eb38b900f3e7bf48947a6683bea16ea7ad98a134e"
  },
  {
    "file": "audio/szia.mp3",
    "sha256": "7efcb01bcbad727d7dd11621da5ac0d50c35da2cba091fea3250703d7184cc41"
  },
  {
    "file": "audio/tej.mp3",
    "sha256": "e78719f0f1708104c73ba68d278f97f6e13fce6187d522b738048c079c00044f"
  },
  {
    "file": "audio/virag.mp3",
    "sha256": "02fb415a3381fe69e74457200367ae89fda1ffcd7cfb9dccff2349c86e4dd4f2"
  },
  {
    "file": "audio/viz.mp3",
    "sha256": "b320559775eac5cadd789008c9e1019939c42f7b596b70ac95ec700a28345c0b"
  },
  {
    "file": "audio/voice/dress_request_cipo.mp3",
    "sha256": "1e4a7495a90e4f2ef4220babbb99e5e464a9e09afb2e217619ca476d7263e6ba"
  },
  {
    "file": "audio/voice/dress_request_polo.mp3",
    "sha256": "e7f923c3d1f911b6391d51cff27c5f11b6ccd2a101c77a1a78ce9331059c44c8"
  },
  {
    "file": "audio/voice/dress_request_sal.mp3",
    "sha256": "663b6c2659172aa2c3f110d59597b605348d948ba9cb141a04f1621e502ee65b"
  },
  {
    "file": "audio/voice/dress_request_sapka.mp3",
    "sha256": "a61efe28f874c72567344b0f3b2d317966ba780c0418982a69479a4b2b09e105"
  },
  {
    "file": "audio/voice/dress_thanks_cipo.mp3",
    "sha256": "21927b4f3993ad5514c26df13ef27da136b7608b36a4e8f8261392d636a219d0"
  },
  {
    "file": "audio/voice/dress_thanks_polo.mp3",
    "sha256": "a922526f51b852fb37034b1f86b75e647876706cc877acaa260b25966dc53783"
  },
  {
    "file": "audio/voice/dress_thanks_sal.mp3",
    "sha256": "8882ce228e1c7e18e6c4bca9c66b61f470064470379547c947c15c65d1b47c01"
  },
  {
    "file": "audio/voice/dress_thanks_sapka.mp3",
    "sha256": "1a43ad00874e53c784ae067bc45182cd4b802bc5435922f2285686439db8d664"
  },
  {
    "file": "audio/voice/guide_again.mp3",
    "sha256": "422317d36c6fa6193ec45d5c02f296df88caa7e732db407e1bf8d74e4639096c"
  },
  {
    "file": "audio/voice/guide_animals.mp3",
    "sha256": "e9fe522ba61f9a0ee4a4d004846aba52c57319e6168229f66439bb946202afc7"
  },
  {
    "file": "audio/voice/guide_cards.mp3",
    "sha256": "e5e411b00c634f48f5e0aeeea7419a9f4fefa585cd11d5f1cd9400d59ac9eb43"
  },
  {
    "file": "audio/voice/guide_count.mp3",
    "sha256": "44f3671a503963d141f31497996396d06b539774945002132de8d4a9877d628d"
  },
  {
    "file": "audio/voice/guide_dress.mp3",
    "sha256": "d8648a0c5fee9fe9c0418ffdb84b0a73eabfa4c5cf3b87c821dee4a1e9342039"
  },
  {
    "file": "audio/voice/guide_dress_finished.mp3",
    "sha256": "b920f909a3d7f330a482a4364a1056ed2b8afea330d3fc95164f1ef555e0dcb4"
  },
  {
    "file": "audio/voice/guide_family.mp3",
    "sha256": "e627c47ba231bdc633326966c1228a1add90b636bc092c80aba5a0047ffe5ff4"
  },
  {
    "file": "audio/voice/guide_finished.mp3",
    "sha256": "72976c632c26a37f2d1279d076f5c05575ac668eedaf9df3f81f2521c5cc5fff"
  },
  {
    "file": "audio/voice/guide_flip.mp3",
    "sha256": "1ba73dc3b2310fc53a90ad1403e37f7444cd3427102c6b2554c6801d9d8e57f1"
  },
  {
    "file": "audio/voice/guide_food.mp3",
    "sha256": "9ff9009ae5103fc1a29b4136fc306afc84320ba87cf72a308d508947e1ba9a2c"
  },
  {
    "file": "audio/voice/guide_good.mp3",
    "sha256": "eff9afff147ecabdaa8e1a4ee0c071dd3eb8d8c07ee20bb91ee8a624dca2e6e7"
  },
  {
    "file": "audio/voice/guide_goodbye.mp3",
    "sha256": "dc57d3ee8bb8d1ea7fa2c28d9b706de5cb6fa4e7cd959aec1f43057041dacfc5"
  },
  {
    "file": "audio/voice/guide_home.mp3",
    "sha256": "631600fc271b7decad0fdb4ec6ab7a85d7358623bc62dcba6c9a5a6120e8a147"
  },
  {
    "file": "audio/voice/guide_imitate.mp3",
    "sha256": "4775bb784adcbb9a5f092bddfebf96c8a569ac714cfdc295db30792731918db2"
  },
  {
    "file": "audio/voice/guide_listening.mp3",
    "sha256": "3f039f29d3cd61419a3d3095edd7c9219333cb99fee0f138f19b828717db2b78"
  },
  {
    "file": "audio/voice/guide_listening_game.mp3",
    "sha256": "d285d412976fd7b3205c723244721520ff62dbdab643f66218a8a7b8b6b43526"
  },
  {
    "file": "audio/voice/guide_mic_help.mp3",
    "sha256": "53231d0aa4d814c5c7aa75feaae5ad39cd2bd7af9c0325e8ef5e78d023ac8896"
  },
  {
    "file": "audio/voice/guide_nature.mp3",
    "sha256": "155abbb636b0a99f328e5cc5db50c6977f7bd34eced8080ccff3306855c3cafb"
  },
  {
    "file": "audio/voice/guide_number_menu.mp3",
    "sha256": "751bd68297a3db745fbbfa2f62d98a313dcdfb4144f31ed16fcda0fd3e5590a7"
  },
  {
    "file": "audio/voice/guide_one_word.mp3",
    "sha256": "f76d14d8d5cf0a7f8b26c41affcda7265d6b0cf0599237b82d5439e16d01c372"
  },
  {
    "file": "audio/voice/guide_phrase.mp3",
    "sha256": "a1afc8998d007ae22aa3546bf572c6122f26fcabb9bddbeb032380845e54e702"
  },
  {
    "file": "audio/voice/guide_picture_menu.mp3",
    "sha256": "0cc62ff450d41630f0829403bbb29e769c8dc9335b59879d1e7af1af30361705"
  },
  {
    "file": "audio/voice/guide_play.mp3",
    "sha256": "18786b3176ce6a1ffdee71fd1482513ef13e46b6a11b8d979a5f4a8c24b21257"
  },
  {
    "file": "audio/voice/guide_play_menu.mp3",
    "sha256": "0a1240ba9d67906e2666530af7dabca88b08b7387121d9450d01e9f350e3e068"
  },
  {
    "file": "audio/voice/guide_play_menu_more.mp3",
    "sha256": "6f01a9d801385e00b282c5128e1ff2850823f858634e7dfb752faf2d52a7776a"
  },
  {
    "file": "audio/voice/guide_practice.mp3",
    "sha256": "c1089eaa9e8707b22ad47432729ed2c940507e43a9a739134177fc14b62d3c33"
  },
  {
    "file": "audio/voice/guide_quiz.mp3",
    "sha256": "48d9f857da5fc30e524936b11809466147d659dba4c506190056029745e4cf8d"
  },
  {
    "file": "audio/voice/guide_retry_count.mp3",
    "sha256": "c56313e76f26ead6936f46a5976ebe34729438d97e076f96cf524c55949df52f"
  },
  {
    "file": "audio/voice/guide_teddy.mp3",
    "sha256": "10ff4a65266f70fceb3f5bd348040cd269f4e97e3df3d33c1d86a716dbc8fbec"
  },
  {
    "file": "audio/voice/guide_teddy_finished.mp3",
    "sha256": "65e62727a735dd90e903de0c6cd564e9c7cf0ed63074a776f3f92c8d0d6a0e13"
  },
  {
    "file": "audio/voice/guide_teddy_thanks.mp3",
    "sha256": "356b6cf74f804c59a7a31a6ee1d1fa1272b5608507cc31dc5cc9e195b35049c5"
  },
  {
    "file": "audio/voice/guide_topics.mp3",
    "sha256": "dd6e2b0e8796b895b9528528441bf6628627deba352c449a74c96950c3b6828b"
  },
  {
    "file": "audio/voice/guide_two_words.mp3",
    "sha256": "063a97903cc819649424f0ce2c51d290f7f6774ab33a129287de751b73d8858b"
  },
  {
    "file": "audio/voice/guide_welcome.mp3",
    "sha256": "007eca3f995ac2ac4f3877b981dc8e21ee6ba2dc1d1a04816aef37847f49facc"
  },
  {
    "file": "audio/voice/logic_apple.mp3",
    "sha256": "a8f6c535a25889b8ed349798b4c7bc0a348f3b27fac1fea0ef17880b8ecf7392"
  },
  {
    "file": "audio/voice/logic_change.mp3",
    "sha256": "d8bb363fc64acf9a28320947e2a06ec385a7bf526f805d4994ccf33062dc36ec"
  },
  {
    "file": "audio/voice/logic_difference.mp3",
    "sha256": "a131f14e636aaab4d609cdb2c92d32bf1c382dcf7a53d1501c6d9246af7e4732"
  },
  {
    "file": "audio/voice/logic_equals.mp3",
    "sha256": "c19d9351e78e64c557cc5d13b2b9948aef36a171ed49b8a6211e4970d328b9df"
  },
  {
    "file": "audio/voice/logic_input.mp3",
    "sha256": "c21bc66b2740bd3529211d75a694efc506b138b75acdbd9d8b485b60c7b4b4d8"
  },
  {
    "file": "audio/voice/logic_machine_1.mp3",
    "sha256": "e0ea7f622719abe6eec0738968bcf2552ef622b3ff2679f5c4c9c9cf289d876a"
  },
  {
    "file": "audio/voice/logic_machine_2.mp3",
    "sha256": "6b62adbe95d009e1136836d15fc9d0f14b1861d1acdf63a30c82e6d80f693459"
  },
  {
    "file": "audio/voice/logic_machine_3.mp3",
    "sha256": "72ff78ece91537fa4660687b7971df4cb44fab8f431d1c575922fcbcf2115b8d"
  },
  {
    "file": "audio/voice/logic_machine_done.mp3",
    "sha256": "986e261c5e91cc81d524237642114554b35bdccec2b3db274589ad475f9720b0"
  },
  {
    "file": "audio/voice/logic_machine_empty.mp3",
    "sha256": "6987eef20bdbe46af17f57ee9286973a3dce26134887e18dbb26e24c57227539"
  },
  {
    "file": "audio/voice/logic_machine_fit.mp3",
    "sha256": "194a86fba5dd2bd3ef99493709a9f4de029df1af005f86b6088d061525bb84cb"
  },
  {
    "file": "audio/voice/logic_machine_guess.mp3",
    "sha256": "5f4467564364d457b07431d87ccd2a558cb2fbbd1cd450df08cf3f58336d7b7d"
  },
  {
    "file": "audio/voice/logic_machine_hint1.mp3",
    "sha256": "bda9ddfaeef210bd497cb5bbcd9f653d905de01bafa3195cd5fe9fa8346b9356"
  },
  {
    "file": "audio/voice/logic_machine_hint2.mp3",
    "sha256": "640e50c7cce0f3e152aaaabd8fa797e2aeb02a9b2c0c0b523664ef78117abe02"
  },
  {
    "file": "audio/voice/logic_machine_hint3.mp3",
    "sha256": "f4875f863f19ab88f0da7438ed145ff6fbff35c55c01b28f3579246329f8df90"
  },
  {
    "file": "audio/voice/logic_machine_retry.mp3",
    "sha256": "3fd710b8b8c8a594028dae4f099f66e9c012972461fb2aaa5e5a48d87279c08e"
  },
  {
    "file": "audio/voice/logic_menu.mp3",
    "sha256": "ca8c702a12fedc3e4d5f305a98785dc3f12ce60669dff0b16cb66aa09e104a4d"
  },
  {
    "file": "audio/voice/logic_minus.mp3",
    "sha256": "978c9918118b4c1dd007c070be1b8e8b16b8ac4b79eaf37a7f2bacd69ef0824b"
  },
  {
    "file": "audio/voice/logic_n_0.mp3",
    "sha256": "5bdbef1a9904357203a0b7b817504f0fee1bb7f2af27e63a65c1f37989b3c628"
  },
  {
    "file": "audio/voice/logic_n_1.mp3",
    "sha256": "fb42d4a4deb83a7c8c1479475e55a68342e0d328614e1ed9171a2d8239c6c72d"
  },
  {
    "file": "audio/voice/logic_n_10.mp3",
    "sha256": "c3440588e8b3bdef8a37076805658001048f582f558be24bea850624f6108aaf"
  },
  {
    "file": "audio/voice/logic_n_11.mp3",
    "sha256": "cb2b0b95bdae7226f5a611ce2af146b726bf8876f369542558a1ae3771270dc4"
  },
  {
    "file": "audio/voice/logic_n_12.mp3",
    "sha256": "dcc666f49a42a10c1f12c5fab4b39969a174f15a8f7152e59c742072e99abe29"
  },
  {
    "file": "audio/voice/logic_n_13.mp3",
    "sha256": "b8734480ba7870d67681036cf8451285fbfd2d66bd1ee08b7336eb2a93c8d11a"
  },
  {
    "file": "audio/voice/logic_n_14.mp3",
    "sha256": "fd1f07b05de8113ab3578ad8713462dbfbeb058ee57a22793f8d813d1da11f09"
  },
  {
    "file": "audio/voice/logic_n_15.mp3",
    "sha256": "54b85d66815d722214ff8fdf51201ab1cc31449cb70a8ddce1958e9f860f3fe5"
  },
  {
    "file": "audio/voice/logic_n_16.mp3",
    "sha256": "fd70563d841f464dccee612960ded72dbc1496673a807035ea7e0f04d7af4ba2"
  },
  {
    "file": "audio/voice/logic_n_17.mp3",
    "sha256": "4a2225546729f643268ade59b0f301432be2283d7bb21faa198dfc4e1b214cfb"
  },
  {
    "file": "audio/voice/logic_n_18.mp3",
    "sha256": "6338741cdceb546631e163022ef0d92191cd8420df7110cf8e5077fc514b5339"
  },
  {
    "file": "audio/voice/logic_n_19.mp3",
    "sha256": "44b18ae0145e26daf9d8ce45066afe1d8828c2e9190369d74d6dddbfc4058046"
  },
  {
    "file": "audio/voice/logic_n_2.mp3",
    "sha256": "f20d5867bb221ee701b0097a7d9547fb8e8b95f4031ec46f2539edb8b9c7b103"
  },
  {
    "file": "audio/voice/logic_n_20.mp3",
    "sha256": "6c10046a2a374fe5e024e20d94f896ec244a839b546a8620b7f162bad8c8459b"
  },
  {
    "file": "audio/voice/logic_n_3.mp3",
    "sha256": "73442ca97bcb52b553121bc3b6adfed7e02f35f3977461b1b46c555b531759a0"
  },
  {
    "file": "audio/voice/logic_n_4.mp3",
    "sha256": "9c9272367a69faa628e173ceee510a12fc16c3c93be350a54476f1077702dff2"
  },
  {
    "file": "audio/voice/logic_n_5.mp3",
    "sha256": "8fd04a0f49b8ef33b0c5892a04f16013850f0acf6a35043a41f647ab784366c3"
  },
  {
    "file": "audio/voice/logic_n_6.mp3",
    "sha256": "38b7cd88a8d7e1f55a6ab7051fb61985ade9f4e4b08f7de343bdffc7204b505f"
  },
  {
    "file": "audio/voice/logic_n_7.mp3",
    "sha256": "2f9b1eef62fabed8743dc4645e046b844628d32756b4aa30abb41cc13cc0b66e"
  },
  {
    "file": "audio/voice/logic_n_8.mp3",
    "sha256": "91867f744789601189cca9e2021a2b7e5a01d99f68119d18a97abe169ba09931"
  },
  {
    "file": "audio/voice/logic_n_9.mp3",
    "sha256": "529ecf9327da340c50d0d58fbce3b7dc56b5ca303a12b66498c9741cc7accc1b"
  },
  {
    "file": "audio/voice/logic_nut.mp3",
    "sha256": "efb86996df8191067a30799ad8dbfaab79c05a2e8bb3c67d3120efbe05f19ec8"
  },
  {
    "file": "audio/voice/logic_op_add1.mp3",
    "sha256": "1638e88a1d28f33f02fb56185ed4ac57768cadee1bab92a80989fe0ba1dad5ce"
  },
  {
    "file": "audio/voice/logic_op_add2.mp3",
    "sha256": "1a927039658074e6e724deaac575518e8906eef7a25b55a3f10cded00dbd4f89"
  },
  {
    "file": "audio/voice/logic_op_add3.mp3",
    "sha256": "23959e9c2e11cb613550e8ef71be224aae8d59e5ba23cd5fa3ab3eff98a73b15"
  },
  {
    "file": "audio/voice/logic_op_double.mp3",
    "sha256": "0c58db7ea0b7a525a6dde724d0e2ecace5480d9c5b4812c904a86745bb7b2eb9"
  },
  {
    "file": "audio/voice/logic_op_sub1.mp3",
    "sha256": "9544d5a278ae871f4e4e948dda9f46ffb90c83649d931663b45c76264ad7c453"
  },
  {
    "file": "audio/voice/logic_op_sub2.mp3",
    "sha256": "47e374ff47bdf3b3afd93166a41114e3f0d16a42c0eb2cb236d8b42da96112a9"
  },
  {
    "file": "audio/voice/logic_op_sub3.mp3",
    "sha256": "31f71eee297bee626e2fd35c5cd5da8286893bc702d454c4450a016075fa9cce"
  },
  {
    "file": "audio/voice/logic_output.mp3",
    "sha256": "37c73b1ce1c804b1b88a26721b0626f6a74f4c85c110773d6a5b5aeb48bb2eaa"
  },
  {
    "file": "audio/voice/logic_play_menu.mp3",
    "sha256": "ed5657e360eee0241ff176c8381eb315176a307b568bf484f9f560787187f07f"
  },
  {
    "file": "audio/voice/logic_plus.mp3",
    "sha256": "3d7fccd9a0808e712d33286e2d296ab47d0246c92d1700567ea339902024191b"
  },
  {
    "file": "audio/voice/logic_predict.mp3",
    "sha256": "333fd32209ed96d6bb9206fe714b4780e14667a41cb560f0cc6231c40fc6cbc6"
  },
  {
    "file": "audio/voice/logic_route_1.mp3",
    "sha256": "cf089e8767146a8c8a2d354eba7ff5c852ddf207b63582bf775d22be1afd70e1"
  },
  {
    "file": "audio/voice/logic_route_2.mp3",
    "sha256": "3702a5d26c6ba42ec36f4fe2af5765b50a7cb175120f3162da540f28ae2f27bc"
  },
  {
    "file": "audio/voice/logic_route_3.mp3",
    "sha256": "e630be9cafe608d41cf015dd21152aebd14ee451631711c12f83e80766d7fa82"
  },
  {
    "file": "audio/voice/logic_route_adjacent.mp3",
    "sha256": "e769045c1ab0ed5c92376b86ff986437c067db8ceb4d3b397e4c1c9538fc213a"
  },
  {
    "file": "audio/voice/logic_route_done.mp3",
    "sha256": "7e67f3b62162097e114d35fb5165981d56dce9fe1b45b3ef02b794bed24023b7"
  },
  {
    "file": "audio/voice/logic_route_full.mp3",
    "sha256": "2c9fcf2b689bb3eb23b3e5b43499ada07afb379c75fc4860359af274b1bb4101"
  },
  {
    "file": "audio/voice/logic_route_hint1.mp3",
    "sha256": "e66f8a520aa00571d01eefe13f0f28b3ce1e0a9b4ab3306db2febffa3024185b"
  },
  {
    "file": "audio/voice/logic_route_hint2.mp3",
    "sha256": "cdfcb323fc8877c039906b3695c6a900dce135ca38fb273fe994b9a4c05dd625"
  },
  {
    "file": "audio/voice/logic_route_hint3.mp3",
    "sha256": "60938ab3780c899b905414e1a4333b97f32e4bfcf47586cadcabc02300867879"
  },
  {
    "file": "audio/voice/logic_route_home.mp3",
    "sha256": "629a637b360dd34f09e6e9dba761c1dcb26c475aeac658cddfcc5626ce9d09a1"
  },
  {
    "file": "audio/voice/logic_route_missing.mp3",
    "sha256": "2bdcbc353c56b11b65670fbc5f59f6c94c62dd59fc488a56c202034cfd17a5ed"
  },
  {
    "file": "audio/voice/logic_route_restart_hint.mp3",
    "sha256": "95834f06d1b00233746ae26fc43d3bba00e5b5a1c7ea28f1c7d79b3282eea3a9"
  },
  {
    "file": "audio/voice/logic_saved.mp3",
    "sha256": "9e8231756929872fd2460dea796cfab7a4b638dd96e9e7cd09a0c3b426918d20"
  },
  {
    "file": "audio/voice/logic_shop_1.mp3",
    "sha256": "02618fd1384ee8a46c6ac11ec85a129c336b370c69173d21acc64450d8fa484a"
  },
  {
    "file": "audio/voice/logic_shop_2.mp3",
    "sha256": "b668753248341f40d1f2d8931d24c2ca5b555ca9db7fc540200113b779f568da"
  },
  {
    "file": "audio/voice/logic_shop_3.mp3",
    "sha256": "27402324db2901b0f627617243b88c46a799e89d0f5d5d22361b40f88249e01a"
  },
  {
    "file": "audio/voice/logic_shop_done.mp3",
    "sha256": "0064c18dadc6817a4be0a2f11d264a7787923e3f7b63352b9cb1f68f77cd1858"
  },
  {
    "file": "audio/voice/logic_shop_hint1.mp3",
    "sha256": "5a402ff3861d872adbf75c6acc67f8fcda03d0659e2de2eb9306d8701e70903a"
  },
  {
    "file": "audio/voice/logic_shop_hint2.mp3",
    "sha256": "098d71fcdcb63c8c4540bd89a4fbef605b6fad3cb4624caa2a600545de90ecce"
  },
  {
    "file": "audio/voice/logic_shop_hint3.mp3",
    "sha256": "dcafd3d60b1dc7fe877371257595b79129920e102d96dea52616573b8466908a"
  },
  {
    "file": "audio/voice/logic_shop_less.mp3",
    "sha256": "acab432bb664b2d57e8c5f8b584f3f77cfeb89e73010cc33258b69a6f0019cde"
  },
  {
    "file": "audio/voice/logic_shop_more.mp3",
    "sha256": "f711a3e57adb8e5e8a84c476720584aab95107c043120790df0d9710a9bc5f57"
  },
  {
    "file": "audio/voice/logic_total.mp3",
    "sha256": "b53a574e0e88b1303987141532f940186fd873d84e6eefa6b8ec2fe534b10a8e"
  },
  {
    "file": "audio/voice/memory_done.mp3",
    "sha256": "29a95f2ff893a963c39d74a93efc74eae0fd6228f435134f5816dfe7d4e1ec63"
  },
  {
    "file": "audio/voice/memory_hint.mp3",
    "sha256": "bad88cc440f996a9ea2fcab8bd9c005a1221e8e6dcd239143b254707f8c9ef35"
  },
  {
    "file": "audio/voice/memory_match.mp3",
    "sha256": "7b716b902a08b5b90268fbcd1d12c897b4d3d8a4d370bffa6da5d56fc506aaa1"
  },
  {
    "file": "audio/voice/memory_start.mp3",
    "sha256": "f3ce0f38d789c46ca102d0bdf5e9e9fe94bfb4d4770c7c33fcb68f253ceec5a5"
  },
  {
    "file": "audio/voice/mese_album.mp3",
    "sha256": "088f092cc2eac2baec1bf8cc5390c48b0be4584d502b194e58c9ac6d5e838833"
  },
  {
    "file": "audio/voice/mese_collect_1.mp3",
    "sha256": "914f74337f4a76276357a9b89cd2901886d1783a986fc3f14161ec87292ceff3"
  },
  {
    "file": "audio/voice/mese_collect_10.mp3",
    "sha256": "d5d0af7dabda7e1631a700a883933372f846740eefcb690d89d6906bb9c794e0"
  },
  {
    "file": "audio/voice/mese_collect_2.mp3",
    "sha256": "52c2c7b15795208242053a85d126ea1d7ee4362f0da611200b8de7738e1074e8"
  },
  {
    "file": "audio/voice/mese_collect_3.mp3",
    "sha256": "cc52f16dfc9f7d10b40a310579754e1b814148ce54fbbd0fa523367ece282a3a"
  },
  {
    "file": "audio/voice/mese_collect_4.mp3",
    "sha256": "6a4a8108c886475a000d72188c2bb268f426a6580cb7571085c97390cfb109ce"
  },
  {
    "file": "audio/voice/mese_collect_5.mp3",
    "sha256": "6f0ed2624fccdb5945fd6cf8b6ab469087f194641b412404924e38f88708639f"
  },
  {
    "file": "audio/voice/mese_collect_6.mp3",
    "sha256": "7aa333271ed304739e98d8ab27c1a160d1dcb41b9ef1ecfd2fd93da6264ae18c"
  },
  {
    "file": "audio/voice/mese_collect_7.mp3",
    "sha256": "fe69fcbfe17a7ec7f102fa704f729abfa92acc537971e9090a94bceb28e6dedc"
  },
  {
    "file": "audio/voice/mese_collect_8.mp3",
    "sha256": "01e2824c87eab41248ea32f58cfc67b86381aabd53e82a0a0c9431106fb5b2de"
  },
  {
    "file": "audio/voice/mese_collect_9.mp3",
    "sha256": "e52b13a7399cb23804bad5ff6e35c160005e88676d46304386adbe13d4bd88d7"
  },
  {
    "file": "audio/voice/mese_collected_1.mp3",
    "sha256": "124ffda8a8214e827ea1af81e952cb85c4f1a38bac2f980c9d1dd90360d5b715"
  },
  {
    "file": "audio/voice/mese_collected_10.mp3",
    "sha256": "15f4a616eb269b1f763583e11e122d12e3e15953296709c9fbe4de6be3dca4b4"
  },
  {
    "file": "audio/voice/mese_collected_2.mp3",
    "sha256": "8b2836a9557c29f9db32f5af2f0cb020e6b0f879dddbf5a6a9cd423d3850733c"
  },
  {
    "file": "audio/voice/mese_collected_3.mp3",
    "sha256": "046600ec676c5d394a761851d6b24a9ef7bdcc44f01235ddd01253729da0dc6f"
  },
  {
    "file": "audio/voice/mese_collected_4.mp3",
    "sha256": "7622295b8e1f1553e56c1e58a70394310b3ef5b8dd14a6793758546dad44953c"
  },
  {
    "file": "audio/voice/mese_collected_5.mp3",
    "sha256": "f886fda5208bcad1f4aec8cc0dd7e862bd82a6f69ac741e653d8471b45287444"
  },
  {
    "file": "audio/voice/mese_collected_6.mp3",
    "sha256": "d8faf69f3e8fc858b6417156f1dba9737e5f047de33a46d6b4e2984e03278099"
  },
  {
    "file": "audio/voice/mese_collected_7.mp3",
    "sha256": "e937d593904dea37afc3d82ecbf59f2587ea25e2189fec5cec2a6de2e00d482e"
  },
  {
    "file": "audio/voice/mese_collected_8.mp3",
    "sha256": "5f28938ae85fffb63f04f1d3cf39e91c150516e7d2119fa7cb124c37bc80373c"
  },
  {
    "file": "audio/voice/mese_collected_9.mp3",
    "sha256": "c76f0e5128a465413b221c26cda8e4619d0ec315eab993d8181f45ebcf67e3be"
  },
  {
    "file": "audio/voice/mese_count_help.mp3",
    "sha256": "f025312eb152aea30fca2854dc804906bb4980c42aac97c4fed4a831f56b1a10"
  },
  {
    "file": "audio/voice/mese_dressed.mp3",
    "sha256": "1d3aa1efffac7725d10f02a262af3087d239a59519bc9d8b7f45c031ca905587"
  },
  {
    "file": "audio/voice/mese_empty_album.mp3",
    "sha256": "3170aceee004fd97c38a66d4d64ceb9fee759477c858988d912542d244786e81"
  },
  {
    "file": "audio/voice/mese_finish.mp3",
    "sha256": "851372c31887ee1f2c5875c0cf919dc4f5bd52ed14c460582e0f4a8df37a2d60"
  },
  {
    "file": "audio/voice/mese_free_finish.mp3",
    "sha256": "ec7c90a4d2187bab943c310032e56793497612dbe36c2b32310d779747b96f24"
  },
  {
    "file": "audio/voice/mese_less.mp3",
    "sha256": "cdda6bcf3a86baa738b326929eaa2dbe70204c5e5ef65a7001ebe910cd5721fe"
  },
  {
    "file": "audio/voice/mese_map.mp3",
    "sha256": "2b07d394d85fe416f7746e52164a2b6afa84d688293883684386fbad5ace3c5e"
  },
  {
    "file": "audio/voice/mese_more.mp3",
    "sha256": "b8df58fc01325148281131e35994f27ce3dbb76eb90f3fbc09d36cd00f1618cb"
  },
  {
    "file": "audio/voice/mese_plate_help.mp3",
    "sha256": "bc7ec421eb19e3a0a21dd41b0e16e41d992d2ad9eec9fc741b1544d2d78fd518"
  },
  {
    "file": "audio/voice/mese_plate_more.mp3",
    "sha256": "c4b01ac6c59a22206bbe277dc7ca146260f566350914cc3f0be8a300edec3d80"
  },
  {
    "file": "audio/voice/mese_play_menu.mp3",
    "sha256": "e317c44c898fda1d9a89c1cd7796e0950ae4f591e93306af94e0ab2844d26497"
  },
  {
    "file": "audio/voice/mese_serve.mp3",
    "sha256": "1c48d830d7bb6213a220ceb176c1b7c2f4e7b69fc53f79fa3a5782019b642ad7"
  },
  {
    "file": "audio/voice/mese_served.mp3",
    "sha256": "6783e62f9fb053af220dae49e459ec4628ac64da0068f7c6f1666f20d746935c"
  },
  {
    "file": "audio/voice/mese_start.mp3",
    "sha256": "48245b198f216f643b226083b3fa75c6a69b2bc6bb1f7719b4bede16d0a1f3bc"
  },
  {
    "file": "audio/voice/number_1.mp3",
    "sha256": "4605df530e53aa0f468524053d63c3bdff834a29b94ff66f1526a85ea3b469b6"
  },
  {
    "file": "audio/voice/number_10.mp3",
    "sha256": "5031d1e726b0791f22c5d72713de4dbafdf6a446353effc8fcbfffea2426421f"
  },
  {
    "file": "audio/voice/number_2.mp3",
    "sha256": "d1fd7f53fd4857340da33ef5a1cce63e991ac86e1adaf58634a076d57356663f"
  },
  {
    "file": "audio/voice/number_3.mp3",
    "sha256": "f04e63379d7ec295a56245b7d02256378e7b7dd5afa6f2c8c331035914376814"
  },
  {
    "file": "audio/voice/number_4.mp3",
    "sha256": "fe2ed9c374709e744f26e602b747c53762204525ca64b01fd3bed789e1285a2a"
  },
  {
    "file": "audio/voice/number_5.mp3",
    "sha256": "0787e81647b5ad09532e00df91e2edf4896f11da6a8ff9f30a114ff8a972cc20"
  },
  {
    "file": "audio/voice/number_6.mp3",
    "sha256": "56bbaca37bc910207a38585a74e203475a2403b23fb9218cafca7be03384f192"
  },
  {
    "file": "audio/voice/number_7.mp3",
    "sha256": "7bd043a8c5df3e09e6390f1e8a72cd2059c5493a85696d9478681c90d1513316"
  },
  {
    "file": "audio/voice/number_8.mp3",
    "sha256": "666799cd6385b100d5fee179024c9180909164cc2cf8be2f510c9ba7c98a0887"
  },
  {
    "file": "audio/voice/number_9.mp3",
    "sha256": "131562d822d95ef00c352022feb39b4730942f95552701868d564d57c55e2d30"
  },
  {
    "file": "audio/voice/phrase_anya_gyere.mp3",
    "sha256": "c76ff06e7827110ee3d6a169abd732a2070289f30200a500e1b045ab5825e8cd"
  },
  {
    "file": "audio/voice/phrase_apa_auto.mp3",
    "sha256": "1c7adf0532a41d7ca1a3ace6ebcb8274652fc38bedf234f0690d4abcb8e2b993"
  },
  {
    "file": "audio/voice/phrase_kerek_vizet.mp3",
    "sha256": "46fd55ae7af8a7547bfb50bee1b3da97a3dea71c3a07846eae0a7674c3ab9824"
  },
  {
    "file": "audio/voice/phrase_meg_alma.mp3",
    "sha256": "cc9b829ba3c487f5db839232569e4cac2a6ab1502b551e4d7b59bef0600d721d"
  },
  {
    "file": "audio/voice/phrase_nagy_labda.mp3",
    "sha256": "1461471209cc5897a1a291d5141128fc8209bf0022bf3b0095dcccd97e4c8211"
  },
  {
    "file": "audio/voice/phrase_nem_kerem.mp3",
    "sha256": "b21b30544f966f71713f215e5fda9be008dd0f2125b60c3780c59d13c511bfe1"
  },
  {
    "file": "audio/voice/quantity_alma_1.mp3",
    "sha256": "c350c00728d92dd6bd4b5da1074580badee658ddf354d70d1aadddf02f7b5585"
  },
  {
    "file": "audio/voice/quantity_alma_10.mp3",
    "sha256": "88774097774ac44ed851ccf4c264adbe273ccc3bfef49a15aabc74090533b2d7"
  },
  {
    "file": "audio/voice/quantity_alma_2.mp3",
    "sha256": "edc36e5476598adc69c93336698a35e2d8aa43aa72981fc0e4ad7a952a955da4"
  },
  {
    "file": "audio/voice/quantity_alma_3.mp3",
    "sha256": "5bacf5bd0b08c7b1fc7f9596fc2654c016f0537a531789680f0dddee1c0fad74"
  },
  {
    "file": "audio/voice/quantity_alma_4.mp3",
    "sha256": "840cd4c58a2c84fdc4b6dc966cab7da4ec2342d42c900f263eaa56374125a2f2"
  },
  {
    "file": "audio/voice/quantity_alma_5.mp3",
    "sha256": "e04821d12953207946b86d3d31ad3950c1bdd8be09e92a55646c6d552e5d75b7"
  },
  {
    "file": "audio/voice/quantity_alma_6.mp3",
    "sha256": "9f08acaa18b0dc8ee42862342922b5f6f361743f898dd4a60d982edc8f53b497"
  },
  {
    "file": "audio/voice/quantity_alma_7.mp3",
    "sha256": "4d6e3e100fd74c0d5a29ac321be40792ca611646faf5207b16ecd249b66c20a8"
  },
  {
    "file": "audio/voice/quantity_alma_8.mp3",
    "sha256": "548d0dd453b559866e9e42fe1ec4d3922efce1afc95f6f40c83e386da6fd74c0"
  },
  {
    "file": "audio/voice/quantity_alma_9.mp3",
    "sha256": "7a575ae2e8e7b14580889fc5cf57c86b8d4b2cb4534f10544cf8a9ea8a042e2e"
  },
  {
    "file": "audio/voice/quantity_auto_1.mp3",
    "sha256": "d3237449a5f1662567889a46a40dfc98051d976067a7f92b376f7b3ecc7dba1c"
  },
  {
    "file": "audio/voice/quantity_auto_10.mp3",
    "sha256": "65e9099cc97fd0590f4436b9f1c9702437b6cc28b1ec45c9788f9feb5e4b7126"
  },
  {
    "file": "audio/voice/quantity_auto_2.mp3",
    "sha256": "78d0b3ca064e0f717cd067da29d580141aaf95fb5f37eb166dc3978a619008a7"
  },
  {
    "file": "audio/voice/quantity_auto_3.mp3",
    "sha256": "c917a129963f019310b4f2fe0e96d05b6f21d6493969aa5327fbccdfc926e20e"
  },
  {
    "file": "audio/voice/quantity_auto_4.mp3",
    "sha256": "b59513c69d502965c95d7032fa96b3211ab95f96096ab30691361bbeff96e2d2"
  },
  {
    "file": "audio/voice/quantity_auto_5.mp3",
    "sha256": "ae474f1b8b1b96274275976d4be0caa33d8780597d9a47dcdd4d74eaebe459f1"
  },
  {
    "file": "audio/voice/quantity_auto_6.mp3",
    "sha256": "491ae3228616ccfa52580ca31f24dc2d61cc55dd8c41aa4297ae09311879298f"
  },
  {
    "file": "audio/voice/quantity_auto_7.mp3",
    "sha256": "de4590d22816a011a8198ff7117dbecd1879553ccccc9e4316ba6edf1dc65b8d"
  },
  {
    "file": "audio/voice/quantity_auto_8.mp3",
    "sha256": "9cc9b84425b4483a76ebeb3c1745679d74e89838c748e6348e59795f1f4db311"
  },
  {
    "file": "audio/voice/quantity_auto_9.mp3",
    "sha256": "667e5e779c2b559f52766137b1ea0c14c132c319e3a23908d13ee884f9d1265a"
  },
  {
    "file": "audio/voice/quantity_labda_1.mp3",
    "sha256": "278e3963b8907cf8a596c87f438fa399b194da128abc8d20ad29e82b723cdf40"
  },
  {
    "file": "audio/voice/quantity_labda_10.mp3",
    "sha256": "70165dbe3e5abf74df0f1e10a87389cf6e455d357dc35f206723630ba4c6a1f6"
  },
  {
    "file": "audio/voice/quantity_labda_2.mp3",
    "sha256": "ebc3ca41ff2954418b8abf2573306e598164aa6669e03b7c1fcbb012586c880f"
  },
  {
    "file": "audio/voice/quantity_labda_3.mp3",
    "sha256": "06e04a941b1594ab88cd60580dab7c605f2ef93eaa219303a3c9e5cec0e5dfc1"
  },
  {
    "file": "audio/voice/quantity_labda_4.mp3",
    "sha256": "edaa70cf842d25abad6065dce84450dd607bae01b83360db5e36a69d7432e127"
  },
  {
    "file": "audio/voice/quantity_labda_5.mp3",
    "sha256": "9d4ffc16a421cbb5d6b35694712aae519b419ac76c7a7ed1be7aba33ff0293f4"
  },
  {
    "file": "audio/voice/quantity_labda_6.mp3",
    "sha256": "11638e58cd9057574ec522e5f6c7e4b7720b7659ee141d5ff4f74e6848cd6a2a"
  },
  {
    "file": "audio/voice/quantity_labda_7.mp3",
    "sha256": "04c0310bc527ba0531f8cf5befab8c6e1f8a8a86077be2ca8c9be9aae9f8e9a1"
  },
  {
    "file": "audio/voice/quantity_labda_8.mp3",
    "sha256": "4c46ceca23c6cc6c52b9437cf09fb5d02b65fc7f1b5101b49884b6a6c118de94"
  },
  {
    "file": "audio/voice/quantity_labda_9.mp3",
    "sha256": "7dd6dc33fe3532bf42bdd2435a74f66eea0f63da63d81f80fce45477d1869a60"
  },
  {
    "file": "audio/voice/question_alma_1.mp3",
    "sha256": "421ec6c34bd326bb751f76b469d317afd80794bec597ca68567087cb7288cb4a"
  },
  {
    "file": "audio/voice/question_alma_10.mp3",
    "sha256": "a4cda432bfe23d7a5feff84a2ca7997d2a18102bdf4fff586f7dd8c6e5e9b9f5"
  },
  {
    "file": "audio/voice/question_alma_2.mp3",
    "sha256": "cc173d214b7cf4579dde10ba2a5a53eefd5fa998807f52ec2fec3ef82915227d"
  },
  {
    "file": "audio/voice/question_alma_3.mp3",
    "sha256": "0af86ae4acfdd7c9aeaa3db224193b7cad87fa0be76c4b34162d61dead2004cc"
  },
  {
    "file": "audio/voice/question_alma_4.mp3",
    "sha256": "a9c9d8e8140a1ae9cd5f9a81425ff14d57ba76efda8511e3061c6f8ae3abb979"
  },
  {
    "file": "audio/voice/question_alma_5.mp3",
    "sha256": "b21851d39e2271f3d0b673c2225229bbcc6292286eb74af15fa92b5ead657734"
  },
  {
    "file": "audio/voice/question_alma_6.mp3",
    "sha256": "c6ba28f97cad40bb093a55f2b36917231066533712eff674808c156fb3da9d45"
  },
  {
    "file": "audio/voice/question_alma_7.mp3",
    "sha256": "fe28b687f233f5a2378dcf1a009f27afd58ad02841d6063cfb6080f1ed6ec209"
  },
  {
    "file": "audio/voice/question_alma_8.mp3",
    "sha256": "63f19faa2e28744261a37728ad9e5bbae064193b185962646b50fea88debf5bf"
  },
  {
    "file": "audio/voice/question_alma_9.mp3",
    "sha256": "2c2b1a55b71f6c409618d19e1855e066e2e01f4ed10c44c7be765403739a3f75"
  },
  {
    "file": "audio/voice/question_auto_1.mp3",
    "sha256": "400fdd3a188f2c109337d23282311ca75b9b7014a68c359247f9a16c94aee84f"
  },
  {
    "file": "audio/voice/question_auto_10.mp3",
    "sha256": "d4799c147befd8881fb743b9f4b97cd958cf010633b3577f5431126580005ee5"
  },
  {
    "file": "audio/voice/question_auto_2.mp3",
    "sha256": "52fff6e54a9e8ce5760316e0d24a4371b41772646516f875d3261a1be7536aad"
  },
  {
    "file": "audio/voice/question_auto_3.mp3",
    "sha256": "598d74c3886062e3773c9a1cd3a28487dd940ec2959f52202afc18481ec831c0"
  },
  {
    "file": "audio/voice/question_auto_4.mp3",
    "sha256": "42a30a0a9f6543e2e4d413137d450722512a592c90cbe9f537f099c95357f270"
  },
  {
    "file": "audio/voice/question_auto_5.mp3",
    "sha256": "e7f1c5de293c86f413578c27b74cd56f0d44e30076cfa01329d4da5ee5ad8f98"
  },
  {
    "file": "audio/voice/question_auto_6.mp3",
    "sha256": "4e629692fded65c94ee44ca560c1c9f3fe1ef8a0179721e4976d1aa2c6ab4f65"
  },
  {
    "file": "audio/voice/question_auto_7.mp3",
    "sha256": "47bd8e60181068b59d66c3bed2ae9c14616ab1b445cce93db5e3611e5af4aaea"
  },
  {
    "file": "audio/voice/question_auto_8.mp3",
    "sha256": "6821ab6f281e09d52c4e9d2f85744fffa6435791f68d5c530088650b7648c9f7"
  },
  {
    "file": "audio/voice/question_auto_9.mp3",
    "sha256": "82f6693f762dba8a5a045cc406fb9f1b8cf123ffd20692765c02928c61294197"
  },
  {
    "file": "audio/voice/question_labda_1.mp3",
    "sha256": "f03ed71034b50873d2499dc33f7004117b50175c3e84e6a422926a4d1c05cb38"
  },
  {
    "file": "audio/voice/question_labda_10.mp3",
    "sha256": "d9dd24e462ed13fb0b6f40ee882a28d20648979ee75e7ca42259ce123e784470"
  },
  {
    "file": "audio/voice/question_labda_2.mp3",
    "sha256": "d255c3563b92dd314561fb8191f4a13d3726b73c2e2b943ff1c5372814b35f78"
  },
  {
    "file": "audio/voice/question_labda_3.mp3",
    "sha256": "f9dc652cb1ca8bd9aff1c707172b626f1a2553fcc5f235b66b2a23dcfdc072d6"
  },
  {
    "file": "audio/voice/question_labda_4.mp3",
    "sha256": "8a39b424405cc79610b546396573d953b6596a5a5b23f9fe115e2b2142420b48"
  },
  {
    "file": "audio/voice/question_labda_5.mp3",
    "sha256": "64fe7241b911a3e8b6d72bc3b7abc79a77078b99129fdc53de9c8a7604920e57"
  },
  {
    "file": "audio/voice/question_labda_6.mp3",
    "sha256": "be89c63ab9cb00121f20096fd656d88e8b447ffe4a63065ef86c5b0939fa1713"
  },
  {
    "file": "audio/voice/question_labda_7.mp3",
    "sha256": "e6b0cf082202539dc43d44981f5b668df3ea7f039f07217ee56b145889073872"
  },
  {
    "file": "audio/voice/question_labda_8.mp3",
    "sha256": "c71208c27c5d20d56006b1399c70c0c13f28c3e3d828804453a4f9a89a33b697"
  },
  {
    "file": "audio/voice/question_labda_9.mp3",
    "sha256": "61ee12bfa06be6138f99405c2c47fd092b9051ba3da2e211261d3c05103a9056"
  },
  {
    "file": "audio/voice/teddy_alma.mp3",
    "sha256": "862b80a2f8a3677cefb0cb1256d0821666b5e8ddaa1b95c194d201d2dabf5993"
  },
  {
    "file": "audio/voice/teddy_kenyer.mp3",
    "sha256": "9cad6b76f3d319bd1fabae3e98c3005fa0b98e857c34db5d407f9b2bdb198e65"
  },
  {
    "file": "audio/voice/teddy_kifli.mp3",
    "sha256": "e8fdb6aa3a8832f9989f6a02d382fe7d609fa863cd2502667c5031f6f076fe12"
  },
  {
    "file": "audio/voice/teddy_tej.mp3",
    "sha256": "7fc44d571da0e23a06c79c2589071bbfa4892cdc759973be06d7a04e2c926150"
  },
  {
    "file": "audio/voice/teddy_viz.mp3",
    "sha256": "9ef0ea43c5e727a091772fab6f5747adf53cb60fe810ded2c7273e6ecdc5de7f"
  },
  {
    "file": "audio/voice/word_alma.mp3",
    "sha256": "3625ba94fba9b85063edf188d34fd8e5646fb34aeef2d4b7564941ec1a883c85"
  },
  {
    "file": "audio/voice/word_anya.mp3",
    "sha256": "fd1499dd2489ed6971a6e0313db1b6247836f76e5ff1e2fc36c04a88f9cb4a51"
  },
  {
    "file": "audio/voice/word_apa.mp3",
    "sha256": "75900448e9a0f6b57cff362197ccf32a09d261619843322d809d654a7001c378"
  },
  {
    "file": "audio/voice/word_auto.mp3",
    "sha256": "d11434e5e211c454bf7a8bf466fd07954eddb9f12efd48f2570a6270fe7b1746"
  },
  {
    "file": "audio/voice/word_baba.mp3",
    "sha256": "76f9cce278137a6edf509a78119d20d7612e02bd560692195168036299862b02"
  },
  {
    "file": "audio/voice/word_busz.mp3",
    "sha256": "a22cbaa9988c7fbcfaa5e16183e99367b801b30fc38ee817585ae7c192f26a97"
  },
  {
    "file": "audio/voice/word_cica.mp3",
    "sha256": "ea3d3fac1258acbfa6fe7cb9809a0fa09c84a7a7f6e28d222d68d7753a6e841c"
  },
  {
    "file": "audio/voice/word_cipo.mp3",
    "sha256": "148b1df65432c16f5d5984934225c67cd341a395e6418bb1ef7e0c00a0275f83"
  },
  {
    "file": "audio/voice/word_fa.mp3",
    "sha256": "df78699b0b3902c61b38f5ac22d6ed2728483886f17bc2f298bf45ff0a178773"
  },
  {
    "file": "audio/voice/word_furdokad.mp3",
    "sha256": "39f92a1c1da676e90c23dc49349dc623b9ee4b9eae637ae932417d8027425f2a"
  },
  {
    "file": "audio/voice/word_hold.mp3",
    "sha256": "9dabb8106daa4fc526ee25c3806037fecc2bdf2338cbe589a97a385ef1324042"
  },
  {
    "file": "audio/voice/word_kanal.mp3",
    "sha256": "01cfe878f5fe53be0ffd28e6010a92323dfea28a12e4dddea0edd1375de95974"
  },
  {
    "file": "audio/voice/word_kenyer.mp3",
    "sha256": "30f096d821a3a6af2faf9b5e95d2da4511553a1cef09deee635df66c1a76bd79"
  },
  {
    "file": "audio/voice/word_kifli.mp3",
    "sha256": "c45fd0996d351d1a0fca398f3b9123fe461f3fe823719603ac997872da7cb25e"
  },
  {
    "file": "audio/voice/word_kutya.mp3",
    "sha256": "326fe99db5b86a61fae5c923a0a7e2db87490ebdc30d77841a15b4b2df532c55"
  },
  {
    "file": "audio/voice/word_labda.mp3",
    "sha256": "49153e835250302e8e84f2b14666628c755715bed058292e6a48486daeab8566"
  },
  {
    "file": "audio/voice/word_maci.mp3",
    "sha256": "ed2972b6bb3b512149e9a47886db0fca15ea499eb64b583434cd99c71a2b2272"
  },
  {
    "file": "audio/voice/word_nap.mp3",
    "sha256": "affe636b008835324919234ec25d56b7198444cd2f744b8d237e3523ee5fccf8"
  },
  {
    "file": "audio/voice/word_sapka.mp3",
    "sha256": "bda42329543b154029af5744c75b8dce8bdfa40029a40e06c09e3a50b996540e"
  },
  {
    "file": "audio/voice/word_szia.mp3",
    "sha256": "408b7fecb809dc85945c938478709ba97d9c32b3ea833556208ff70fc370b728"
  },
  {
    "file": "audio/voice/word_tej.mp3",
    "sha256": "0b3fd05f577f81191a86bf6c9b115ff04bf746f175d44a7f63a4ab8c994f62b7"
  },
  {
    "file": "audio/voice/word_virag.mp3",
    "sha256": "fcff529a6ebdccca0e6f0da38c2d55f4d610a7c775d4444bccd3740651e56d73"
  },
  {
    "file": "audio/voice/word_viz.mp3",
    "sha256": "431f0ded88626b9f79106fac3829bdfd1d4a9f1b9fe6770367b8a63f6fbf7dc2"
  },
  {
    "file": "audio/voice/word_vonat.mp3",
    "sha256": "c101a03282045e77859b7b11694fb3809981560bebdd3343bbf5147bbabf6433"
  },
  {
    "file": "audio/voice/workshop_add_rod.mp3",
    "sha256": "760f7844bd99087ae368a52f2a02322aa96c75d9db30213416ac80282ddcb29e"
  },
  {
    "file": "audio/voice/workshop_balance_1.mp3",
    "sha256": "1597c940b444fc0f1b6acb6ffe30f9e8a78e34ce28ab8830d740528e886a1278"
  },
  {
    "file": "audio/voice/workshop_balance_2.mp3",
    "sha256": "00730382458b500be31f147087fa4894b19705a70844650efaffc13101d6d0ac"
  },
  {
    "file": "audio/voice/workshop_balance_3.mp3",
    "sha256": "f5a66e923fde5ac6d3016c8509acbec498dc335e64c00e39a7820066979b0614"
  },
  {
    "file": "audio/voice/workshop_balance_done.mp3",
    "sha256": "d2a2156a2eda8d9ca45e2bc18c304ac504546dbd42980d970e3dc6827fc1ba01"
  },
  {
    "file": "audio/voice/workshop_balance_hint1.mp3",
    "sha256": "de6f922c121ff76ff1aeca05235607d87c25b5bc159957b98706700842c668e0"
  },
  {
    "file": "audio/voice/workshop_balance_hint2.mp3",
    "sha256": "0b0e889c959b33b1475a8b367d2faeca5bacb8f4300e44e37b5d2d3f4bf1342c"
  },
  {
    "file": "audio/voice/workshop_balance_hint3.mp3",
    "sha256": "50721007a4cf6b441587a6ac02193a6d9d6eaa86b92eb73b2340be78a452295c"
  },
  {
    "file": "audio/voice/workshop_balance_retry.mp3",
    "sha256": "78ca1d2f3feb824fd0f7ca9253dd2a237fef8d15650e375f9ee663601c7a94c8"
  },
  {
    "file": "audio/voice/workshop_level_1.mp3",
    "sha256": "b1ca5d839a74fbd11b56ca0fb40a3ec2a764655e131c9f65bff8f0fe10cf60a8"
  },
  {
    "file": "audio/voice/workshop_level_2.mp3",
    "sha256": "05a365e2bc417cb6873fd3339b09b9b8641dd517d88b2fd4edbe903f15e47c32"
  },
  {
    "file": "audio/voice/workshop_level_3.mp3",
    "sha256": "63e0b910afa3c15187c235416c471ab79d378858e398da10751e9fc6a701d630"
  },
  {
    "file": "audio/voice/workshop_menu.mp3",
    "sha256": "34764868933f5f14d165f1d83befd6b78d17506e8bbc5ed5d09e8f5545851569"
  },
  {
    "file": "audio/voice/workshop_n_0.mp3",
    "sha256": "36db70d7b5a0c2160d61bb015db97aeff41e0b5b8e8ccd3634ffe14191e9f9d5"
  },
  {
    "file": "audio/voice/workshop_n_1.mp3",
    "sha256": "5540b5b3e8e36ccc27ca950e2b404d64a8c85d9db7516665f3a8ab1b32e3c576"
  },
  {
    "file": "audio/voice/workshop_n_10.mp3",
    "sha256": "798839668ba138b2f97600d0c923a2f9620d3c8cf405a25dd20440e193dc23ef"
  },
  {
    "file": "audio/voice/workshop_n_11.mp3",
    "sha256": "86e51450fee470784cacbf9fa163cc727b9ee9102860f1807e702df6a3ea6893"
  },
  {
    "file": "audio/voice/workshop_n_12.mp3",
    "sha256": "b379c045f0d34f42ade00fb9a60f90234fab596be6ed0d90ca1c59e395c23c77"
  },
  {
    "file": "audio/voice/workshop_n_13.mp3",
    "sha256": "b7872b31726e2b1f4df4e13ab3b76b95690f2d18fc4a63d794f21a6b34f55712"
  },
  {
    "file": "audio/voice/workshop_n_14.mp3",
    "sha256": "72914795b3d239e3103ba5555bb29d4fc3a1e5386ebd976afd64f9d67e18ae5f"
  },
  {
    "file": "audio/voice/workshop_n_15.mp3",
    "sha256": "1e81d8e4748c5417ab0dc430c7e989a75dd6cae37f2c17c434eaa2371d607fbf"
  },
  {
    "file": "audio/voice/workshop_n_2.mp3",
    "sha256": "bc42cdfd240fb7e3c9f6c333185c58b0c45a2682c8985ee070482fd6e2052cad"
  },
  {
    "file": "audio/voice/workshop_n_3.mp3",
    "sha256": "1d0319a5b62384a07393cd056c3d955a57846e6b7df23bde5f0d8a632c846ab6"
  },
  {
    "file": "audio/voice/workshop_n_4.mp3",
    "sha256": "6a1a3f3962716aee7243530cdf3544ea6055c23e87ddcbe3c5687a748d62b272"
  },
  {
    "file": "audio/voice/workshop_n_5.mp3",
    "sha256": "6caf4be20ab1db978d4b8d5adef636e18e7fe2b7361cdad72aa36acab31c5c72"
  },
  {
    "file": "audio/voice/workshop_n_6.mp3",
    "sha256": "a1374dca51f5bc459c3629021a82d57ed91a58292dbbebbfcafa4e158313aaa1"
  },
  {
    "file": "audio/voice/workshop_n_7.mp3",
    "sha256": "033958cfa4d997ec842af6ae60af4efbc3ca0214f6cca0794b191b9945a5e78c"
  },
  {
    "file": "audio/voice/workshop_n_8.mp3",
    "sha256": "588b83cd2fc6ac8647fe08dbc173a736013d9f15691b95406ca0f931607ffbc1"
  },
  {
    "file": "audio/voice/workshop_n_9.mp3",
    "sha256": "007f3f20a094210dccbf556f029e9276d8d3cf7855a470f5a189baed929317ae"
  },
  {
    "file": "audio/voice/workshop_only_big.mp3",
    "sha256": "39c57bd1bd6834cb112b34c5ce19d13ab831224dcacb89126a50dbf7f3598481"
  },
  {
    "file": "audio/voice/workshop_only_small.mp3",
    "sha256": "26b41ce9d38f5822d4970bc97f42a70ce6d03b8b54cad19af90591a76c1a151f"
  },
  {
    "file": "audio/voice/workshop_pattern_1.mp3",
    "sha256": "683587d70c00c0a960e1efd16e16c68ee5588e1fa6940dd38ad41a49c4f6032a"
  },
  {
    "file": "audio/voice/workshop_pattern_2.mp3",
    "sha256": "4e4bb8cfc6285b5972f4a8f0e5f11adf403ba7da7b7b2894adba5e13d5d4c2c6"
  },
  {
    "file": "audio/voice/workshop_pattern_3.mp3",
    "sha256": "64af8693909e1535b91de8ec3c6ca908ea3c618a99c4ef5712ec6ffcc6b9e9f0"
  },
  {
    "file": "audio/voice/workshop_pattern_done.mp3",
    "sha256": "b6228ef6c7a30dee41b0e0d60a065ac2a3a489bcb9c5294f4669dcdf71b0e553"
  },
  {
    "file": "audio/voice/workshop_pattern_hint1.mp3",
    "sha256": "b765a3649ca93169dc70fec6980a7b3f0956d66ff55e44d97edeb87ea413e08d"
  },
  {
    "file": "audio/voice/workshop_pattern_hint2.mp3",
    "sha256": "a72cad7073b683047714ff0dd90cd24ef68dc8485c8ede284e95e34c9e97a636"
  },
  {
    "file": "audio/voice/workshop_pattern_hint3.mp3",
    "sha256": "ed424a81938abb812f44de13101006ee5811d2283f1491ab8d74408117c9e40e"
  },
  {
    "file": "audio/voice/workshop_pattern_retry.mp3",
    "sha256": "2af05617168d65c2390ceb084238a232f987c1e3300013c4c6bebf029d7b6d63"
  },
  {
    "file": "audio/voice/workshop_ready.mp3",
    "sha256": "1aac928b4360254ceb8b16f6304ef47431be59d3e1b73cbadac29440215f1829"
  },
  {
    "file": "audio/voice/workshop_sort_1.mp3",
    "sha256": "015c897e0729cca3b0b7f3b7469671accfe84acf72831c752ef7434699dc9baf"
  },
  {
    "file": "audio/voice/workshop_sort_2.mp3",
    "sha256": "ae3dea3a4e716056438d601156bcdab694420555656573a5f035f19c6a8046af"
  },
  {
    "file": "audio/voice/workshop_sort_3.mp3",
    "sha256": "a69d57dd02944788daadc1c97f719423fb7f16a82ce7873dff54b0324952b702"
  },
  {
    "file": "audio/voice/workshop_sort_done.mp3",
    "sha256": "3a745159931a4c1d4949498b8af661f49728d37bf58b8e02898b388b63b9ed68"
  },
  {
    "file": "audio/voice/workshop_sort_hint1.mp3",
    "sha256": "5a6237e20103117cff139c9d246f8d426abe0ceef20103f4853518296c97f5fc"
  },
  {
    "file": "audio/voice/workshop_sort_hint2.mp3",
    "sha256": "60169f18302bb822661388cf278d4f0533ba55e0400579f3701d6f22b99b2bcc"
  },
  {
    "file": "audio/voice/workshop_sort_hint3.mp3",
    "sha256": "5551adc83b0eddc204e5b33b6172c5f38fa830a3e20c90a0c0f63435335ad98e"
  },
  {
    "file": "audio/voice/workshop_sort_retry.mp3",
    "sha256": "cdd8f9c1790f6185e34b07cdaaf3497e5cac8100f3ac33ca5f7c23ff4162a6db"
  },
  {
    "file": "audio/voice/workshop_take_rod.mp3",
    "sha256": "fcf058180a18dddd08ac12f754e72c4ecf57fb966510ab56ceaacdcdc93a67bf"
  },
  {
    "file": "audio/voice/workshop_target.mp3",
    "sha256": "aa0c76397c1ea194b00ec881f8c9908249571f941bd2cc827db225126471904d"
  },
  {
    "file": "audio/vonat.mp3",
    "sha256": "db9b4a991e119e3d78ac71ac1896cf50889f56fdee979b9bef2355523775ff0e"
  },
  {
    "file": "child-ui.css",
    "sha256": "253131abc64b6e75b7c164e08290f53489f16da05d38f79a6e3c3ae98546d939"
  },
  {
    "file": "cloud-save-queue.js",
    "sha256": "172e1ce2b92a1189277f9ae41fd978b7c69c94925223d6d4d8c668fe1f9aa6be"
  },
  {
    "file": "dress-art.js",
    "sha256": "938f1dfa3433f21173fe3a27d48f94b4f5f9bbe9f539e9615f3871496923a5d3"
  },
  {
    "file": "dress-data.js",
    "sha256": "7638a1b16d2136e109fc67f080f7435de10467d40f20e47c01ba33483f0ed891"
  },
  {
    "file": "dress-game.css",
    "sha256": "1f7c392d730cbdb51e3c98c290c5b0ba1192f7dca2346c75926c5240a0a3e1b3"
  },
  {
    "file": "dress-game.js",
    "sha256": "065b7e06b94323f8cdc404e0b12d03b4962e7cee2c8109cc557f49357a230f39"
  },
  {
    "file": "game-data.js",
    "sha256": "7255eb4199054d8f81365e7e0895a1e9bf3d089a091ad957c834ce5fd2d63e94"
  },
  {
    "file": "icons/apple-touch-icon.png",
    "sha256": "fe5dc93cf0ee10d10b335c3f704c22cf9a17c27e3bef55c639e92e8a974a4a0a"
  },
  {
    "file": "icons/icon-192.png",
    "sha256": "8ec214a50f05143968ce237c0d7f4a8d1d70a7c4820bf5e080c6ae2619864012"
  },
  {
    "file": "icons/icon-512.png",
    "sha256": "c12d47b6030cc1ae14508598fe7df33c6b62de281e792e253d4bc3bf48bf5180"
  },
  {
    "file": "icons/icon.svg",
    "sha256": "af04b9c18c95b6b98b81de52ef7bc96d06871bc8d108fcd91cc63aeb484fa9fc"
  },
  {
    "file": "index.html",
    "sha256": "40746c8668aab2fbe44eafa596386a20c7bcab0ec193b2fc54d34c3bbd0e77e6"
  },
  {
    "file": "listening-game.js",
    "sha256": "e2ee7cc8047634f5cc7404d1864e208262f953d11446375f5f7d3a1e9f27a683"
  },
  {
    "file": "logic-data.js",
    "sha256": "6e898d8dc05b986859ce1ece67d0ae6341cdccf9915d53605dafcdd64a49cb6e"
  },
  {
    "file": "logic-game.js",
    "sha256": "9e45e71c57b0cd39367968241efc27833379368813b717981759422814842aa6"
  },
  {
    "file": "logic-voice.js",
    "sha256": "e20dc06997171f0a62f73e3b187466fe43a312410b8937706fd6fb8596e1bff9"
  },
  {
    "file": "logic.css",
    "sha256": "6fdb00882c78accee590b6c3c8e8da1ee34efd7dc689599923e3e747ddf49513"
  },
  {
    "file": "memory-data.js",
    "sha256": "b0e98367c01e5390705f2c07e0c24fbf90a195df2d53635aa73d59d87d5fc6f1"
  },
  {
    "file": "memory-game.js",
    "sha256": "e1374adb3b711a2774a00161e091fd15fa345f1133b27ab41a9d1a4c4ae0c6d4"
  },
  {
    "file": "memory.css",
    "sha256": "2fca5973d8b45657ee75bb979179f770a800c1e30312cbf0a3fe1b904d5e435b"
  },
  {
    "file": "meseliget-data.js",
    "sha256": "a5ff0c4d90f690aafe73d59c1b755b4f5e09595b7bf5ee2763836ac073d6a008"
  },
  {
    "file": "meseliget-game.js",
    "sha256": "0ade255c78e79322129294edde16c085fc349fcdebd1c09c1448dcf100d0e58b"
  },
  {
    "file": "meseliget.css",
    "sha256": "c09b8fc65702b927c1b80b3c6b7b8eb6f023a88e3d962bb7f55b443f5261dd5f"
  },
  {
    "file": "offline-client.js",
    "sha256": "57fa7904eed51f550f1e081bee402f738b1ecb3c030b9cb5202b247d13bc8c8d"
  },
  {
    "file": "portal.css",
    "sha256": "570cd88dbf7c72377c54b84361156504849ad5fa432678e1a97a865afae7ce9a"
  },
  {
    "file": "progress-data.js",
    "sha256": "dd0dd23ca1dc36a3b7e3d7019ea3b5a8c14447d44ab95427379fb3a3dd22edfd"
  },
  {
    "file": "progress-profiles.js",
    "sha256": "4e67d8a831e08ce7475f4ac8599d1248a8860208014535f0a9be799ad32b344a"
  },
  {
    "file": "progress-tools.js",
    "sha256": "aae65508c45ac9392510e32e57586e97fd6834c5b5cc35843098eaa822bd431d"
  },
  {
    "file": "speech-matching.js",
    "sha256": "f22fe8259c20640b2f5d2253bcb7ebb0f7d16100e537a0e146c21e5287a6aa4e"
  },
  {
    "file": "speech-recognition.js",
    "sha256": "22d5e890c6e13254ed8da611e89af3e378c0c6271c5fb829f9f2de67b0c2461f"
  },
  {
    "file": "styles.css",
    "sha256": "b03e704a066fdbdcf0d5bbcca94257ab14a8560326b5a1bdca08b3ec3c40afc8"
  },
  {
    "file": "supabase-config.js",
    "sha256": "121a1a2198f6373fde459f21ee70782f18ae6e256c0cdeca46959fdff221b9c3"
  },
  {
    "file": "teddy-game.css",
    "sha256": "3b537ef2d7426d0ba034a480baa3774bb1680d99369ed9c2bcc11a4babb7d5f0"
  },
  {
    "file": "teddy-game.js",
    "sha256": "9897a2ead16ab0ad2b929d061b0afbd703127491801c3c36b94c5438711f6984"
  },
  {
    "file": "voice-library.js",
    "sha256": "e8e9181a45dabe77f54f35043ca9f243a12606a2d0b613f7f9a157771818a44e"
  },
  {
    "file": "workshop-data.js",
    "sha256": "8104efe2c4a4912743c5b1ffc446ef94c7bdf3a3809479b526817654dc84e08a"
  },
  {
    "file": "workshop-game.js",
    "sha256": "58b17534d0ffcc81c399e88a85cbd04e06e500350df2e34cd6134c3ceb97fd92"
  },
  {
    "file": "workshop-voice.js",
    "sha256": "5033cda244474786e09fce284e948363390293924b4e2954de0a4c5dec866056"
  },
  {
    "file": "workshop.css",
    "sha256": "faaed0a9aac1d27141970585d87c31d8a494247837b79691c483d63f005afc6c"
  }
];

/* CACHE_VERSION and ASSETS are supplied by scripts/build-offline.mjs. */
const SCOPE = new URL(self.registration.scope);
const CACHE_PREFIX = `beszedtanulas:${SCOPE.href}:`;
const CACHE_NAME = CACHE_PREFIX + CACHE_VERSION;
const INDEX_URL = new URL("index.html", SCOPE).href;
const ASSET_URLS = new Set(ASSETS.map(asset => new URL(asset.file, SCOPE).href));

async function tellClients(message) {
  const clients = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
  for (const client of clients) {
    if (client.url.startsWith(SCOPE.href)) client.postMessage({ ...message, version: CACHE_VERSION });
  }
}

async function installOffline(repair = false) {
  const cache = await caches.open(CACHE_NAME);
  let completed = 0;
  let next = 0;
  let failure;
  await tellClients({ type: "OFFLINE_PROGRESS", completed, total: ASSETS.length });
  const download = async () => {
    while (next < ASSETS.length && !failure) {
      const asset = ASSETS[next++];
      const abort = new AbortController();
      const timer = setTimeout(() => abort.abort(), 15000);
      try {
        const url = new URL(asset.file, SCOPE).href;
        if (repair && await cache.match(url)) {
          completed += 1;
          await tellClients({ type: "OFFLINE_PROGRESS", completed, total: ASSETS.length });
          continue;
        }
        const response = await fetch(new Request(url, { cache: "reload", credentials: "same-origin", signal: abort.signal }));
        if (response.status !== 200) throw new Error(`Download failed: ${asset.file}`);
        const data = await response.clone().arrayBuffer();
        const digest = await crypto.subtle.digest("SHA-256", data);
        const hash = Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, "0")).join("");
        if (hash !== asset.sha256) throw new Error(`File changed: ${asset.file}`);
        await cache.put(url, response);
        completed += 1;
        await tellClients({ type: "OFFLINE_PROGRESS", completed, total: ASSETS.length });
      } catch (error) {
        failure = error;
      } finally {
        clearTimeout(timer);
      }
    }
  };
  // Let in-flight writes finish before removing an incomplete new cache.
  await Promise.all(Array.from({ length: 6 }, download));
  if (failure) {
    if (!repair) await caches.delete(CACHE_NAME);
    await tellClients({ type: "OFFLINE_ERROR" });
    throw failure;
  }
  await tellClients({ type: repair ? "OFFLINE_READY" : "OFFLINE_DOWNLOADED", total: ASSETS.length });
  // Updates wait until all existing windows close or a parent requests activation.
}

self.addEventListener("install", event => event.waitUntil(installOffline()));

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(key => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME).map(key => caches.delete(key)));
    await self.clients.claim();
    await tellClients({ type: "OFFLINE_READY", total: ASSETS.length });
  })());
});

async function rangeResponse(response, range) {
  const match = /^bytes=(\d*)-(\d*)$/.exec(range || "");
  // Unsupported multipart/invalid ranges may be ignored with a full 200 response.
  if (!match || (!match[1] && !match[2])) return response;
  const data = await response.arrayBuffer();
  const length = data.byteLength;
  const start = match[1] ? Number(match[1]) : Math.max(0, length - Number(match[2]));
  const end = match[1] && match[2] ? Math.min(Number(match[2]), length - 1) : length - 1;
  if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start > end || start >= length || (!match[1] && Number(match[2]) === 0)) {
    return new Response(null, { status: 416, headers: { "Content-Range": `bytes */${length}` } });
  }
  const headers = new Headers(response.headers);
  headers.delete("Content-Encoding");
  headers.set("Content-Range", `bytes ${start}-${end}/${length}`);
  headers.set("Content-Length", String(end - start + 1));
  headers.set("Accept-Ranges", "bytes");
  return new Response(data.slice(start, end + 1), { status: 206, headers });
}

async function serveOffline(request, key) {
  const cache = await caches.open(CACHE_NAME);
  const response = await cache.match(key);
  if (!response) return fetch(request);
  return request.headers.has("Range") ? rangeResponse(response, request.headers.get("Range")) : response;
}

self.addEventListener("fetch", event => {
  if (event.request.method !== "GET") return;
  const url = new URL(event.request.url);
  if (url.origin !== SCOPE.origin) return;
  const key = url.origin + url.pathname;
  const isHome = event.request.mode === "navigate" && (key === SCOPE.href || key === INDEX_URL);
  if (isHome || ASSET_URLS.has(key)) {
    event.respondWith(serveOffline(event.request, isHome ? INDEX_URL : key));
  }
});

let repairInFlight;
self.addEventListener("message", event => {
  if (event.data?.type === "REPAIR_OFFLINE") {
    repairInFlight ||= installOffline(true).finally(() => { repairInFlight = null; });
    event.waitUntil(repairInFlight);
  }
  if (event.data?.type === "OFFLINE_STATUS") {
    event.waitUntil((async () => {
      const cache = await caches.open(CACHE_NAME);
      const complete = (await cache.keys()).length === ASSETS.length;
      event.source?.postMessage({ type: complete ? "OFFLINE_READY" : "OFFLINE_INCOMPLETE", version: CACHE_VERSION, total: ASSETS.length });
    })());
  }
  if (event.data?.type === "ACTIVATE_UPDATE") {
    event.waitUntil((async () => {
      const clients = (await self.clients.matchAll({ type: "window", includeUncontrolled: true })).filter(client => client.url.startsWith(SCOPE.href));
      if (clients.some(client => client.id !== event.source?.id)) {
        event.source?.postMessage({ type: "UPDATE_CLOSE_WINDOWS" });
        return;
      }
      await self.skipWaiting();
    })());
  }
});
