// Generated by npm run build-offline. Do not edit this file directly.
const CACHE_VERSION = "41dddceb23d2bfff";
const ASSETS = [
  {
    "file": "app.js",
    "sha256": "17b06540056c1d408402f3d760056c449a0315bc39321413fd3959df6fea4ba7"
  },
  {
    "file": "app.webmanifest",
    "sha256": "7c72744d874f72772abd70675cf71419db4f9b73954b56a75d18c86130993170"
  },
  {
    "file": "assets/furfang-fox.png",
    "sha256": "ba7e0fea9fed0fefc1f5caa2088d9e031e09b03b1efb4431e0c6a4b9a1ba70e1"
  },
  {
    "file": "audio/alma.mp3",
    "sha256": "4c15875a03cb601932dd497aa80331c245b8c7b696326f65825f3f3648eb164e"
  },
  {
    "file": "audio/anya.mp3",
    "sha256": "8238d02e87ea9568800e90db7f57aa579dbd668d3b4fd9c090e5f423a39e3554"
  },
  {
    "file": "audio/apa.mp3",
    "sha256": "6cf6745ee3dce03782df169e6077174a2852a534d5ce21282ec9d8c5080a7ec7"
  },
  {
    "file": "audio/auto.mp3",
    "sha256": "25c2fc9369e57352f3cdddd423222be5f45818f8d513e33832302b681d2789e1"
  },
  {
    "file": "audio/baba.mp3",
    "sha256": "0957d2067d39117d2fefb350cdc594671f78876c77f052e09aefaff5f7b5b5d4"
  },
  {
    "file": "audio/busz.mp3",
    "sha256": "68d819a050e34831f191f0d787053a2ffb0ed22fdaf9861702551e96cb5ee13d"
  },
  {
    "file": "audio/cica.mp3",
    "sha256": "b0864eb57142ec605af6a15d0b39f14d7ba2a9e1bebaa9cf87cc1d363d7b12c4"
  },
  {
    "file": "audio/cipo.mp3",
    "sha256": "7de5a236096c847366741287fbdc848deb5d174d8a9dd0e45aa4d20ee1687ae0"
  },
  {
    "file": "audio/fa.mp3",
    "sha256": "7dd68fba16068e4dc4d2082bc88421b881038ecdc33bd9c9924700e14c3d68c5"
  },
  {
    "file": "audio/furdokad.mp3",
    "sha256": "078f4ea1a6a31af0a9efe2fc07fb558790728f94da2eab71c574920fb9cfc8f9"
  },
  {
    "file": "audio/hold.mp3",
    "sha256": "ed7012d36fb4adf502c8e91be2eadeb3ede1dd0c81d3287b699e270c520d46c0"
  },
  {
    "file": "audio/kanal.mp3",
    "sha256": "3179910e8fc69e25e9577ffdf01652b290f374898dae6f3e1deb836afe377c17"
  },
  {
    "file": "audio/kenyer.mp3",
    "sha256": "eeaf0fe379ef5e1de800d9c6a7e7e9f70062d8ffe2e2da74c68948179d4f82c5"
  },
  {
    "file": "audio/kifli.mp3",
    "sha256": "13c217b2842abb74ade4cb82cfddc46abbc4cb628bc5bbace2e20a8fee4c3f6b"
  },
  {
    "file": "audio/kutya.mp3",
    "sha256": "e546af267dd7642a3c52c3504b39edd6324e3c5122fe4638e672a1e29317be46"
  },
  {
    "file": "audio/labda.mp3",
    "sha256": "0613c9bb41f9a7ba038d6b5f8029104d71625e5c27f84b5e3a2f6a1b0cbd60aa"
  },
  {
    "file": "audio/maci.mp3",
    "sha256": "7a1621baa490765dd21aa293585648ac0c7fdd2832bd6fb7c5910eec2b4e14a1"
  },
  {
    "file": "audio/nap.mp3",
    "sha256": "55665e77ead0ab9de03ec8f57ec220662644a2f22aece666b2de24a4a16d4e3b"
  },
  {
    "file": "audio/sapka.mp3",
    "sha256": "5ba8d03dcd17da4e5479a64eb38b900f3e7bf48947a6683bea16ea7ad98a134e"
  },
  {
    "file": "audio/szia.mp3",
    "sha256": "7efcb01bcbad727d7dd11621da5ac0d50c35da2cba091fea3250703d7184cc41"
  },
  {
    "file": "audio/tej.mp3",
    "sha256": "e78719f0f1708104c73ba68d278f97f6e13fce6187d522b738048c079c00044f"
  },
  {
    "file": "audio/virag.mp3",
    "sha256": "02fb415a3381fe69e74457200367ae89fda1ffcd7cfb9dccff2349c86e4dd4f2"
  },
  {
    "file": "audio/viz.mp3",
    "sha256": "b320559775eac5cadd789008c9e1019939c42f7b596b70ac95ec700a28345c0b"
  },
  {
    "file": "audio/voice/dress_request_cipo.mp3",
    "sha256": "47936f112b36f58d6ab500dc7c529d67cf9b4c538d949cf8495f7b7d1bbf9174"
  },
  {
    "file": "audio/voice/dress_request_polo.mp3",
    "sha256": "b5103909d2bf167b508bf1a2eeaa9c52d700b4d7a499abc60cc5c99096d3852e"
  },
  {
    "file": "audio/voice/dress_request_sal.mp3",
    "sha256": "f38172a0d9b9b44930a5db9ed58e6669a9d0a519b7752f3ba0bbe425926e072a"
  },
  {
    "file": "audio/voice/dress_request_sapka.mp3",
    "sha256": "5473630dc86825adb977b1c48a0c8d59addc7510a3f3665bb0dd260957d1360b"
  },
  {
    "file": "audio/voice/dress_thanks_cipo.mp3",
    "sha256": "60bc4a1d5ee92474dca2b59cdb76f99df0e6173a326b5fea575291bd4e23dcbd"
  },
  {
    "file": "audio/voice/dress_thanks_polo.mp3",
    "sha256": "5d9a05e79ce4ea1643281c05eb0a949ef3383a9e51ce3cca50e1103fa2a75ac2"
  },
  {
    "file": "audio/voice/dress_thanks_sal.mp3",
    "sha256": "8ad67ce99ee6c0cc6059267dbb14262fff631f2098dd13751e9cccab871b82b2"
  },
  {
    "file": "audio/voice/dress_thanks_sapka.mp3",
    "sha256": "d6a6f14272c540b59418a7e06925946ba5507affd26726a8b3424aeff09843ab"
  },
  {
    "file": "audio/voice/guide_again.mp3",
    "sha256": "c237b2f01b938a8fc24ef86c651ab700387a6a3fdc963e77c8b38f766b02e1d9"
  },
  {
    "file": "audio/voice/guide_animals.mp3",
    "sha256": "ba3b510c000a69be53b1d14b3bb20242d4f15118d801ea01346fa69f66244fac"
  },
  {
    "file": "audio/voice/guide_cards.mp3",
    "sha256": "ecf0ab00f5c6e0ba7f9ba45e23dc99f4985a36dd497eaf98593004b6f2572813"
  },
  {
    "file": "audio/voice/guide_count.mp3",
    "sha256": "d382e90718f414641e220490b384d6e1ec73445556bfc397735fe850eddb420d"
  },
  {
    "file": "audio/voice/guide_dress.mp3",
    "sha256": "45a962a89018c945c21429ea609fc44e9afe6f0717b34300842cddfce814fd62"
  },
  {
    "file": "audio/voice/guide_dress_finished.mp3",
    "sha256": "8e88f7965538ccd07124d2a1756af4bceb2d2e19adab24d35bc39e3169387a57"
  },
  {
    "file": "audio/voice/guide_family.mp3",
    "sha256": "b240b992f9da47e640027be6f536c8733ee8efc5e310e6056d59e356c8ff3106"
  },
  {
    "file": "audio/voice/guide_finished.mp3",
    "sha256": "94e78ce777ab0e01267991b3a89cbfa0fa19a3634b777fd80743e4322216bfff"
  },
  {
    "file": "audio/voice/guide_flip.mp3",
    "sha256": "cdee3f82a5e4adcb341f82088562adb18429ef6b4d40668f13b6c89040e795bf"
  },
  {
    "file": "audio/voice/guide_food.mp3",
    "sha256": "1590fd77ef17f0697bf845202afb13f709de69fa02251929bd6dd62f318fa59d"
  },
  {
    "file": "audio/voice/guide_good.mp3",
    "sha256": "3c9c538c2eebb8c1db43dcc9df629ff785d9d1c8cae2584e3a36a08be68de55c"
  },
  {
    "file": "audio/voice/guide_goodbye.mp3",
    "sha256": "4c8c58a41ae4f6c450588a4f87f06c6a08846d5e17769133fb2344f839a6335b"
  },
  {
    "file": "audio/voice/guide_home.mp3",
    "sha256": "2291145f6430c7cc8be44656db62f0b5d73dafb2f781aa68e0dae789a60f18d0"
  },
  {
    "file": "audio/voice/guide_imitate.mp3",
    "sha256": "b3fe4acb9a212658210e986f4ac0c50af0d214b0e4a5d1075f6a76474b4cf6ed"
  },
  {
    "file": "audio/voice/guide_listening.mp3",
    "sha256": "277244df6ec9242a50ded8d9e40535adec23cd702989a9f56ab769d49b6a35b8"
  },
  {
    "file": "audio/voice/guide_listening_game.mp3",
    "sha256": "27706fb01f9069ce8dc1fdc66cc8333ed2e3306f80f1dba743b5092a2e319d2c"
  },
  {
    "file": "audio/voice/guide_mic_help.mp3",
    "sha256": "8e26a10360a6d663636d47dad37ab2169972dd7178bf60d1d64e914d088468e7"
  },
  {
    "file": "audio/voice/guide_nature.mp3",
    "sha256": "f6ecd57eb55478b86d9681089f8ec7d44c69c4bf806d1e578f84d325563fdd7b"
  },
  {
    "file": "audio/voice/guide_number_menu.mp3",
    "sha256": "fc3507c8f34759c825b5da77870bfb799fbb1aa784c073ac3c96d85c7c65756f"
  },
  {
    "file": "audio/voice/guide_one_word.mp3",
    "sha256": "c44772ec4aca0d18cc540bfc4d53520f7b8a429425ea8c4516d6287fbee4e28e"
  },
  {
    "file": "audio/voice/guide_phrase.mp3",
    "sha256": "14fe89440e60c6a4607b93632f7170ac68ee798d36a16541aa78af31ba0e557e"
  },
  {
    "file": "audio/voice/guide_picture_menu.mp3",
    "sha256": "9b79c182f603d84452ae6dbbae8275db7c269edd745b8609f6cc1605aeea7b97"
  },
  {
    "file": "audio/voice/guide_play.mp3",
    "sha256": "a2bf839f65897e751ea9308223a838062d3716bd94ab779f54f5e1b20b101b7a"
  },
  {
    "file": "audio/voice/guide_play_menu.mp3",
    "sha256": "9fed21379d61e50549ac32ab0649897cce480741bbaf0fd0aab5d88e5e2fafc8"
  },
  {
    "file": "audio/voice/guide_play_menu_more.mp3",
    "sha256": "8da5e509de2071a517ce70b06db16ea1c0b24e79ac44632be2b85d103aec6d81"
  },
  {
    "file": "audio/voice/guide_practice.mp3",
    "sha256": "c79af5fa671393acb810f6122bb3a94928033b9c7759b4b0532295e484da470e"
  },
  {
    "file": "audio/voice/guide_quiz.mp3",
    "sha256": "f9cc77f72ba6e1f795a07c6db3f8ae58b49136285472b3ab8c863bb7059e985e"
  },
  {
    "file": "audio/voice/guide_retry_count.mp3",
    "sha256": "9655c54f510a85a4014075dfbe11d2c95d0e7b917e109ed310f10e3ee2c9587b"
  },
  {
    "file": "audio/voice/guide_teddy.mp3",
    "sha256": "0924f9f2b5b65498f2bee0abe46194c959fb9fc33f2cdd7617bcfe6d9f1c068f"
  },
  {
    "file": "audio/voice/guide_teddy_finished.mp3",
    "sha256": "2419ae55350a21562f0d966f23bb74daa05e17442a3d12e292695b9978ba6da5"
  },
  {
    "file": "audio/voice/guide_teddy_thanks.mp3",
    "sha256": "fdd98d550ca3d07f399a015164f1c4e74faeec141f32052880ac79d889fb71bc"
  },
  {
    "file": "audio/voice/guide_topics.mp3",
    "sha256": "06583b543917b375782ba83b2ba9817a6809268f18962f258043820e32d06fa5"
  },
  {
    "file": "audio/voice/guide_two_words.mp3",
    "sha256": "0d8a3db5eff9d8c46b446d61f2b47fe59d893b2beb58dcf67ff1c37454bc70a3"
  },
  {
    "file": "audio/voice/guide_welcome.mp3",
    "sha256": "b3f34e12095723996028e31800f73a0cfa66fc39f930904ebff12695d7cd6aab"
  },
  {
    "file": "audio/voice/logic_apple.mp3",
    "sha256": "d1caac843ec455093db710a716a60955584dcd009dea6da339e747f9a27a8a9c"
  },
  {
    "file": "audio/voice/logic_change.mp3",
    "sha256": "94aa02cd0c3f4670e4427f631b669b4cdd48ce8803b95cf2e23040d90f66c8e3"
  },
  {
    "file": "audio/voice/logic_difference.mp3",
    "sha256": "cd77df1c3eecfc6cf4b3688f186eb873e8144528697404037d3346fe064b314b"
  },
  {
    "file": "audio/voice/logic_equals.mp3",
    "sha256": "2fe75b9db41402aba502ee825915c5134577537db2bb0a24aed238b01f7de60d"
  },
  {
    "file": "audio/voice/logic_input.mp3",
    "sha256": "08659b898d51aae480bd2d0fb0d3092001469fab81a06e0e409ffb850c65eefb"
  },
  {
    "file": "audio/voice/logic_machine_1.mp3",
    "sha256": "6ca4a1ad5158557bd13f24711dcfa7ae125a14a632017880d87c4185ffa821fb"
  },
  {
    "file": "audio/voice/logic_machine_2.mp3",
    "sha256": "1e5804773a7fb3f200143c1bee67586f61d1715f12043b5b61e78b66d8010864"
  },
  {
    "file": "audio/voice/logic_machine_3.mp3",
    "sha256": "ba3ca3a85417ebb40c0ec84165469f5a4716f518e0104c916694949287dff831"
  },
  {
    "file": "audio/voice/logic_machine_done.mp3",
    "sha256": "939d6314034d7a1712b41232fe1839bedba6d431e5ec1c4c7313eada243090ac"
  },
  {
    "file": "audio/voice/logic_machine_empty.mp3",
    "sha256": "9bc9342cc1d8ccf688a5c4a026b22489e29dd9c0560a20c2956bac1448f9ef78"
  },
  {
    "file": "audio/voice/logic_machine_fit.mp3",
    "sha256": "b7b4ed852cc00e0f443b2466c6fe95d5e138ce26eea77c8076cc34c823271e81"
  },
  {
    "file": "audio/voice/logic_machine_guess.mp3",
    "sha256": "10eedf69fc34308a39521e7f266f5bceb81e5e8294634193eedcf06913b0d37b"
  },
  {
    "file": "audio/voice/logic_machine_hint1.mp3",
    "sha256": "405a467075209420adb95800a631f0c35505f6b4bf9d17ff6e79f07b4e2b6760"
  },
  {
    "file": "audio/voice/logic_machine_hint2.mp3",
    "sha256": "5fa890b67da651f2573b7c4acbd682e76252af317cacb951e79569b70eafa384"
  },
  {
    "file": "audio/voice/logic_machine_hint3.mp3",
    "sha256": "91ac0c8fde433cdd07cc777b4b48137eb08a248248437e95d6a67819ca8884df"
  },
  {
    "file": "audio/voice/logic_machine_retry.mp3",
    "sha256": "c555d287a64342d476ffcc3c5f09e4d7e10939e90a98887e71a7e29582c362b8"
  },
  {
    "file": "audio/voice/logic_menu.mp3",
    "sha256": "61ef11d0a8f31149cd9f94bb675af4f4b8c6744d7345a61fc88155e4862bb25a"
  },
  {
    "file": "audio/voice/logic_minus.mp3",
    "sha256": "1968bc38a82ee91c9ccb82edc76f78bcd34a1b3fcde70c41f3c235dac5395250"
  },
  {
    "file": "audio/voice/logic_n_0.mp3",
    "sha256": "7bdea1cf71f45ffc3dadf38a3280ab16d3fefa41b0191289fa6334f749f521a6"
  },
  {
    "file": "audio/voice/logic_n_1.mp3",
    "sha256": "68f151b6da92ef4a889bc6228822981f9740ffe836d79eb3138fac73d14a5b39"
  },
  {
    "file": "audio/voice/logic_n_10.mp3",
    "sha256": "dcae2e0794c929604c4aac56493f6c8b717e5d15671b52e2b1624eb9cd7c6e2d"
  },
  {
    "file": "audio/voice/logic_n_11.mp3",
    "sha256": "3cf125669f251a89e0b85b93880c035ab2ba95a20279ec8a6223d5e22a911d49"
  },
  {
    "file": "audio/voice/logic_n_12.mp3",
    "sha256": "b66961cf8dde54f945007a943632f4cf33ca2d627910e688fdacb17a8ee04515"
  },
  {
    "file": "audio/voice/logic_n_13.mp3",
    "sha256": "f5608a1cb5fe4328c131d801d8b7c2b0427bd13ded8d13190d80bb072e92b7d8"
  },
  {
    "file": "audio/voice/logic_n_14.mp3",
    "sha256": "7cd2ab8ff108ba0c5132e4023c363cb182dcbcfaba07755447d7f9c2f2f01b23"
  },
  {
    "file": "audio/voice/logic_n_15.mp3",
    "sha256": "d2fefae8eaf8b392b9bf046db7bd61c7b57e24f80a850c9f0add518d13f4e016"
  },
  {
    "file": "audio/voice/logic_n_16.mp3",
    "sha256": "86ee458074fc6518952d8b0ff74ccc6e81b58b2808fe78b695c6fd73758d8de4"
  },
  {
    "file": "audio/voice/logic_n_17.mp3",
    "sha256": "8addb26f4bfe65ce03a8fcbaf209eefc9478a8945f2004e254e58dd65526a34d"
  },
  {
    "file": "audio/voice/logic_n_18.mp3",
    "sha256": "9f133d210ab5817774af15265dece27941d2fd673502d28e9a2916a6cfcf20ca"
  },
  {
    "file": "audio/voice/logic_n_19.mp3",
    "sha256": "c09227d03a98374ef42756ffc13aa041b48b0fa5c868f877d3f4f4d3532df315"
  },
  {
    "file": "audio/voice/logic_n_2.mp3",
    "sha256": "6508c7a003cd4621f9d6b2e5756f2e725e6d39bb1938aec88dce8b03f4d87cb7"
  },
  {
    "file": "audio/voice/logic_n_20.mp3",
    "sha256": "76fd2b6c688809bd345d65d8729217927d0c9f201d2ebb6d63ab1ec259f768d6"
  },
  {
    "file": "audio/voice/logic_n_3.mp3",
    "sha256": "28940f5cabd46029f15b48fb930dbe7b1a6e3683f42d244089830f2e6f7b48bf"
  },
  {
    "file": "audio/voice/logic_n_4.mp3",
    "sha256": "7cf4282f664516ac4e1ed127fce0f523dd9f0707869ab85be99e9c987c363217"
  },
  {
    "file": "audio/voice/logic_n_5.mp3",
    "sha256": "e3404711703b6f6a6b3a9ad0f30dcb8ca65d07f14f91ff097a64fcf9376f77ac"
  },
  {
    "file": "audio/voice/logic_n_6.mp3",
    "sha256": "d884408a24c79e9616a428358a6160b30b71009a493c27b9055d3b20f8b748d8"
  },
  {
    "file": "audio/voice/logic_n_7.mp3",
    "sha256": "922e0fa246d0e61f3ddeefcbd3ee324c74e417cef6b6f7daba7e2379b991f526"
  },
  {
    "file": "audio/voice/logic_n_8.mp3",
    "sha256": "d411dfebcc24aea1bc91cda7ff371e1fc703c1370bf92d30825488fdb0b01179"
  },
  {
    "file": "audio/voice/logic_n_9.mp3",
    "sha256": "3debb8851888bde73c19c7af728433951ba534767b24c1b84c51ce331c569f6c"
  },
  {
    "file": "audio/voice/logic_nut.mp3",
    "sha256": "5787cd8f25d37a6730289042108af059c583563c196c23457252c663051ef6ec"
  },
  {
    "file": "audio/voice/logic_op_add1.mp3",
    "sha256": "6340340c6c1163ac3dc74ef4897bd0d22dffcba4af70f548c2f7e2bae57b3ae6"
  },
  {
    "file": "audio/voice/logic_op_add2.mp3",
    "sha256": "196f2e60df705022d3f8a700181973132f910baeef6874ecc66951edaa0eab8e"
  },
  {
    "file": "audio/voice/logic_op_add3.mp3",
    "sha256": "b865c3aa220c6695ef8297ab8b5e33f53c24576719ef57de6921f7b6935660d0"
  },
  {
    "file": "audio/voice/logic_op_double.mp3",
    "sha256": "4869e74ec71a5ead7a97b1066b9714c7e93ded25813f8a970de66be0113109a6"
  },
  {
    "file": "audio/voice/logic_op_sub1.mp3",
    "sha256": "9efa757a5edc19e14fc446e40b3256cc9e3cb7463d30c975040cc89ef42a8350"
  },
  {
    "file": "audio/voice/logic_op_sub2.mp3",
    "sha256": "9b43c6c32ad8244c935761616356d8d0114dc1bc7a6830f7f2672a09e2465681"
  },
  {
    "file": "audio/voice/logic_op_sub3.mp3",
    "sha256": "5556e38acba4bab77ac97a8c8f93840b60941348cd1674f01021d369313eb3c4"
  },
  {
    "file": "audio/voice/logic_output.mp3",
    "sha256": "c5dfef031e72bc2475c7c9cbaf47a113e8b2e472c5f2be4a6f7c14397755ca73"
  },
  {
    "file": "audio/voice/logic_play_menu.mp3",
    "sha256": "a1239aeade293acc6d1c70f5b88b5a1bb355e41732bdb0a97cb19f4c719d8054"
  },
  {
    "file": "audio/voice/logic_plus.mp3",
    "sha256": "12cb8ce70bd0cba41ae2dcd2d39cf3974b712d7f77e960d72725fed0d6de6585"
  },
  {
    "file": "audio/voice/logic_predict.mp3",
    "sha256": "223b32df30911d7d3a6eb06679d9ca235798e7250b675296f76d8d5450cd6e1c"
  },
  {
    "file": "audio/voice/logic_route_1.mp3",
    "sha256": "ed39898284b59045303f6cc45cb7fb48d345d9d09ac86a93e9fc18a7c845ff93"
  },
  {
    "file": "audio/voice/logic_route_2.mp3",
    "sha256": "fc265576785fe37330e1bf564351a22f008cc6f1fb3978018e534b3f1f87ce08"
  },
  {
    "file": "audio/voice/logic_route_3.mp3",
    "sha256": "5a4787390041105ac27a5195645f37b3b9f0ab5d1bbc3fd21dd3f22d673c0de2"
  },
  {
    "file": "audio/voice/logic_route_adjacent.mp3",
    "sha256": "acc64d963d38bcb458075be2d793b3f9c6d31a1d3efcdacf26ad4adb24325461"
  },
  {
    "file": "audio/voice/logic_route_done.mp3",
    "sha256": "84c806da4b27c94f6bcdbd479e7c54e0dd55161f3bbd055c59be45d937b89e1e"
  },
  {
    "file": "audio/voice/logic_route_full.mp3",
    "sha256": "2d9bd644405e010b650f3538334821029f1163ef7c36324fc2250048a35d31f4"
  },
  {
    "file": "audio/voice/logic_route_hint1.mp3",
    "sha256": "dee3ff19c64040f11cf0517d949398db0d85cc887199ec3ae553bb9188ec9fe8"
  },
  {
    "file": "audio/voice/logic_route_hint2.mp3",
    "sha256": "2399b3c4928fb2057d7d4ccdc8fdeee19fab0af28062595f1b28d00334aa8fde"
  },
  {
    "file": "audio/voice/logic_route_hint3.mp3",
    "sha256": "4898fb843e704eb982ca344994e97168175de09b95ca47d83aad1f896f5103af"
  },
  {
    "file": "audio/voice/logic_route_home.mp3",
    "sha256": "1ab140ef1c6ec911fd60e76ee19bafaccc4de9cf0c9c4befdd20d9a506259c93"
  },
  {
    "file": "audio/voice/logic_route_missing.mp3",
    "sha256": "3479ca44601f87ebcb705e7cd91ee1d788736d62274a6e622432f0ae4ec0f7b7"
  },
  {
    "file": "audio/voice/logic_route_restart_hint.mp3",
    "sha256": "52fdea532bd31834dc504a7cfce77a8b74aa6522a2f95b30f33e48ee03b2bd46"
  },
  {
    "file": "audio/voice/logic_saved.mp3",
    "sha256": "4aefcde93609371e3ac4604e8a039104d253a0040af86fb9d4a4b2aaf251ee5d"
  },
  {
    "file": "audio/voice/logic_shop_1.mp3",
    "sha256": "2ba55e20d3153715a1d2adfa215566cb16d1f71e1f68eae4f0c3d4ada0c8b589"
  },
  {
    "file": "audio/voice/logic_shop_2.mp3",
    "sha256": "5b6093e9f7369321be6b348415e1e6fd3bb70044c9db8f8508f9fd042cb7c228"
  },
  {
    "file": "audio/voice/logic_shop_3.mp3",
    "sha256": "f3351188658e8d4a05bf74905b481eacec4d3e6e80ba67cb2470f8f86f80758e"
  },
  {
    "file": "audio/voice/logic_shop_done.mp3",
    "sha256": "e1a76a57f93a5c73896892e6111c8cc665adaa0fa6d7a788ccdf55b781d8f5b9"
  },
  {
    "file": "audio/voice/logic_shop_hint1.mp3",
    "sha256": "7246a38c0459284da64a7b80325a3b9f14ab5f7174e5b01090f4012a774d8cb6"
  },
  {
    "file": "audio/voice/logic_shop_hint2.mp3",
    "sha256": "dc99c0f048305c8e2c9721f8153b5011fbbf8dcb4e8b4700c0eb9a2769b969f9"
  },
  {
    "file": "audio/voice/logic_shop_hint3.mp3",
    "sha256": "ec84f3c56d3f3c4578e2bb1584ae3b3d42847a0311f431be899b538e82c001ed"
  },
  {
    "file": "audio/voice/logic_shop_less.mp3",
    "sha256": "43bcb586b4ac7079a78e2344201d8e2ff270555879a6ae8553825249c39571b0"
  },
  {
    "file": "audio/voice/logic_shop_more.mp3",
    "sha256": "8d4b36521781247cef2877a7ecd2502fdca8373993b3c0348a238b5231e19503"
  },
  {
    "file": "audio/voice/logic_total.mp3",
    "sha256": "7ee48b9d3d2977b74f2005a003d54379e0385f364bcd958e3503c25371a3c94f"
  },
  {
    "file": "audio/voice/mese_album.mp3",
    "sha256": "daf0b9db01198896c87884a94a8e2dff28ccaa93e29db6e6f84b930dbffdf2aa"
  },
  {
    "file": "audio/voice/mese_collect_1.mp3",
    "sha256": "1d7037b3ec76bdf9f02cd0529ee107bc4922a9f7ee0e0344c399cd21ec72beb8"
  },
  {
    "file": "audio/voice/mese_collect_10.mp3",
    "sha256": "bb286f3e05002f7995cc848058317cf803f2ddfb37d0d4743527f5c68ceebf16"
  },
  {
    "file": "audio/voice/mese_collect_2.mp3",
    "sha256": "a4b3b87d49f9bb4ef9c65dcddf22583357ce67320d401bb1dc75458e70f86cb2"
  },
  {
    "file": "audio/voice/mese_collect_3.mp3",
    "sha256": "9e62354a0d4694753678ff42dce961153aea355b6a5990254071b66235a11b8b"
  },
  {
    "file": "audio/voice/mese_collect_4.mp3",
    "sha256": "5ba110364a7c29b51a15080fc72d62aec4cfd7903d0e633c5b4266cc0013378f"
  },
  {
    "file": "audio/voice/mese_collect_5.mp3",
    "sha256": "c8c01b7982c1c8a51fa98d4be43eb89c90cd59ba497e6932e4a76bc3b6769e2c"
  },
  {
    "file": "audio/voice/mese_collect_6.mp3",
    "sha256": "207283e02ff503282ada85c33fc12ae2791b4c06745a250205f28258f7d81a04"
  },
  {
    "file": "audio/voice/mese_collect_7.mp3",
    "sha256": "76132f040c69092653ba9e502f841f379e7072b188134b5447d8fc7299c43520"
  },
  {
    "file": "audio/voice/mese_collect_8.mp3",
    "sha256": "edfefa69d9f7083cb09d1e8dbc5ced6617077e301b831b5b625e94201d4fbf91"
  },
  {
    "file": "audio/voice/mese_collect_9.mp3",
    "sha256": "457d07836100f900d8ddb535ff65d79e40d1db672d152a9943105e49cfc62249"
  },
  {
    "file": "audio/voice/mese_collected_1.mp3",
    "sha256": "b29b74f052f73b3388af584824ef5b5bf131b28892f7b52dfabfc89b72b54aec"
  },
  {
    "file": "audio/voice/mese_collected_10.mp3",
    "sha256": "c8654406018b9f8454f2e5f6ba7094b67f2795cca32006efb64da156141d7a8b"
  },
  {
    "file": "audio/voice/mese_collected_2.mp3",
    "sha256": "167b8e82ed00140804eacfa52776ec32f694aceb5e25f294541f3e85485bf534"
  },
  {
    "file": "audio/voice/mese_collected_3.mp3",
    "sha256": "bc898b9ed3c24e16c68317975ef1dd6014d8b26053e27d46d683bcf94d711761"
  },
  {
    "file": "audio/voice/mese_collected_4.mp3",
    "sha256": "ce129d34d7f25fdd3c64c35160694bc6e9cc3bbdce08a377712f2ec7da737d4b"
  },
  {
    "file": "audio/voice/mese_collected_5.mp3",
    "sha256": "65cdf27704ee51e6359c64061fb6583b90e0065912591fab1593c0e7d92d97fc"
  },
  {
    "file": "audio/voice/mese_collected_6.mp3",
    "sha256": "5082f498b1c2295b741a7bba38fbe9597361cc0241b256323e519d2cede7e8db"
  },
  {
    "file": "audio/voice/mese_collected_7.mp3",
    "sha256": "c2e26ac8b49c24c9344230c4f61c8444b19b5ec59f67f37a1805fe263306483a"
  },
  {
    "file": "audio/voice/mese_collected_8.mp3",
    "sha256": "053f8a5793ffab2e19074c1e3b7caf28148f3c3beafa086719ba92dffd5ba576"
  },
  {
    "file": "audio/voice/mese_collected_9.mp3",
    "sha256": "ebed4d3dd44de4fbba24dbab3344091ecd57acbc562e390816fe435f07e32c7f"
  },
  {
    "file": "audio/voice/mese_count_help.mp3",
    "sha256": "4fe4f8b8656635742c3519f06c67f1f89e797451dbb008847c20cd5d804f320f"
  },
  {
    "file": "audio/voice/mese_dressed.mp3",
    "sha256": "fb6b95f93e521ce83883d3b5b6773c1ff86970a90fa6792bd7c5f180fb08adff"
  },
  {
    "file": "audio/voice/mese_empty_album.mp3",
    "sha256": "eb3f0c8820f89180a408510488c2f66a51c57e059a78382165009c6831813762"
  },
  {
    "file": "audio/voice/mese_finish.mp3",
    "sha256": "809203708943e61e4b8f5ee795394089c76b06eddebb1f49ca668b92384dc215"
  },
  {
    "file": "audio/voice/mese_free_finish.mp3",
    "sha256": "b42d9b326465bd36f46fb985c1565010ccef3e171028da2ba7eadd85ab227216"
  },
  {
    "file": "audio/voice/mese_less.mp3",
    "sha256": "f62a6af2ee542e9a60f48be05c2084b5945bc3bf75423504e2fbdfe8e9bc619f"
  },
  {
    "file": "audio/voice/mese_map.mp3",
    "sha256": "5247d439455db6618bd4106e421b59014d9647ada95e437511fe179cbe567cef"
  },
  {
    "file": "audio/voice/mese_more.mp3",
    "sha256": "a2609d47a0f75e221df0e1edc2bc7ba4b478bbf8e011068dbbf718b226f5adb0"
  },
  {
    "file": "audio/voice/mese_plate_help.mp3",
    "sha256": "750e8786e940205da67babffc1a2e98158ebc205bd15ebd3701a2a85d73040a9"
  },
  {
    "file": "audio/voice/mese_plate_more.mp3",
    "sha256": "61f9b079c8d22b6575db54ed7d4e5dbe12181455608fb5dbd51c4c14693b723d"
  },
  {
    "file": "audio/voice/mese_play_menu.mp3",
    "sha256": "98a76fb2194c7424c2ffb90ac18297decfcfd5896a92569c09db9117d8e4bb44"
  },
  {
    "file": "audio/voice/mese_serve.mp3",
    "sha256": "f6e9c1963cdd2a3c33776bfa99da1951a968faf1fd2bcbb6670bbbef2d55c645"
  },
  {
    "file": "audio/voice/mese_served.mp3",
    "sha256": "e9bc0a49b14ccf018d8406965f856f3ff955e6e6e703678c07c2e9549282cd88"
  },
  {
    "file": "audio/voice/mese_start.mp3",
    "sha256": "ffa528ce3e62726f3ec888d94c8193c74f614bed352acaf3b683b9a2ab9c249e"
  },
  {
    "file": "audio/voice/number_1.mp3",
    "sha256": "7180d4e7c51951ebf9558a53c4eda733db7c282b7170e313f4010ee76864328f"
  },
  {
    "file": "audio/voice/number_10.mp3",
    "sha256": "de5e96759df6213eb921eaae186ea6a771a34e0c0b7d8d59e952805b03ea8783"
  },
  {
    "file": "audio/voice/number_2.mp3",
    "sha256": "d0893c006224a0ad574583201debfa4b33d2f53bcccfdb6566377c2500790c19"
  },
  {
    "file": "audio/voice/number_3.mp3",
    "sha256": "a77f36a254b90cc2d65886b417fd45b0803980d989a1430481e37a25fb58b918"
  },
  {
    "file": "audio/voice/number_4.mp3",
    "sha256": "7cf4282f664516ac4e1ed127fce0f523dd9f0707869ab85be99e9c987c363217"
  },
  {
    "file": "audio/voice/number_5.mp3",
    "sha256": "e7ce6fa6f0912ed569cd8bafe84d429120289e8875b1c6b9c6f7f66e3b63df78"
  },
  {
    "file": "audio/voice/number_6.mp3",
    "sha256": "bff7361eea228a3990bba6b49e210552134776a0e170e29e915fa824049a2db6"
  },
  {
    "file": "audio/voice/number_7.mp3",
    "sha256": "34c6c7bcf7391904e16e48d3a5357b12b7945f941910ef33dac542c26fc05452"
  },
  {
    "file": "audio/voice/number_8.mp3",
    "sha256": "0db0278fa8a69114d7b96ffa557540761cc1ae0919e9b94b70e5210b1f9fa26e"
  },
  {
    "file": "audio/voice/number_9.mp3",
    "sha256": "147e6a1f6c3764a11ccb4a56d17da3a9aa1c994796f948f0917ef6371bd5a70f"
  },
  {
    "file": "audio/voice/phrase_anya_gyere.mp3",
    "sha256": "974d5700c95b7f473d8a93d0de985dc67630de38875d6affc009c95c2579c4b7"
  },
  {
    "file": "audio/voice/phrase_apa_auto.mp3",
    "sha256": "68be0dc3d5bf694b3e4d8353ce537ab8894943a9f2113ba9d79bed10aad53e10"
  },
  {
    "file": "audio/voice/phrase_kerek_vizet.mp3",
    "sha256": "59209fd4f43ed7c978f3e321a3b6ca0a50aabf591c1a92f47772cf40c1877d30"
  },
  {
    "file": "audio/voice/phrase_meg_alma.mp3",
    "sha256": "120b915670caef02a8dd75f06c34f41ea6370ac2e8291d7026a7a2dd6260a9a7"
  },
  {
    "file": "audio/voice/phrase_nagy_labda.mp3",
    "sha256": "b8999c8969153bb673571893a7c85f5f35f77c450694bbb4f4c5038c9cf4d121"
  },
  {
    "file": "audio/voice/phrase_nem_kerem.mp3",
    "sha256": "01aebb434c761cc0fc830cb7bf619a6cc0ff9e424da6c01199e9a599779a09ef"
  },
  {
    "file": "audio/voice/quantity_alma_1.mp3",
    "sha256": "cf79ed5d3ba5df076e2daf1ab22506329066916686ba4ed4ceff91f948b49d2a"
  },
  {
    "file": "audio/voice/quantity_alma_10.mp3",
    "sha256": "63ed781efc71c948ac639b42f957b6eb23dfe9d5bcc5aa4739345aa84edbddf1"
  },
  {
    "file": "audio/voice/quantity_alma_2.mp3",
    "sha256": "c2fb438d5f8b39a69af2ac07c22b8fec9fe02b3f53953fb31ae425c0d98854d5"
  },
  {
    "file": "audio/voice/quantity_alma_3.mp3",
    "sha256": "9e5fac44db321b2abfd1bc803cc6f6ac8e2b6b5018647e02cea7435158f0dc76"
  },
  {
    "file": "audio/voice/quantity_alma_4.mp3",
    "sha256": "e7527be354d8431a36f6cc76e49d196563e5da0c23b092750269a5350c2cb911"
  },
  {
    "file": "audio/voice/quantity_alma_5.mp3",
    "sha256": "fee06605c64c42ddd239a6ec46b345479303b645e87b708e5b225164bcd58db9"
  },
  {
    "file": "audio/voice/quantity_alma_6.mp3",
    "sha256": "7ea456d29da4dffff8cca06e31918f51e1153431d6582a9874f15faa8e9d16e7"
  },
  {
    "file": "audio/voice/quantity_alma_7.mp3",
    "sha256": "ca992498ad4374848a4744f4f7c5aebe2a435292b8c6648c3e262ec140ebaf58"
  },
  {
    "file": "audio/voice/quantity_alma_8.mp3",
    "sha256": "93ead3590fa73f2443e306a1fc6a231a35beae394ddda16fe8a56f4457afc798"
  },
  {
    "file": "audio/voice/quantity_alma_9.mp3",
    "sha256": "92cd6122c5736d94e9687873113e403384b12dca66aab00f9c44cc70f2c866d2"
  },
  {
    "file": "audio/voice/quantity_auto_1.mp3",
    "sha256": "5bb84fdd3f88bda34ea58b16c6348b3629c34bfe7974096c47ba68203a91f2ec"
  },
  {
    "file": "audio/voice/quantity_auto_10.mp3",
    "sha256": "ce9ca653d9fae4e81a8047950836cc58fe7f8349746197786c8552da03e6729e"
  },
  {
    "file": "audio/voice/quantity_auto_2.mp3",
    "sha256": "1ff738f0c74b5887055db77abef4de1949f162c5bdb982aae2211416b40c4e34"
  },
  {
    "file": "audio/voice/quantity_auto_3.mp3",
    "sha256": "30eb14f3347b6fd0b996dea62380741a6d7530d0cfe2b8049ce3ef6c3e4f9f84"
  },
  {
    "file": "audio/voice/quantity_auto_4.mp3",
    "sha256": "09703210546784d3360dfa2ee0de8f68804552701cd0836f65a37643321e56cf"
  },
  {
    "file": "audio/voice/quantity_auto_5.mp3",
    "sha256": "ac8789b2ebf09ded34db3080c3e81bd0b174b2507dfc14084dbafe15a51e308c"
  },
  {
    "file": "audio/voice/quantity_auto_6.mp3",
    "sha256": "3720aeef09673a67f82f5aa428e6218272563a60b0977de2b668ee75791c4a75"
  },
  {
    "file": "audio/voice/quantity_auto_7.mp3",
    "sha256": "8d04328388f7e9c5b83b1a02ba89695c791607af6ddda3dbcc795d4961025c3e"
  },
  {
    "file": "audio/voice/quantity_auto_8.mp3",
    "sha256": "050296d08648f82b7bb497eb59b5c29aa799a8d8ddda3548627d8b5f0393c03a"
  },
  {
    "file": "audio/voice/quantity_auto_9.mp3",
    "sha256": "f11dee3547d0456bb36278f1a48cb3f532bad22af26088737cb3c5c5284a484f"
  },
  {
    "file": "audio/voice/quantity_labda_1.mp3",
    "sha256": "df52bd59f53ddfff91354095d96cf1497929ab5926f5e260f6cec615bfea0c00"
  },
  {
    "file": "audio/voice/quantity_labda_10.mp3",
    "sha256": "467223d70275ca2b295798d66c264a2fd3ed86c1c9a6548aa3c44d7b67b46a58"
  },
  {
    "file": "audio/voice/quantity_labda_2.mp3",
    "sha256": "012901188e460b6d25fc43428e26410267e56ced99c329e58bcde7a099673dba"
  },
  {
    "file": "audio/voice/quantity_labda_3.mp3",
    "sha256": "f9697d557698fa06ce26812e5d4cdeebbf6d283f55de456f15463c5df99da738"
  },
  {
    "file": "audio/voice/quantity_labda_4.mp3",
    "sha256": "85f9a200ac8653b5048167ec6e2ba9b3f6c0334a7e213d3e887d13c9b3f1c3ed"
  },
  {
    "file": "audio/voice/quantity_labda_5.mp3",
    "sha256": "7b5ef283b2cb5f71fc8ea3e25ce46d7aa94b0a14f980461baef54ca2096ee520"
  },
  {
    "file": "audio/voice/quantity_labda_6.mp3",
    "sha256": "4cdd18092e303a1395b252fa4967edf3db225e7ad0f5f8efb8e60b15899e0f5b"
  },
  {
    "file": "audio/voice/quantity_labda_7.mp3",
    "sha256": "802e2268555be8fce8f5ed2ce28252056dba7722f775e7006f1026e0a159750a"
  },
  {
    "file": "audio/voice/quantity_labda_8.mp3",
    "sha256": "239478e2a4f42f5813bba25d03b717b786fb3eb190ad9a081d2aba62af1171ef"
  },
  {
    "file": "audio/voice/quantity_labda_9.mp3",
    "sha256": "7873c8618b122392097f3a77b315c7d4cb70624a846e9e52c8e62a6d70ae8d8a"
  },
  {
    "file": "audio/voice/question_alma_1.mp3",
    "sha256": "ac7a14716aae8dc7990e09a0304cea5c2902e390ac3b1da12dcafbf17da5ef78"
  },
  {
    "file": "audio/voice/question_alma_10.mp3",
    "sha256": "55d2308febe4f4a01a080118cdee33a053d129aaf1bc42b26f685f77f0ed5678"
  },
  {
    "file": "audio/voice/question_alma_2.mp3",
    "sha256": "64cdc8676e4a8ece513c48ec08e683b788ad760b09e3911453f935086b9399f6"
  },
  {
    "file": "audio/voice/question_alma_3.mp3",
    "sha256": "76283f8411e414fe09779d364c8682438ba31514b07f709f59309f53c72c8620"
  },
  {
    "file": "audio/voice/question_alma_4.mp3",
    "sha256": "aafd83d535a004912b9f4de30562d47b2a02a713193a9c5ce81ae313f86a8172"
  },
  {
    "file": "audio/voice/question_alma_5.mp3",
    "sha256": "fca63738f30666cba11688de45903d5886eb6c014a79d6deb902e6fa03446e5f"
  },
  {
    "file": "audio/voice/question_alma_6.mp3",
    "sha256": "06ef48807a605ed25a0f74e803db6dd35c2e688d95fbadf251bbc0356831b69a"
  },
  {
    "file": "audio/voice/question_alma_7.mp3",
    "sha256": "d7d4323abda72da1e21495bbd2b4256e86abfe53fad0c2c268d1a880913f806b"
  },
  {
    "file": "audio/voice/question_alma_8.mp3",
    "sha256": "98266f05d8e9be62ef60defca77ee26c2e7252197bd2b8f6ee7c39289128c2b9"
  },
  {
    "file": "audio/voice/question_alma_9.mp3",
    "sha256": "4ba0a4c3afc1deca7e6206a46225e79557d38eff1691d6ea7a49ad2b412c65b5"
  },
  {
    "file": "audio/voice/question_auto_1.mp3",
    "sha256": "f4195a647515d6ff0de126b6e1b81de3e581a593e8c1b2dffedd92cfc788331c"
  },
  {
    "file": "audio/voice/question_auto_10.mp3",
    "sha256": "a776f015c67cc0c16edf8a1e8bf8541d0864b4c0b9eabf64831b353d105bc0b9"
  },
  {
    "file": "audio/voice/question_auto_2.mp3",
    "sha256": "13c4b29c16856576cf21a36c77b8b1b348288258dbe8e7c37fd43124527a3bc8"
  },
  {
    "file": "audio/voice/question_auto_3.mp3",
    "sha256": "de99d43221f48ed295ddb098245bbf9280a25946ed6d06391d29fbe4fe69d98f"
  },
  {
    "file": "audio/voice/question_auto_4.mp3",
    "sha256": "c5965d1b1a18b6c9269670748594032e3cbab28dd2f7fd8ecd0f3ce709979661"
  },
  {
    "file": "audio/voice/question_auto_5.mp3",
    "sha256": "5e4f083aa104fc82ef429eb59645f6181c18e7d4cab496f411e8746531a5475a"
  },
  {
    "file": "audio/voice/question_auto_6.mp3",
    "sha256": "ca2b067421779bbe61125f5bb32dd4d1ed8ab3504d145738e56c7aba2dbc86f1"
  },
  {
    "file": "audio/voice/question_auto_7.mp3",
    "sha256": "5bb04cfe5faff95d79dd131b4e61ea437973e9fe3a54561293d1e757c8bf53ee"
  },
  {
    "file": "audio/voice/question_auto_8.mp3",
    "sha256": "69afcecf037a1e38503bac1b4fea7b8e00ff860f115761bbb6989b1ff9d8e25b"
  },
  {
    "file": "audio/voice/question_auto_9.mp3",
    "sha256": "0d2d0c9a942678abb5f3a0ba0a7b2216889c32a80e268ee92fe115f6c0b44946"
  },
  {
    "file": "audio/voice/question_labda_1.mp3",
    "sha256": "4e3567277b032ebbccf21deb456ab7f5005270d0ae49fe4788b04b91ad3e1697"
  },
  {
    "file": "audio/voice/question_labda_10.mp3",
    "sha256": "da3b215f2928c35bf9ba94da5739bb9a4dcb60586ce6a1a893c1ceb955c36ace"
  },
  {
    "file": "audio/voice/question_labda_2.mp3",
    "sha256": "7b9da0062ac29355f7f0694a202d28f0b08c6dcd355b1f0d2d448352bd4146b5"
  },
  {
    "file": "audio/voice/question_labda_3.mp3",
    "sha256": "c24915e4221f68498a9409f3f4267ca8fc31a73f2f293dcb1cd2a3559e5bca63"
  },
  {
    "file": "audio/voice/question_labda_4.mp3",
    "sha256": "639760075114001b48da755c0025345ff86a873606b5b1535ef59440f978feb0"
  },
  {
    "file": "audio/voice/question_labda_5.mp3",
    "sha256": "206783613852b86f959c304e01ab1b5503dc070128106fa72189b81d6f18a4f7"
  },
  {
    "file": "audio/voice/question_labda_6.mp3",
    "sha256": "30005b8cc1429e38815921272472928af49684bde28fdbd3c893c43ce8dfb660"
  },
  {
    "file": "audio/voice/question_labda_7.mp3",
    "sha256": "946a635f9749885d3f005bcd1aa6d516946188910ae29b24dcdb99187e62b7b9"
  },
  {
    "file": "audio/voice/question_labda_8.mp3",
    "sha256": "5071718daa191a9add13dfc021578700059c1309e7e796bd6bbae4204a92f524"
  },
  {
    "file": "audio/voice/question_labda_9.mp3",
    "sha256": "2b0ffc808ee0bc6bbdb6e0dad4a7e9061639f9b677465bd3e98f835f2fe163e4"
  },
  {
    "file": "audio/voice/teddy_alma.mp3",
    "sha256": "c5cf84dc53f8b32ea51bd23fa754129dedae25eecbec92ffa13f9f0c3e5ce987"
  },
  {
    "file": "audio/voice/teddy_kenyer.mp3",
    "sha256": "d3f63a9ff59280464d6e46a21d019574015a7f70686a5fbce0d2ff709c4032ed"
  },
  {
    "file": "audio/voice/teddy_kifli.mp3",
    "sha256": "73cf0730024229256f6d04c44c4725d54f1cb99765c7f43b0e849bd752b1ee62"
  },
  {
    "file": "audio/voice/teddy_tej.mp3",
    "sha256": "e98eeafb6507c29842b6a323e73af0de208930aca09dcbccaa6cb6332fe47272"
  },
  {
    "file": "audio/voice/teddy_viz.mp3",
    "sha256": "4fb2c5c177961878dc4d2f23321010bc9d4d897ad3b74c53892fe68cb423076b"
  },
  {
    "file": "audio/voice/word_alma.mp3",
    "sha256": "f49ffcebf5d3165b6ee0f7a5c2a1ccd801c6e9e6fd24f0c3d847c5f4029207f1"
  },
  {
    "file": "audio/voice/word_anya.mp3",
    "sha256": "2a3a11689cbefd77150fc5fbae5c9f45467f008440c2af66d72b3595a6c1a559"
  },
  {
    "file": "audio/voice/word_apa.mp3",
    "sha256": "af90b4ccd631af1d04b4713e0d86d370536164ec38bc9beb63a20b8c6c1ac545"
  },
  {
    "file": "audio/voice/word_auto.mp3",
    "sha256": "e1a65928f1957c3d5712af75066ab85506085c56806fdfe892000a0e1a13a96d"
  },
  {
    "file": "audio/voice/word_baba.mp3",
    "sha256": "76f9cce278137a6edf509a78119d20d7612e02bd560692195168036299862b02"
  },
  {
    "file": "audio/voice/word_busz.mp3",
    "sha256": "68d97e060287ded18846f47bf71198e1e2651e906e4ca80e7eb5078799c70879"
  },
  {
    "file": "audio/voice/word_cica.mp3",
    "sha256": "c7f970b02e49dbd4eba83679fe7f103f93cbf098bb0d4e265692d2f6dd7dce31"
  },
  {
    "file": "audio/voice/word_cipo.mp3",
    "sha256": "9669003f4b845bd173f12889c42fdae363e65cd9eac6995b9d6d595a01d7345b"
  },
  {
    "file": "audio/voice/word_fa.mp3",
    "sha256": "b72cf392c96efaca8030c69274d29c2ca44e995b9886f239844e45a9c4eb9d30"
  },
  {
    "file": "audio/voice/word_furdokad.mp3",
    "sha256": "2616832873382e974dfc570a0b632ee6b001f9984b918b7528976b4a02193029"
  },
  {
    "file": "audio/voice/word_hold.mp3",
    "sha256": "83adcc61cacd33d4ab148863213009a392522451495d38178b063ab367cf6030"
  },
  {
    "file": "audio/voice/word_kanal.mp3",
    "sha256": "3703b4523ef353a96970787dc4ceddd96816fb804d9e7fae5039bcfe742da157"
  },
  {
    "file": "audio/voice/word_kenyer.mp3",
    "sha256": "8b002a5ab9b5ddc337bfef1af334620df05f3339ca850a4a2aaefe39d47793cc"
  },
  {
    "file": "audio/voice/word_kifli.mp3",
    "sha256": "da8b5c720f35321a8558636178c4fd5778c327b14ac87409e79cdf1cbba87c5d"
  },
  {
    "file": "audio/voice/word_kutya.mp3",
    "sha256": "02e22f112c0073a9e36ee51d73e039493d4ebd6dc38a1b9191e3144c78f54a07"
  },
  {
    "file": "audio/voice/word_labda.mp3",
    "sha256": "77f571b3cd8739c1f84a849c15ab92b24a02e277c3e75bd9777de2a8d9f618b3"
  },
  {
    "file": "audio/voice/word_maci.mp3",
    "sha256": "663bf53cf1a24b573051c6da29739102b866cce1ca0b490864be217f130fc9dd"
  },
  {
    "file": "audio/voice/word_nap.mp3",
    "sha256": "ac239b36dfa2446b3a2d0b83f0d18ab4d81efd5f60646a1d4bdbc2e0ac1e22b9"
  },
  {
    "file": "audio/voice/word_sapka.mp3",
    "sha256": "2d07c665bdec3ac43e3ebfb23683c9d13eae225193b352cea7a2db81aed4eacf"
  },
  {
    "file": "audio/voice/word_szia.mp3",
    "sha256": "1a4333430b9f8a6a61be93373059b76f8c47882dbc05842d365dd623d24a38c5"
  },
  {
    "file": "audio/voice/word_tej.mp3",
    "sha256": "3fe70d229b1c2cb848aa5043b1f8dd69c9f01bfa9d4c84fcc4234f890c53bbff"
  },
  {
    "file": "audio/voice/word_virag.mp3",
    "sha256": "ab20bfc8e5f51229ba29da691265e5fbff4baf44f9791349355c51d4b191c90c"
  },
  {
    "file": "audio/voice/word_viz.mp3",
    "sha256": "d6101b53a6984e4a5a53d43004b0cde1ddc80c3b790efa813f8de0ecfbec290f"
  },
  {
    "file": "audio/voice/word_vonat.mp3",
    "sha256": "531cd2193f67af3854fc7a68b64d88a73bbd5f2b8f5ddb4302abd351c6cafcf7"
  },
  {
    "file": "audio/vonat.mp3",
    "sha256": "db9b4a991e119e3d78ac71ac1896cf50889f56fdee979b9bef2355523775ff0e"
  },
  {
    "file": "child-ui.css",
    "sha256": "253131abc64b6e75b7c164e08290f53489f16da05d38f79a6e3c3ae98546d939"
  },
  {
    "file": "cloud-save-queue.js",
    "sha256": "172e1ce2b92a1189277f9ae41fd978b7c69c94925223d6d4d8c668fe1f9aa6be"
  },
  {
    "file": "dress-art.js",
    "sha256": "938f1dfa3433f21173fe3a27d48f94b4f5f9bbe9f539e9615f3871496923a5d3"
  },
  {
    "file": "dress-data.js",
    "sha256": "7638a1b16d2136e109fc67f080f7435de10467d40f20e47c01ba33483f0ed891"
  },
  {
    "file": "dress-game.css",
    "sha256": "1f7c392d730cbdb51e3c98c290c5b0ba1192f7dca2346c75926c5240a0a3e1b3"
  },
  {
    "file": "dress-game.js",
    "sha256": "065b7e06b94323f8cdc404e0b12d03b4962e7cee2c8109cc557f49357a230f39"
  },
  {
    "file": "game-data.js",
    "sha256": "7255eb4199054d8f81365e7e0895a1e9bf3d089a091ad957c834ce5fd2d63e94"
  },
  {
    "file": "icons/apple-touch-icon.png",
    "sha256": "fe5dc93cf0ee10d10b335c3f704c22cf9a17c27e3bef55c639e92e8a974a4a0a"
  },
  {
    "file": "icons/icon-192.png",
    "sha256": "8ec214a50f05143968ce237c0d7f4a8d1d70a7c4820bf5e080c6ae2619864012"
  },
  {
    "file": "icons/icon-512.png",
    "sha256": "c12d47b6030cc1ae14508598fe7df33c6b62de281e792e253d4bc3bf48bf5180"
  },
  {
    "file": "icons/icon.svg",
    "sha256": "af04b9c18c95b6b98b81de52ef7bc96d06871bc8d108fcd91cc63aeb484fa9fc"
  },
  {
    "file": "index.html",
    "sha256": "51ee5bd504427cb6296c65b626573e875620ae2353e17d5f276428ae2b5ea371"
  },
  {
    "file": "listening-game.js",
    "sha256": "e2ee7cc8047634f5cc7404d1864e208262f953d11446375f5f7d3a1e9f27a683"
  },
  {
    "file": "logic-data.js",
    "sha256": "6e898d8dc05b986859ce1ece67d0ae6341cdccf9915d53605dafcdd64a49cb6e"
  },
  {
    "file": "logic-game.js",
    "sha256": "4662dd4ecbedb25ca678bbe5aa7fcabdea0b840c8976b889e95c94287c5124d3"
  },
  {
    "file": "logic-voice.js",
    "sha256": "c4ae9772bbefec8e0148600a57ce4696c691a9802a2ed65cbcba9e505b99c833"
  },
  {
    "file": "logic.css",
    "sha256": "296ea989911bdd99a3036ee351a15c0d455282dcf161c23009199d0e0d3d84f5"
  },
  {
    "file": "meseliget-data.js",
    "sha256": "a5ff0c4d90f690aafe73d59c1b755b4f5e09595b7bf5ee2763836ac073d6a008"
  },
  {
    "file": "meseliget-game.js",
    "sha256": "a5cd17f90202978db05253350d4e79c74b907599c9db7ae399a8fd483dd7ddd1"
  },
  {
    "file": "meseliget.css",
    "sha256": "1ee58c1192903b33c49b2f9e682836f8d20c8c91fcb54bf85b8b7fdbfbf882c9"
  },
  {
    "file": "offline-client.js",
    "sha256": "57fa7904eed51f550f1e081bee402f738b1ecb3c030b9cb5202b247d13bc8c8d"
  },
  {
    "file": "progress-data.js",
    "sha256": "0aa6926e9ecbec76d29c386a35d49d262520ee72bec35908c01257a129fab9bf"
  },
  {
    "file": "progress-profiles.js",
    "sha256": "4e67d8a831e08ce7475f4ac8599d1248a8860208014535f0a9be799ad32b344a"
  },
  {
    "file": "progress-tools.js",
    "sha256": "3a06195ef250d955c0cc2107066c830d32c7cc64fd7527ee686d6b2dbfc672bd"
  },
  {
    "file": "speech-matching.js",
    "sha256": "f22fe8259c20640b2f5d2253bcb7ebb0f7d16100e537a0e146c21e5287a6aa4e"
  },
  {
    "file": "speech-recognition.js",
    "sha256": "22d5e890c6e13254ed8da611e89af3e378c0c6271c5fb829f9f2de67b0c2461f"
  },
  {
    "file": "styles.css",
    "sha256": "b03e704a066fdbdcf0d5bbcca94257ab14a8560326b5a1bdca08b3ec3c40afc8"
  },
  {
    "file": "supabase-config.js",
    "sha256": "121a1a2198f6373fde459f21ee70782f18ae6e256c0cdeca46959fdff221b9c3"
  },
  {
    "file": "teddy-game.css",
    "sha256": "3b537ef2d7426d0ba034a480baa3774bb1680d99369ed9c2bcc11a4babb7d5f0"
  },
  {
    "file": "teddy-game.js",
    "sha256": "9897a2ead16ab0ad2b929d061b0afbd703127491801c3c36b94c5438711f6984"
  },
  {
    "file": "voice-library.js",
    "sha256": "25e135a16dbe2b1e848518a59ac5d232f5613143c76c03975258816717fda1c2"
  }
];

/* CACHE_VERSION and ASSETS are supplied by scripts/build-offline.mjs. */
const SCOPE = new URL(self.registration.scope);
const CACHE_PREFIX = `beszedtanulas:${SCOPE.href}:`;
const CACHE_NAME = CACHE_PREFIX + CACHE_VERSION;
const INDEX_URL = new URL("index.html", SCOPE).href;
const ASSET_URLS = new Set(ASSETS.map(asset => new URL(asset.file, SCOPE).href));

async function tellClients(message) {
  const clients = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
  for (const client of clients) {
    if (client.url.startsWith(SCOPE.href)) client.postMessage({ ...message, version: CACHE_VERSION });
  }
}

async function installOffline(repair = false) {
  const cache = await caches.open(CACHE_NAME);
  let completed = 0;
  let next = 0;
  let failure;
  await tellClients({ type: "OFFLINE_PROGRESS", completed, total: ASSETS.length });
  const download = async () => {
    while (next < ASSETS.length && !failure) {
      const asset = ASSETS[next++];
      const abort = new AbortController();
      const timer = setTimeout(() => abort.abort(), 15000);
      try {
        const url = new URL(asset.file, SCOPE).href;
        if (repair && await cache.match(url)) {
          completed += 1;
          await tellClients({ type: "OFFLINE_PROGRESS", completed, total: ASSETS.length });
          continue;
        }
        const response = await fetch(new Request(url, { cache: "reload", credentials: "same-origin", signal: abort.signal }));
        if (response.status !== 200) throw new Error(`Download failed: ${asset.file}`);
        const data = await response.clone().arrayBuffer();
        const digest = await crypto.subtle.digest("SHA-256", data);
        const hash = Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, "0")).join("");
        if (hash !== asset.sha256) throw new Error(`File changed: ${asset.file}`);
        await cache.put(url, response);
        completed += 1;
        await tellClients({ type: "OFFLINE_PROGRESS", completed, total: ASSETS.length });
      } catch (error) {
        failure = error;
      } finally {
        clearTimeout(timer);
      }
    }
  };
  // Let in-flight writes finish before removing an incomplete new cache.
  await Promise.all(Array.from({ length: 6 }, download));
  if (failure) {
    if (!repair) await caches.delete(CACHE_NAME);
    await tellClients({ type: "OFFLINE_ERROR" });
    throw failure;
  }
  await tellClients({ type: repair ? "OFFLINE_READY" : "OFFLINE_DOWNLOADED", total: ASSETS.length });
  // Updates wait until all existing windows close or a parent requests activation.
}

self.addEventListener("install", event => event.waitUntil(installOffline()));

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(key => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME).map(key => caches.delete(key)));
    await self.clients.claim();
    await tellClients({ type: "OFFLINE_READY", total: ASSETS.length });
  })());
});

async function rangeResponse(response, range) {
  const match = /^bytes=(\d*)-(\d*)$/.exec(range || "");
  // Unsupported multipart/invalid ranges may be ignored with a full 200 response.
  if (!match || (!match[1] && !match[2])) return response;
  const data = await response.arrayBuffer();
  const length = data.byteLength;
  const start = match[1] ? Number(match[1]) : Math.max(0, length - Number(match[2]));
  const end = match[1] && match[2] ? Math.min(Number(match[2]), length - 1) : length - 1;
  if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start > end || start >= length || (!match[1] && Number(match[2]) === 0)) {
    return new Response(null, { status: 416, headers: { "Content-Range": `bytes */${length}` } });
  }
  const headers = new Headers(response.headers);
  headers.delete("Content-Encoding");
  headers.set("Content-Range", `bytes ${start}-${end}/${length}`);
  headers.set("Content-Length", String(end - start + 1));
  headers.set("Accept-Ranges", "bytes");
  return new Response(data.slice(start, end + 1), { status: 206, headers });
}

async function serveOffline(request, key) {
  const cache = await caches.open(CACHE_NAME);
  const response = await cache.match(key);
  if (!response) return fetch(request);
  return request.headers.has("Range") ? rangeResponse(response, request.headers.get("Range")) : response;
}

self.addEventListener("fetch", event => {
  if (event.request.method !== "GET") return;
  const url = new URL(event.request.url);
  if (url.origin !== SCOPE.origin) return;
  const key = url.origin + url.pathname;
  const isHome = event.request.mode === "navigate" && (key === SCOPE.href || key === INDEX_URL);
  if (isHome || ASSET_URLS.has(key)) {
    event.respondWith(serveOffline(event.request, isHome ? INDEX_URL : key));
  }
});

let repairInFlight;
self.addEventListener("message", event => {
  if (event.data?.type === "REPAIR_OFFLINE") {
    repairInFlight ||= installOffline(true).finally(() => { repairInFlight = null; });
    event.waitUntil(repairInFlight);
  }
  if (event.data?.type === "OFFLINE_STATUS") {
    event.waitUntil((async () => {
      const cache = await caches.open(CACHE_NAME);
      const complete = (await cache.keys()).length === ASSETS.length;
      event.source?.postMessage({ type: complete ? "OFFLINE_READY" : "OFFLINE_INCOMPLETE", version: CACHE_VERSION, total: ASSETS.length });
    })());
  }
  if (event.data?.type === "ACTIVATE_UPDATE") {
    event.waitUntil((async () => {
      const clients = (await self.clients.matchAll({ type: "window", includeUncontrolled: true })).filter(client => client.url.startsWith(SCOPE.href));
      if (clients.some(client => client.id !== event.source?.id)) {
        event.source?.postMessage({ type: "UPDATE_CLOSE_WINDOWS" });
        return;
      }
      await self.skipWaiting();
    })());
  }
});
