// Generated by scripts/build-voice-manifest.mjs. Existing family recordings stay in audio/.
export const VOICE_CLIPS = {
  "guide_welcome": {
    "text": "Szia! Mivel játsszunk?",
    "file": "audio/voice/guide_welcome.mp3"
  },
  "guide_topics": {
    "text": "Mit nézzünk meg? Válassz egy képet!",
    "file": "audio/voice/guide_topics.mp3"
  },
  "guide_picture_menu": {
    "text": "Nézegessünk képeket, vagy keressük meg, amit hallunk?",
    "file": "audio/voice/guide_picture_menu.mp3"
  },
  "guide_listening_game": {
    "text": "Hallgasd meg a szót, és keresd meg a képét!",
    "file": "audio/voice/guide_listening_game.mp3"
  },
  "guide_cards": {
    "text": "Koppints egy képre! Hallgassuk meg együtt!",
    "file": "audio/voice/guide_cards.mp3"
  },
  "guide_practice": {
    "text": "Egy szót mondjunk, vagy kettőt?",
    "file": "audio/voice/guide_practice.mp3"
  },
  "guide_imitate": {
    "text": "Hallgasd meg a szót, és mondd utánam!",
    "file": "audio/voice/guide_imitate.mp3"
  },
  "guide_phrase": {
    "text": "Hallgasd meg, és mondd utánam a két szót!",
    "file": "audio/voice/guide_phrase.mp3"
  },
  "guide_number_menu": {
    "text": "Számoljunk, vagy keressük meg a képet?",
    "file": "audio/voice/guide_number_menu.mp3"
  },
  "guide_count": {
    "text": "Koppints a tárgyakra! Számoljuk meg őket együtt!",
    "file": "audio/voice/guide_count.mp3"
  },
  "guide_quiz": {
    "text": "Keresd meg a képet! Hol van ennyi?",
    "file": "audio/voice/guide_quiz.mp3"
  },
  "guide_flip": {
    "text": "Mi bújt a kártya mögé? Koppints rá!",
    "file": "audio/voice/guide_flip.mp3"
  },
  "guide_listening": {
    "text": "Most te jössz!",
    "file": "audio/voice/guide_listening.mp3"
  },
  "guide_again": {
    "text": "Próbáljuk meg együtt!",
    "file": "audio/voice/guide_again.mp3"
  },
  "guide_good": {
    "text": "Ez az! Ügyes vagy!",
    "file": "audio/voice/guide_good.mp3"
  },
  "guide_finished": {
    "text": "De jó volt együtt játszani! Jöhet még egy kör?",
    "file": "audio/voice/guide_finished.mp3"
  },
  "guide_mic_help": {
    "text": "Kérj meg egy felnőttet, hogy kapcsolja be a mikrofont!",
    "file": "audio/voice/guide_mic_help.mp3"
  },
  "guide_goodbye": {
    "text": "Válasszunk egy másik játékot!",
    "file": "audio/voice/guide_goodbye.mp3"
  },
  "guide_one_word": {
    "text": "Egy szó.",
    "file": "audio/voice/guide_one_word.mp3"
  },
  "guide_two_words": {
    "text": "Két szó.",
    "file": "audio/voice/guide_two_words.mp3"
  },
  "guide_family": {
    "text": "Család.",
    "file": "audio/voice/guide_family.mp3"
  },
  "guide_animals": {
    "text": "Állatok.",
    "file": "audio/voice/guide_animals.mp3"
  },
  "guide_food": {
    "text": "Finomságok.",
    "file": "audio/voice/guide_food.mp3"
  },
  "guide_play": {
    "text": "Játék és utazás.",
    "file": "audio/voice/guide_play.mp3"
  },
  "guide_nature": {
    "text": "Természet.",
    "file": "audio/voice/guide_nature.mp3"
  },
  "guide_home": {
    "text": "Otthon.",
    "file": "audio/voice/guide_home.mp3"
  },
  "guide_retry_count": {
    "text": "Próbáld újra! Számold meg egyesével.",
    "file": "audio/voice/guide_retry_count.mp3"
  },
  "word_viz": {
    "text": "víz",
    "file": "audio/voice/word_viz.mp3"
  },
  "word_anya": {
    "text": "anya",
    "file": "audio/voice/word_anya.mp3"
  },
  "word_apa": {
    "text": "apa",
    "file": "audio/voice/word_apa.mp3"
  },
  "word_auto": {
    "text": "autó",
    "file": "audio/voice/word_auto.mp3"
  },
  "word_labda": {
    "text": "labda",
    "file": "audio/voice/word_labda.mp3"
  },
  "word_cica": {
    "text": "cica",
    "file": "audio/voice/word_cica.mp3"
  },
  "word_alma": {
    "text": "alma",
    "file": "audio/voice/word_alma.mp3"
  },
  "word_kifli": {
    "text": "kifli",
    "file": "audio/voice/word_kifli.mp3"
  },
  "word_tej": {
    "text": "tej",
    "file": "audio/voice/word_tej.mp3"
  },
  "word_furdokad": {
    "text": "fürdőkád",
    "file": "audio/voice/word_furdokad.mp3"
  },
  "word_maci": {
    "text": "maci",
    "file": "audio/voice/word_maci.mp3"
  },
  "word_szia": {
    "text": "szia",
    "file": "audio/voice/word_szia.mp3"
  },
  "word_kutya": {
    "text": "kutya",
    "file": "audio/voice/word_kutya.mp3"
  },
  "word_baba": {
    "text": "baba",
    "file": "audio/voice/word_baba.mp3"
  },
  "word_nap": {
    "text": "nap",
    "file": "audio/voice/word_nap.mp3"
  },
  "word_hold": {
    "text": "hold",
    "file": "audio/voice/word_hold.mp3"
  },
  "word_fa": {
    "text": "fa",
    "file": "audio/voice/word_fa.mp3"
  },
  "word_virag": {
    "text": "virág",
    "file": "audio/voice/word_virag.mp3"
  },
  "word_kenyer": {
    "text": "kenyér",
    "file": "audio/voice/word_kenyer.mp3"
  },
  "word_kanal": {
    "text": "kanál",
    "file": "audio/voice/word_kanal.mp3"
  },
  "word_cipo": {
    "text": "cipő",
    "file": "audio/voice/word_cipo.mp3"
  },
  "word_sapka": {
    "text": "sapka",
    "file": "audio/voice/word_sapka.mp3"
  },
  "word_vonat": {
    "text": "vonat",
    "file": "audio/voice/word_vonat.mp3"
  },
  "word_busz": {
    "text": "busz",
    "file": "audio/voice/word_busz.mp3"
  },
  "phrase_kerek_vizet": {
    "text": "kérek vizet",
    "file": "audio/voice/phrase_kerek_vizet.mp3"
  },
  "phrase_meg_alma": {
    "text": "még alma",
    "file": "audio/voice/phrase_meg_alma.mp3"
  },
  "phrase_anya_gyere": {
    "text": "anya gyere",
    "file": "audio/voice/phrase_anya_gyere.mp3"
  },
  "phrase_apa_auto": {
    "text": "apa autó",
    "file": "audio/voice/phrase_apa_auto.mp3"
  },
  "phrase_nagy_labda": {
    "text": "nagy labda",
    "file": "audio/voice/phrase_nagy_labda.mp3"
  },
  "phrase_nem_kerem": {
    "text": "nem kérem",
    "file": "audio/voice/phrase_nem_kerem.mp3"
  },
  "number_1": {
    "text": "egy",
    "file": "audio/voice/number_1.mp3"
  },
  "quantity_auto_1": {
    "text": "egy autó",
    "file": "audio/voice/quantity_auto_1.mp3"
  },
  "question_auto_1": {
    "text": "Hol van egy autó?",
    "file": "audio/voice/question_auto_1.mp3"
  },
  "quantity_labda_1": {
    "text": "egy labda",
    "file": "audio/voice/quantity_labda_1.mp3"
  },
  "question_labda_1": {
    "text": "Hol van egy labda?",
    "file": "audio/voice/question_labda_1.mp3"
  },
  "quantity_alma_1": {
    "text": "egy alma",
    "file": "audio/voice/quantity_alma_1.mp3"
  },
  "question_alma_1": {
    "text": "Hol van egy alma?",
    "file": "audio/voice/question_alma_1.mp3"
  },
  "number_2": {
    "text": "kettő",
    "file": "audio/voice/number_2.mp3"
  },
  "quantity_auto_2": {
    "text": "két autó",
    "file": "audio/voice/quantity_auto_2.mp3"
  },
  "question_auto_2": {
    "text": "Hol van két autó?",
    "file": "audio/voice/question_auto_2.mp3"
  },
  "quantity_labda_2": {
    "text": "két labda",
    "file": "audio/voice/quantity_labda_2.mp3"
  },
  "question_labda_2": {
    "text": "Hol van két labda?",
    "file": "audio/voice/question_labda_2.mp3"
  },
  "quantity_alma_2": {
    "text": "két alma",
    "file": "audio/voice/quantity_alma_2.mp3"
  },
  "question_alma_2": {
    "text": "Hol van két alma?",
    "file": "audio/voice/question_alma_2.mp3"
  },
  "number_3": {
    "text": "három",
    "file": "audio/voice/number_3.mp3"
  },
  "quantity_auto_3": {
    "text": "három autó",
    "file": "audio/voice/quantity_auto_3.mp3"
  },
  "question_auto_3": {
    "text": "Hol van három autó?",
    "file": "audio/voice/question_auto_3.mp3"
  },
  "quantity_labda_3": {
    "text": "három labda",
    "file": "audio/voice/quantity_labda_3.mp3"
  },
  "question_labda_3": {
    "text": "Hol van három labda?",
    "file": "audio/voice/question_labda_3.mp3"
  },
  "quantity_alma_3": {
    "text": "három alma",
    "file": "audio/voice/quantity_alma_3.mp3"
  },
  "question_alma_3": {
    "text": "Hol van három alma?",
    "file": "audio/voice/question_alma_3.mp3"
  },
  "number_4": {
    "text": "négy",
    "file": "audio/voice/number_4.mp3"
  },
  "quantity_auto_4": {
    "text": "négy autó",
    "file": "audio/voice/quantity_auto_4.mp3"
  },
  "question_auto_4": {
    "text": "Hol van négy autó?",
    "file": "audio/voice/question_auto_4.mp3"
  },
  "quantity_labda_4": {
    "text": "négy labda",
    "file": "audio/voice/quantity_labda_4.mp3"
  },
  "question_labda_4": {
    "text": "Hol van négy labda?",
    "file": "audio/voice/question_labda_4.mp3"
  },
  "quantity_alma_4": {
    "text": "négy alma",
    "file": "audio/voice/quantity_alma_4.mp3"
  },
  "question_alma_4": {
    "text": "Hol van négy alma?",
    "file": "audio/voice/question_alma_4.mp3"
  },
  "number_5": {
    "text": "öt",
    "file": "audio/voice/number_5.mp3"
  },
  "quantity_auto_5": {
    "text": "öt autó",
    "file": "audio/voice/quantity_auto_5.mp3"
  },
  "question_auto_5": {
    "text": "Hol van öt autó?",
    "file": "audio/voice/question_auto_5.mp3"
  },
  "quantity_labda_5": {
    "text": "öt labda",
    "file": "audio/voice/quantity_labda_5.mp3"
  },
  "question_labda_5": {
    "text": "Hol van öt labda?",
    "file": "audio/voice/question_labda_5.mp3"
  },
  "quantity_alma_5": {
    "text": "öt alma",
    "file": "audio/voice/quantity_alma_5.mp3"
  },
  "question_alma_5": {
    "text": "Hol van öt alma?",
    "file": "audio/voice/question_alma_5.mp3"
  },
  "number_6": {
    "text": "hat",
    "file": "audio/voice/number_6.mp3"
  },
  "quantity_auto_6": {
    "text": "hat autó",
    "file": "audio/voice/quantity_auto_6.mp3"
  },
  "question_auto_6": {
    "text": "Hol van hat autó?",
    "file": "audio/voice/question_auto_6.mp3"
  },
  "quantity_labda_6": {
    "text": "hat labda",
    "file": "audio/voice/quantity_labda_6.mp3"
  },
  "question_labda_6": {
    "text": "Hol van hat labda?",
    "file": "audio/voice/question_labda_6.mp3"
  },
  "quantity_alma_6": {
    "text": "hat alma",
    "file": "audio/voice/quantity_alma_6.mp3"
  },
  "question_alma_6": {
    "text": "Hol van hat alma?",
    "file": "audio/voice/question_alma_6.mp3"
  },
  "number_7": {
    "text": "hét",
    "file": "audio/voice/number_7.mp3"
  },
  "quantity_auto_7": {
    "text": "hét autó",
    "file": "audio/voice/quantity_auto_7.mp3"
  },
  "question_auto_7": {
    "text": "Hol van hét autó?",
    "file": "audio/voice/question_auto_7.mp3"
  },
  "quantity_labda_7": {
    "text": "hét labda",
    "file": "audio/voice/quantity_labda_7.mp3"
  },
  "question_labda_7": {
    "text": "Hol van hét labda?",
    "file": "audio/voice/question_labda_7.mp3"
  },
  "quantity_alma_7": {
    "text": "hét alma",
    "file": "audio/voice/quantity_alma_7.mp3"
  },
  "question_alma_7": {
    "text": "Hol van hét alma?",
    "file": "audio/voice/question_alma_7.mp3"
  },
  "number_8": {
    "text": "nyolc",
    "file": "audio/voice/number_8.mp3"
  },
  "quantity_auto_8": {
    "text": "nyolc autó",
    "file": "audio/voice/quantity_auto_8.mp3"
  },
  "question_auto_8": {
    "text": "Hol van nyolc autó?",
    "file": "audio/voice/question_auto_8.mp3"
  },
  "quantity_labda_8": {
    "text": "nyolc labda",
    "file": "audio/voice/quantity_labda_8.mp3"
  },
  "question_labda_8": {
    "text": "Hol van nyolc labda?",
    "file": "audio/voice/question_labda_8.mp3"
  },
  "quantity_alma_8": {
    "text": "nyolc alma",
    "file": "audio/voice/quantity_alma_8.mp3"
  },
  "question_alma_8": {
    "text": "Hol van nyolc alma?",
    "file": "audio/voice/question_alma_8.mp3"
  },
  "number_9": {
    "text": "kilenc",
    "file": "audio/voice/number_9.mp3"
  },
  "quantity_auto_9": {
    "text": "kilenc autó",
    "file": "audio/voice/quantity_auto_9.mp3"
  },
  "question_auto_9": {
    "text": "Hol van kilenc autó?",
    "file": "audio/voice/question_auto_9.mp3"
  },
  "quantity_labda_9": {
    "text": "kilenc labda",
    "file": "audio/voice/quantity_labda_9.mp3"
  },
  "question_labda_9": {
    "text": "Hol van kilenc labda?",
    "file": "audio/voice/question_labda_9.mp3"
  },
  "quantity_alma_9": {
    "text": "kilenc alma",
    "file": "audio/voice/quantity_alma_9.mp3"
  },
  "question_alma_9": {
    "text": "Hol van kilenc alma?",
    "file": "audio/voice/question_alma_9.mp3"
  },
  "number_10": {
    "text": "tíz",
    "file": "audio/voice/number_10.mp3"
  },
  "quantity_auto_10": {
    "text": "tíz autó",
    "file": "audio/voice/quantity_auto_10.mp3"
  },
  "question_auto_10": {
    "text": "Hol van tíz autó?",
    "file": "audio/voice/question_auto_10.mp3"
  },
  "quantity_labda_10": {
    "text": "tíz labda",
    "file": "audio/voice/quantity_labda_10.mp3"
  },
  "question_labda_10": {
    "text": "Hol van tíz labda?",
    "file": "audio/voice/question_labda_10.mp3"
  },
  "quantity_alma_10": {
    "text": "tíz alma",
    "file": "audio/voice/quantity_alma_10.mp3"
  },
  "question_alma_10": {
    "text": "Hol van tíz alma?",
    "file": "audio/voice/question_alma_10.mp3"
  }
};
