// Generated by scripts/build-voice-manifest.mjs. Existing family recordings stay in audio/.
export const VOICE_CLIPS = {
  "guide_welcome": {
    "text": "Szia! Kezdődhet a játék. Válassz egy képet!",
    "file": "audio/voice/guide_welcome.mp3"
  },
  "guide_play_menu": {
    "text": "Etessük meg a macit, vagy nézzük meg, mi bújt el!",
    "file": "audio/voice/guide_play_menu.mp3"
  },
  "guide_play_menu_more": {
    "text": "Etessük meg a macit, öltöztessük fel, vagy nézzük meg, mi bújt el!",
    "file": "audio/voice/guide_play_menu_more.mp3"
  },
  "guide_menu_pictures": {
    "text": "Képek és hangok. Nézegessünk képeket, keressünk hang után, vagy lapozzuk az állatkönyvet!",
    "file": "audio/voice/guide_menu_pictures.mp3"
  },
  "guide_menu_speech": {
    "text": "Mondjuk együtt! Válassz szavakat, rövid kifejezést vagy a róka R-kalandját!",
    "file": "audio/voice/guide_menu_speech.mp3"
  },
  "guide_menu_thinking": {
    "text": "Számoljunk, figyeljük a mintákat, és oldjunk meg fejtörőket! Válassz egy játékot!",
    "file": "audio/voice/guide_menu_thinking.mp3"
  },
  "guide_menu_stories": {
    "text": "Hallgassunk mesét, vagy játsszunk a macival! Válassz egy képet!",
    "file": "audio/voice/guide_menu_stories.mp3"
  },
  "guide_menu_activity": {
    "text": "Keress képpárokat, rakj össze egy képet, vagy tölts a barátainknak! Válassz egy játékot!",
    "file": "audio/voice/guide_menu_activity.mp3"
  },
  "guide_dress": {
    "text": "Sétálni szeretnék! Segíts felöltözni! Koppints arra, amit kérek!",
    "file": "audio/voice/guide_dress.mp3"
  },
  "guide_dress_finished": {
    "text": "Felöltöztem! Köszönöm! Indulhat a séta!",
    "file": "audio/voice/guide_dress_finished.mp3"
  },
  "guide_teddy": {
    "text": "Megéheztem! Hallgasd meg, mit kérek, és koppints a finomságra!",
    "file": "audio/voice/guide_teddy.mp3"
  },
  "guide_teddy_thanks": {
    "text": "De finom! Köszönöm!",
    "file": "audio/voice/guide_teddy_thanks.mp3"
  },
  "guide_teddy_finished": {
    "text": "Tele a pocakom! Köszönöm a finom pikniket!",
    "file": "audio/voice/guide_teddy_finished.mp3"
  },
  "guide_topics": {
    "text": "Itt vannak a képek. Válassz egyet!",
    "file": "audio/voice/guide_topics.mp3"
  },
  "guide_picture_menu": {
    "text": "Itt képeket nézegethetünk, és szavakat hallgathatunk. Válassz egy játékot!",
    "file": "audio/voice/guide_picture_menu.mp3"
  },
  "guide_listening_game": {
    "text": "Hallgasd meg a szót, és keresd meg a képét!",
    "file": "audio/voice/guide_listening_game.mp3"
  },
  "guide_cards": {
    "text": "Koppints egy képre! Hallgassuk meg együtt!",
    "file": "audio/voice/guide_cards.mp3"
  },
  "guide_practice": {
    "text": "Egy szóval vagy két szóval is gyakorolhatunk. Válassz egy képet!",
    "file": "audio/voice/guide_practice.mp3"
  },
  "guide_imitate": {
    "text": "Hallgasd meg a szót, és mondd utánam!",
    "file": "audio/voice/guide_imitate.mp3"
  },
  "guide_phrase": {
    "text": "Hallgasd meg, és mondd utánam a két szót!",
    "file": "audio/voice/guide_phrase.mp3"
  },
  "guide_number_menu": {
    "text": "Itt együtt számolunk. Válassz egy játékot!",
    "file": "audio/voice/guide_number_menu.mp3"
  },
  "guide_count": {
    "text": "Koppints a tárgyakra! Számoljuk meg őket együtt!",
    "file": "audio/voice/guide_count.mp3"
  },
  "guide_quiz": {
    "text": "Hallgasd meg, melyik képet keressük. Koppints rá!",
    "file": "audio/voice/guide_quiz.mp3"
  },
  "guide_flip": {
    "text": "A kártya mögött egy kép bújik meg. Koppints rá!",
    "file": "audio/voice/guide_flip.mp3"
  },
  "guide_listening": {
    "text": "Most te jössz!",
    "file": "audio/voice/guide_listening.mp3"
  },
  "guide_again": {
    "text": "Próbáljuk meg együtt!",
    "file": "audio/voice/guide_again.mp3"
  },
  "guide_good": {
    "text": "Ez az! Ügyes vagy!",
    "file": "audio/voice/guide_good.mp3"
  },
  "guide_finished": {
    "text": "De jó volt együtt játszani! Újabb kör vár rád.",
    "file": "audio/voice/guide_finished.mp3"
  },
  "guide_mic_help": {
    "text": "Kérj meg egy felnőttet, hogy kapcsolja be a mikrofont!",
    "file": "audio/voice/guide_mic_help.mp3"
  },
  "guide_goodbye": {
    "text": "Válasszunk egy másik játékot!",
    "file": "audio/voice/guide_goodbye.mp3"
  },
  "guide_one_word": {
    "text": "Egy szó.",
    "file": "audio/voice/guide_one_word.mp3"
  },
  "guide_two_words": {
    "text": "Két szó.",
    "file": "audio/voice/guide_two_words.mp3"
  },
  "guide_family": {
    "text": "Család.",
    "file": "audio/voice/guide_family.mp3"
  },
  "guide_animals": {
    "text": "Állatok.",
    "file": "audio/voice/guide_animals.mp3"
  },
  "guide_food": {
    "text": "Finomságok.",
    "file": "audio/voice/guide_food.mp3"
  },
  "guide_play": {
    "text": "Játék és utazás.",
    "file": "audio/voice/guide_play.mp3"
  },
  "guide_nature": {
    "text": "Természet.",
    "file": "audio/voice/guide_nature.mp3"
  },
  "guide_home": {
    "text": "Otthon.",
    "file": "audio/voice/guide_home.mp3"
  },
  "guide_retry_count": {
    "text": "Próbáld újra! Számold meg egyesével.",
    "file": "audio/voice/guide_retry_count.mp3"
  },
  "logic_play_menu": {
    "text": "Játsszunk a macival, menjünk Meseligetbe, vagy keressük a kirakós képét! Az a Furfangliget, ahol fejtörők várnak.",
    "file": "audio/voice/logic_play_menu.mp3"
  },
  "logic_menu": {
    "text": "Itt Furfangliget! Rendezzük be az erdei boltot, találjuk ki a gép szabályát, vagy tervezzünk egy csomagszállító utat!",
    "file": "audio/voice/logic_menu.mp3"
  },
  "logic_shop_1": {
    "text": "Két kosár várja a rendelést. A képek mutatják, mennyi kell bele. A plusz gombbal tehetsz bele, a mínusszal visszavehetsz. Ha elkészültél, koppints a Kész gombra!",
    "file": "audio/voice/logic_shop_1.mp3"
  },
  "logic_shop_2": {
    "text": "Új rendelés érkezett a két kosárhoz. A plusz hozzáadást, a mínusz elvételt jelent. Tedd bele, ami hiányzik, és vedd ki, ami sok!",
    "file": "audio/voice/logic_shop_2.mp3"
  },
  "logic_shop_3": {
    "text": "A rendelésből tudjuk, mennyi termés kell összesen. Azt is tudjuk, mennyivel több alma kell, mint gesztenye. Tedd a terméseket a két kosárba!",
    "file": "audio/voice/logic_shop_3.mp3"
  },
  "logic_change": {
    "text": "Változott a rendelés! Tedd bele, ami hiányzik, és vedd ki, ami sok!",
    "file": "audio/voice/logic_change.mp3"
  },
  "logic_apple": {
    "text": "Alma.",
    "file": "audio/voice/logic_apple.mp3"
  },
  "logic_nut": {
    "text": "Gesztenye.",
    "file": "audio/voice/logic_nut.mp3"
  },
  "logic_total": {
    "text": "Összesen ennyi termés kell.",
    "file": "audio/voice/logic_total.mp3"
  },
  "logic_difference": {
    "text": "Ennyivel több alma kell, mint gesztenye.",
    "file": "audio/voice/logic_difference.mp3"
  },
  "logic_plus": {
    "text": "Meg",
    "file": "audio/voice/logic_plus.mp3"
  },
  "logic_minus": {
    "text": "Mínusz",
    "file": "audio/voice/logic_minus.mp3"
  },
  "logic_equals": {
    "text": "Egyenlő",
    "file": "audio/voice/logic_equals.mp3"
  },
  "logic_shop_hint1": {
    "text": "Nézd meg külön a két kosarat! Mindegyikben pontosan annyi legyen, amennyit a rendelés kér.",
    "file": "audio/voice/logic_shop_hint1.mp3"
  },
  "logic_shop_hint2": {
    "text": "A pöttyök segítenek számolni. Tegyél hozzá, vagy vegyél el! A változtatást vissza is vonhatod.",
    "file": "audio/voice/logic_shop_hint2.mp3"
  },
  "logic_shop_hint3": {
    "text": "Most megmutatom, mennyi kell a két kosárba. Számold meg! Tegyél hozzá, vagy vegyél el, hogy ugyanannyi legyen!",
    "file": "audio/voice/logic_shop_hint3.mp3"
  },
  "logic_shop_more": {
    "text": "Az egyik kosárba még kell termés. Nézd meg a kiemelt kosarat!",
    "file": "audio/voice/logic_shop_more.mp3"
  },
  "logic_shop_less": {
    "text": "Az egyik kosárban több van a kelleténél. Vegyél ki belőle a mínusz gombbal!",
    "file": "audio/voice/logic_shop_less.mp3"
  },
  "logic_shop_done": {
    "text": "Mindkét rendelés elkészült! A barátaink elvitték a kosarakat. Köszönik a segítségedet!",
    "file": "audio/voice/logic_shop_done.mp3"
  },
  "logic_machine_1": {
    "text": "A példák megmutatják, hogyan működik a gép. Válassz egy műveletet, és próbáld ki! A két új szám eredményét te adod meg.",
    "file": "audio/voice/logic_machine_1.mp3"
  },
  "logic_machine_2": {
    "text": "Ugyanaz a szabály működik mindhárom példában. Most te rakod össze a gépet. A próbagombbal kísérletezhetsz. A két új szám eredményét te adod meg.",
    "file": "audio/voice/logic_machine_2.mp3"
  },
  "logic_machine_3": {
    "text": "Ebben a gépben két művelet követi egymást. A sorrend is számít! Koppints egy helyre, majd válassz bele műveletet! Próbáld ki, és oldd meg a két új esetet!",
    "file": "audio/voice/logic_machine_3.mp3"
  },
  "logic_input": {
    "text": "Bemenet.",
    "file": "audio/voice/logic_input.mp3"
  },
  "logic_output": {
    "text": "Kimenet.",
    "file": "audio/voice/logic_output.mp3"
  },
  "logic_predict": {
    "text": "Ide kerül a gépből kijövő szám.",
    "file": "audio/voice/logic_predict.mp3"
  },
  "logic_machine_hint1": {
    "text": "Figyeld meg a bemenő és a kijövő számokat! Mindhárom példában ugyanaz a szabály működik.",
    "file": "audio/voice/logic_machine_hint1.mp3"
  },
  "logic_machine_hint2": {
    "text": "Az első műveletet megmutatom. Próbáld ki a többi példán is!",
    "file": "audio/voice/logic_machine_hint2.mp3"
  },
  "logic_machine_hint3": {
    "text": "Megmutatom a gép műveleteit. A két új eredményt továbbra is te adod meg.",
    "file": "audio/voice/logic_machine_hint3.mp3"
  },
  "logic_machine_retry": {
    "text": "Ez a gép még másképp dolgozik, mint a példák. Változtass a műveleteken, és próbáld újra!",
    "file": "audio/voice/logic_machine_retry.mp3"
  },
  "logic_machine_fit": {
    "text": "A géped minden példához illik! Most a két új eredmény következik.",
    "file": "audio/voice/logic_machine_fit.mp3"
  },
  "logic_machine_guess": {
    "text": "A gép jó! Nézd meg újra a két új szám eredményét!",
    "file": "audio/voice/logic_machine_guess.mp3"
  },
  "logic_machine_empty": {
    "text": "Előbb tegyél műveletet a gép minden helyére!",
    "file": "audio/voice/logic_machine_empty.mp3"
  },
  "logic_machine_done": {
    "text": "Megfejtetted a szabályt, és a két új feladatot is megoldottad! Működik a gép!",
    "file": "audio/voice/logic_machine_done.mp3"
  },
  "logic_route_1": {
    "text": "Tervezz utat a rókának! Vedd fel a csomagot, majd menj a házhoz! Koppints egymás melletti mezőkre, vagy húzd végig az ujjad! A próbagomb indítja a rókát.",
    "file": "audio/voice/logic_route_1.mp3"
  },
  "logic_route_2": {
    "text": "Vidd el a csomagot a házhoz! A köveket kerüld meg! Tervezd meg az egész utat, aztán próbáld ki! Visszavonással javíthatsz.",
    "file": "audio/voice/logic_route_2.mp3"
  },
  "logic_route_3": {
    "text": "Mindkét csomagot el kell vinni a házhoz. Gondold végig, merre kerülsz! Az utadnak bele kell férnie a megadott lépésszámba. Több jó út is lehet.",
    "file": "audio/voice/logic_route_3.mp3"
  },
  "logic_route_steps": {
    "text": "Most kép nélkül tervezünk. A leírásból tudjuk, hol vannak a csomagok, a kövek és a ház. A nyilakkal sorban megadod a lépéseket. Fejben követed az utat, majd a próbagombbal ellenőrzöd.",
    "file": "audio/voice/logic_route_steps.mp3"
  },
  "logic_route_steps_hint2": {
    "text": "A segítségnél megjelenik a következő lehetséges irány. A nyilakkal folytathatod az útitervet.",
    "file": "audio/voice/logic_route_steps_hint2.mp3"
  },
  "logic_route_steps_hint3": {
    "text": "A segítségnél egy teljes lehetséges út lépései szerepelnek. Más jó út is lehet.",
    "file": "audio/voice/logic_route_steps_hint3.mp3"
  },
  "logic_route_steps_restart": {
    "text": "Ez az út már túl hosszú lenne. Visszavonással javíthatsz, vagy újratervezhetsz. A segítségnél egy rövidebb út lépései szerepelnek.",
    "file": "audio/voice/logic_route_steps_restart.mp3"
  },
  "logic_route_hint1": {
    "text": "Előbb a csomagokhoz tervezz utat, aztán a házhoz! Csak egymás melletti mezőkre léphetsz.",
    "file": "audio/voice/logic_route_hint1.mp3"
  },
  "logic_route_hint2": {
    "text": "A kiemelt mezőre lépve még célba érhetsz. Koppints rá, ha arra szeretnél menni!",
    "file": "audio/voice/logic_route_hint2.mp3"
  },
  "logic_route_hint3": {
    "text": "Megmutatok egy teljes lehetséges utat. Kövesd a számozott mezőket, vagy találj másikat!",
    "file": "audio/voice/logic_route_hint3.mp3"
  },
  "logic_route_restart_hint": {
    "text": "Ez az út már túl hosszú lenne. Vonj vissza néhány lépést! A pöttyök egy rövidebb utat mutatnak.",
    "file": "audio/voice/logic_route_restart_hint.mp3"
  },
  "logic_route_adjacent": {
    "text": "A róka csak szomszédos mezőre léphet. Átlósan nem tud menni.",
    "file": "audio/voice/logic_route_adjacent.mp3"
  },
  "logic_route_full": {
    "text": "Megtelt az útiterv. Vonj vissza egy lépést, ha másfelé mennél!",
    "file": "audio/voice/logic_route_full.mp3"
  },
  "logic_route_missing": {
    "text": "Még maradt csomag az ösvényen. Változtass az útiterven, és próbáld újra!",
    "file": "audio/voice/logic_route_missing.mp3"
  },
  "logic_route_home": {
    "text": "A csomag megvan, de még el kell jutni a házhoz. Folytasd az útitervet!",
    "file": "audio/voice/logic_route_home.mp3"
  },
  "logic_route_done": {
    "text": "Megérkezett minden csomag! A barátaink már vártak. Szép útiterv volt!",
    "file": "audio/voice/logic_route_done.mp3"
  },
  "logic_saved": {
    "text": "Itt folytathatod a félbehagyott feladatot.",
    "file": "audio/voice/logic_saved.mp3"
  },
  "logic_op_add1": {
    "text": "Adj hozzá egyet!",
    "file": "audio/voice/logic_op_add1.mp3"
  },
  "logic_op_sub1": {
    "text": "Vegyél el egyet!",
    "file": "audio/voice/logic_op_sub1.mp3"
  },
  "logic_op_add2": {
    "text": "Adj hozzá kettőt!",
    "file": "audio/voice/logic_op_add2.mp3"
  },
  "logic_op_sub2": {
    "text": "Vegyél el kettőt!",
    "file": "audio/voice/logic_op_sub2.mp3"
  },
  "logic_op_double": {
    "text": "Duplázd meg!",
    "file": "audio/voice/logic_op_double.mp3"
  },
  "logic_op_add3": {
    "text": "Adj hozzá hármat!",
    "file": "audio/voice/logic_op_add3.mp3"
  },
  "logic_op_sub3": {
    "text": "Vegyél el hármat!",
    "file": "audio/voice/logic_op_sub3.mp3"
  },
  "logic_n_0": {
    "text": "nulla",
    "file": "audio/voice/logic_n_0.mp3"
  },
  "logic_n_1": {
    "text": "egy",
    "file": "audio/voice/logic_n_1.mp3"
  },
  "logic_n_2": {
    "text": "kettő",
    "file": "audio/voice/logic_n_2.mp3"
  },
  "logic_n_3": {
    "text": "három",
    "file": "audio/voice/logic_n_3.mp3"
  },
  "logic_n_4": {
    "text": "négy",
    "file": "audio/voice/logic_n_4.mp3"
  },
  "logic_n_5": {
    "text": "öt",
    "file": "audio/voice/logic_n_5.mp3"
  },
  "logic_n_6": {
    "text": "hat",
    "file": "audio/voice/logic_n_6.mp3"
  },
  "logic_n_7": {
    "text": "hét",
    "file": "audio/voice/logic_n_7.mp3"
  },
  "logic_n_8": {
    "text": "nyolc",
    "file": "audio/voice/logic_n_8.mp3"
  },
  "logic_n_9": {
    "text": "kilenc",
    "file": "audio/voice/logic_n_9.mp3"
  },
  "logic_n_10": {
    "text": "tíz",
    "file": "audio/voice/logic_n_10.mp3"
  },
  "logic_n_11": {
    "text": "tizenegy",
    "file": "audio/voice/logic_n_11.mp3"
  },
  "logic_n_12": {
    "text": "tizenkettő",
    "file": "audio/voice/logic_n_12.mp3"
  },
  "logic_n_13": {
    "text": "tizenhárom",
    "file": "audio/voice/logic_n_13.mp3"
  },
  "logic_n_14": {
    "text": "tizennégy",
    "file": "audio/voice/logic_n_14.mp3"
  },
  "logic_n_15": {
    "text": "tizenöt",
    "file": "audio/voice/logic_n_15.mp3"
  },
  "logic_n_16": {
    "text": "tizenhat",
    "file": "audio/voice/logic_n_16.mp3"
  },
  "logic_n_17": {
    "text": "tizenhét",
    "file": "audio/voice/logic_n_17.mp3"
  },
  "logic_n_18": {
    "text": "tizennyolc",
    "file": "audio/voice/logic_n_18.mp3"
  },
  "logic_n_19": {
    "text": "tizenkilenc",
    "file": "audio/voice/logic_n_19.mp3"
  },
  "logic_n_20": {
    "text": "húsz",
    "file": "audio/voice/logic_n_20.mp3"
  },
  "memory_start": {
    "text": "Keress egyforma képeket! Fordíts fel két kártyát!",
    "file": "audio/voice/memory_start.mp3"
  },
  "memory_hint": {
    "text": "Nézzük meg együtt a képeket! Jegyezd meg, melyik hol van!",
    "file": "audio/voice/memory_hint.mp3"
  },
  "memory_match": {
    "text": "Ez egy pár! A két kép egyforma.",
    "file": "audio/voice/memory_match.mp3"
  },
  "memory_done": {
    "text": "Minden pár megvan! Szép munka!",
    "file": "audio/voice/memory_done.mp3"
  },
  "puzzle_start": {
    "text": "Rakjuk össze a képet! Válassz egy darabot, és koppints a helyére! Oda is húzhatod.",
    "file": "audio/voice/puzzle_start.mp3"
  },
  "puzzle_hint": {
    "text": "Nézzük meg a teljes képet! Keresd meg rajta a darabod helyét!",
    "file": "audio/voice/puzzle_hint.mp3"
  },
  "puzzle_retry": {
    "text": "Ez a darab másik helyre illik. Próbáld újra!",
    "file": "audio/voice/puzzle_retry.mp3"
  },
  "puzzle_place": {
    "text": "Ez az! A darab a helyén van.",
    "file": "audio/voice/puzzle_place.mp3"
  },
  "puzzle_done": {
    "text": "Elkészült a kép! Szép munka!",
    "file": "audio/voice/puzzle_done.mp3"
  },
  "workshop_menu": {
    "text": "Itt Műhelyliget! Válogasd a tárgyakat, folytasd a mintát, vagy hozd egyensúlyba a mérleget! A három gyémánt nehezebb feladatot jelent.",
    "file": "audio/voice/workshop_menu.mp3"
  },
  "workshop_level_1": {
    "text": "Felfedező. Egyszerűbb minták és kisebb mennyiségek várnak.",
    "file": "audio/voice/workshop_level_1.mp3"
  },
  "workshop_level_2": {
    "text": "Gondolkodó. Több tulajdonságot és a rudak számát is figyeld!",
    "file": "audio/voice/workshop_level_2.mp3"
  },
  "workshop_level_3": {
    "text": "Tervező. Több szabály működik egyszerre. Haladj lépésenként!",
    "file": "audio/voice/workshop_level_3.mp3"
  },
  "workshop_sort_1": {
    "text": "A tárgyakat színük szerint válogasd! Koppints egy tárgyra, majd a hozzá illő tálcára! A tárgy és a tálca színjele segít. A tálcáról vissza is veheted a tárgyat.",
    "file": "audio/voice/workshop_sort_1.mp3"
  },
  "workshop_sort_2": {
    "text": "Most a szín és a forma együtt mutatja a helyet. Válassz egy tárgyat, majd koppints a hozzá illő tálcára! A tárgyakat át is rendezheted.",
    "file": "audio/voice/workshop_sort_2.mp3"
  },
  "workshop_sort_3": {
    "text": "A megadott méretű tárgyakat szín és forma szerint válogasd a tálcákra! A másik méretű tárgyak a levélre kerülnek. Koppints a tárgyra, majd a helyére!",
    "file": "audio/voice/workshop_sort_3.mp3"
  },
  "workshop_only_big": {
    "text": "Csak a nagy tárgyak kerülnek a színes tálcákra. A kis tárgyakat a levélre tedd!",
    "file": "audio/voice/workshop_only_big.mp3"
  },
  "workshop_only_small": {
    "text": "Csak a kis tárgyak kerülnek a színes tálcákra. A nagy tárgyakat a levélre tedd!",
    "file": "audio/voice/workshop_only_small.mp3"
  },
  "workshop_sort_hint1": {
    "text": "A tárgy és a tálca színjele megegyezik. A nehezebb feladatban a formát és a megadott méretet is figyeld!",
    "file": "audio/voice/workshop_sort_hint1.mp3"
  },
  "workshop_sort_hint2": {
    "text": "A napocskás tárggyal folytasd! Nézd meg a színjelét és a formáját, majd válassz tálcát!",
    "file": "audio/voice/workshop_sort_hint2.mp3"
  },
  "workshop_sort_hint3": {
    "text": "A napocskás tárgy a napocskás tálcára illik. Koppints a tárgyra, majd arra a tálcára!",
    "file": "audio/voice/workshop_sort_hint3.mp3"
  },
  "workshop_sort_retry": {
    "text": "Néhány tárgynak még keresünk helyet. Figyeld a jeleket, és rendezd át őket! A lépéseket vissza is vonhatod.",
    "file": "audio/voice/workshop_sort_retry.mp3"
  },
  "workshop_sort_done": {
    "text": "Minden tárgy megtalálta a helyét! Rendezett lett a válogatókert. Szép munka!",
    "file": "audio/voice/workshop_sort_done.mp3"
  },
  "workshop_pattern_1": {
    "text": "Figyeld az ismétlődő mintát! Koppints egy üres helyre, majd válassz rá egy formát a készletből! A kitöltött helyet később át is cserélheted.",
    "file": "audio/voice/workshop_pattern_1.mp3"
  },
  "workshop_pattern_2": {
    "text": "A minta néhány helye üres. Az elején látod az ismétlődő egységet. Koppints egy üres helyre, és válassz rá formát! Minden hely illeszkedjen a mintához!",
    "file": "audio/voice/workshop_pattern_2.mp3"
  },
  "workshop_pattern_3": {
    "text": "Két szín váltakozik, a forma hármasával ismétlődik. A kettőt együtt figyeld! Koppints egy üres helyre, majd válassz rá formát a készletből!",
    "file": "audio/voice/workshop_pattern_3.mp3"
  },
  "workshop_pattern_hint1": {
    "text": "A minta elején kiemeltem az ismétlődő elemeket. Kövesd a sorrendjüket a következő helyeken is!",
    "file": "audio/voice/workshop_pattern_hint1.mp3"
  },
  "workshop_pattern_hint2": {
    "text": "A minta alatt külön is látod az ismétlődő egységet. A napocskás helyet töltsd ki vele!",
    "file": "audio/voice/workshop_pattern_hint2.mp3"
  },
  "workshop_pattern_hint3": {
    "text": "A napocskás forma a napocskás helyre illik. Koppints rá a formakészletben!",
    "file": "audio/voice/workshop_pattern_hint3.mp3"
  },
  "workshop_pattern_retry": {
    "text": "Néhány elem még hiányzik, vagy másként folytatja a mintát. Figyeld az ismétlődést, és cseréld át, amit szeretnél!",
    "file": "audio/voice/workshop_pattern_retry.mp3"
  },
  "workshop_pattern_done": {
    "text": "Minden elem illeszkedik! Végigfut a színes minta a műhelyen. Szép munka!",
    "file": "audio/voice/workshop_pattern_done.mp3"
  },
  "workshop_balance_1": {
    "text": "A bal oldalon lévő mennyiséget rudakkal rakd ki a jobb oldalon! Egy pötty egy egység. Koppints egy rúdra a készletben! A jobb oldalról a rúdra koppintva visszaveheted.",
    "file": "audio/voice/workshop_balance_1.mp3"
  },
  "workshop_balance_2": {
    "text": "Két különböző hosszúságú rudat tegyél a jobb oldalra! Együtt pontosan annyit érjenek, mint a bal oldal. Vissza is vehetsz egy rudat, és kipróbálhatsz másikat.",
    "file": "audio/voice/workshop_balance_2.mp3"
  },
  "workshop_balance_3": {
    "text": "Három különböző hosszúságú rudat válassz! Mindegyik hosszúságból csak egy van. A három együtt pontosan annyit érjen, mint a bal oldal. Rendezd át őket, amíg egyensúlyba kerül a mérleg!",
    "file": "audio/voice/workshop_balance_3.mp3"
  },
  "workshop_balance_hint1": {
    "text": "Egy pötty egy egység. Hasonlítsd össze a két oldalt! A hosszabb rúd többet ér.",
    "file": "audio/voice/workshop_balance_hint1.mp3"
  },
  "workshop_balance_hint2": {
    "text": "Megmutattam, mennyi hiányzik, vagy mennyivel van több a jobb oldalon. A nehezebb feladatban különböző rudakat válassz, a megadott darabszámban!",
    "file": "audio/voice/workshop_balance_hint2.mp3"
  },
  "workshop_balance_hint3": {
    "text": "A napocskás rúd mutatja a következő lépést. A készletből beteheted, a jobb oldalról visszaveheted. Így tovább alakíthatod az egyensúlyt.",
    "file": "audio/voice/workshop_balance_hint3.mp3"
  },
  "workshop_add_rod": {
    "text": "Tegyél be egy ilyen hosszúságú rudat!",
    "file": "audio/voice/workshop_add_rod.mp3"
  },
  "workshop_take_rod": {
    "text": "Vegyél vissza egy ilyen hosszúságú rudat!",
    "file": "audio/voice/workshop_take_rod.mp3"
  },
  "workshop_target": {
    "text": "A bal oldalon ennyi egység van.",
    "file": "audio/voice/workshop_target.mp3"
  },
  "workshop_balance_retry": {
    "text": "A rudakat még átrendezheted. Figyeld a mennyiséget és a megadott darabszámot! A lépéseket vissza is vonhatod.",
    "file": "audio/voice/workshop_balance_retry.mp3"
  },
  "workshop_balance_done": {
    "text": "A két oldal egyensúlyban van! Megtaláltad az összeillő rudakat. Szép munka!",
    "file": "audio/voice/workshop_balance_done.mp3"
  },
  "workshop_ready": {
    "text": "Minden a helyén van. Koppints a Kész gombra!",
    "file": "audio/voice/workshop_ready.mp3"
  },
  "workshop_n_0": {
    "text": "nulla",
    "file": "audio/voice/workshop_n_0.mp3"
  },
  "workshop_n_1": {
    "text": "egy",
    "file": "audio/voice/workshop_n_1.mp3"
  },
  "workshop_n_2": {
    "text": "kettő",
    "file": "audio/voice/workshop_n_2.mp3"
  },
  "workshop_n_3": {
    "text": "három",
    "file": "audio/voice/workshop_n_3.mp3"
  },
  "workshop_n_4": {
    "text": "négy",
    "file": "audio/voice/workshop_n_4.mp3"
  },
  "workshop_n_5": {
    "text": "öt",
    "file": "audio/voice/workshop_n_5.mp3"
  },
  "workshop_n_6": {
    "text": "hat",
    "file": "audio/voice/workshop_n_6.mp3"
  },
  "workshop_n_7": {
    "text": "hét",
    "file": "audio/voice/workshop_n_7.mp3"
  },
  "workshop_n_8": {
    "text": "nyolc",
    "file": "audio/voice/workshop_n_8.mp3"
  },
  "workshop_n_9": {
    "text": "kilenc",
    "file": "audio/voice/workshop_n_9.mp3"
  },
  "workshop_n_10": {
    "text": "tíz",
    "file": "audio/voice/workshop_n_10.mp3"
  },
  "workshop_n_11": {
    "text": "tizenegy",
    "file": "audio/voice/workshop_n_11.mp3"
  },
  "workshop_n_12": {
    "text": "tizenkettő",
    "file": "audio/voice/workshop_n_12.mp3"
  },
  "workshop_n_13": {
    "text": "tizenhárom",
    "file": "audio/voice/workshop_n_13.mp3"
  },
  "workshop_n_14": {
    "text": "tizennégy",
    "file": "audio/voice/workshop_n_14.mp3"
  },
  "workshop_n_15": {
    "text": "tizenöt",
    "file": "audio/voice/workshop_n_15.mp3"
  },
  "pour_start": {
    "text": "Kínáljuk meg a barátainkat! Válassz poharat, és tartsd nyomva az öntés gombot! Tölts a jelzésig!",
    "file": "audio/voice/pour_start.mp3"
  },
  "pour_tilt": {
    "text": "Tartsd kényelmesen a telefont! Döntsd balra a macihoz, jobbra a nyuszihoz! Középen megáll az öntés.",
    "file": "audio/voice/pour_tilt.mp3"
  },
  "pour_centre": {
    "text": "Hozd vissza középre a telefont! Utána tölthetünk a másik pohárba.",
    "file": "audio/voice/pour_centre.mp3"
  },
  "pour_manual": {
    "text": "Lassan önts a jelzésig! Amikor elengedjük a gombot, megáll a víz.",
    "file": "audio/voice/pour_manual.mp3"
  },
  "pour_two": {
    "text": "A macinak kevesebb, a nyuszinak több víz kell. Figyeld a jelzéseket!",
    "file": "audio/voice/pour_two.mp3"
  },
  "pour_bear_done": {
    "text": "A maci pohara elkészült! Köszönöm!",
    "file": "audio/voice/pour_bear_done.mp3"
  },
  "pour_rabbit_done": {
    "text": "A nyuszi pohara elkészült! Köszönöm!",
    "file": "audio/voice/pour_rabbit_done.mp3"
  },
  "pour_more": {
    "text": "Még egy kicsi víz kell. Töltsünk a jelzésig!",
    "file": "audio/voice/pour_more.mp3"
  },
  "pour_over": {
    "text": "Kicsit sok lett. Ürítsd ki ezt a poharat, és próbáljuk újra!",
    "file": "audio/voice/pour_over.mp3"
  },
  "pour_done": {
    "text": "Mindkét barátunk kapott inni! Kezdődhet a piknik!",
    "file": "audio/voice/pour_done.mp3"
  },
  "r_hub": {
    "text": "Róka és robot vár rád! Hallgassunk szavakat, mondjunk mondókát, és játsszunk együtt!",
    "file": "audio/voice/r_hub.mp3"
  },
  "r_hunter": {
    "text": "Hallgasd meg a szót! Koppints a képére!",
    "file": "audio/voice/r_hunter.mp3"
  },
  "r_hunter_sound": {
    "text": "Hallgasd meg a képek nevét! Keresd meg azt, amelyikben hallod az R hangot!",
    "file": "audio/voice/r_hunter_sound.mp3"
  },
  "r_post": {
    "text": "Robot csomagot vár. Hallgasd meg a szót, és mondd utánam!",
    "file": "audio/voice/r_post.mp3"
  },
  "r_workshop": {
    "text": "Díszítsük fel a perecműhelyt! Hallgasd meg a szót, és mondd utánam!",
    "file": "audio/voice/r_workshop.mp3"
  },
  "r_rhyme": {
    "text": "Hallgassunk mondókát! Koppints egy sorra, és mondd utánam!",
    "file": "audio/voice/r_rhyme.mp3"
  },
  "r_echo": {
    "text": "Hallgasd meg a mintát! A mikrofon gombbal felveheted a saját hangodat.",
    "file": "audio/voice/r_echo.mp3"
  },
  "r_try": {
    "text": "Most te jössz!",
    "file": "audio/voice/r_try.mp3"
  },
  "r_retry": {
    "text": "Hallgassuk meg még egyszer! Próbálhatjuk együtt is.",
    "file": "audio/voice/r_retry.mp3"
  },
  "r_found": {
    "text": "Megtaláltad a képet!",
    "file": "audio/voice/r_found.mp3"
  },
  "r_try_thanks": {
    "text": "Köszönöm, hogy próbálkoztál!",
    "file": "audio/voice/r_try_thanks.mp3"
  },
  "r_delivered": {
    "text": "Elindult a csomag! Robot örül neki.",
    "file": "audio/voice/r_delivered.mp3"
  },
  "r_decorated": {
    "text": "Új dísz került a műhelybe!",
    "file": "audio/voice/r_decorated.mp3"
  },
  "r_round_done": {
    "text": "Elkészült a közös játék! Jöhet egy újabb kaland.",
    "file": "audio/voice/r_round_done.mp3"
  },
  "r_word_roka": {
    "text": "róka",
    "file": "audio/voice/r_word_roka.mp3"
  },
  "r_word_repa": {
    "text": "répa",
    "file": "audio/voice/r_word_repa.mp3"
  },
  "r_word_robot": {
    "text": "robot",
    "file": "audio/voice/r_word_robot.mp3"
  },
  "r_word_ruha": {
    "text": "ruha",
    "file": "audio/voice/r_word_ruha.mp3"
  },
  "r_word_rozsa": {
    "text": "rózsa",
    "file": "audio/voice/r_word_rozsa.mp3"
  },
  "r_word_raketa": {
    "text": "rakéta",
    "file": "audio/voice/r_word_raketa.mp3"
  },
  "r_word_radio": {
    "text": "rádió",
    "file": "audio/voice/r_word_radio.mp3"
  },
  "r_word_rak": {
    "text": "rák",
    "file": "audio/voice/r_word_rak.mp3"
  },
  "r_word_rizs": {
    "text": "rizs",
    "file": "audio/voice/r_word_rizs.mp3"
  },
  "r_word_roller": {
    "text": "roller",
    "file": "audio/voice/r_word_roller.mp3"
  },
  "r_word_virag": {
    "text": "virág",
    "file": "audio/voice/r_word_virag.mp3"
  },
  "r_word_korte": {
    "text": "körte",
    "file": "audio/voice/r_word_korte.mp3"
  },
  "r_word_perec": {
    "text": "perec",
    "file": "audio/voice/r_word_perec.mp3"
  },
  "r_word_korona": {
    "text": "korona",
    "file": "audio/voice/r_word_korona.mp3"
  },
  "r_word_barack": {
    "text": "barack",
    "file": "audio/voice/r_word_barack.mp3"
  },
  "r_word_ceruza": {
    "text": "ceruza",
    "file": "audio/voice/r_word_ceruza.mp3"
  },
  "r_word_erdo": {
    "text": "erdő",
    "file": "audio/voice/r_word_erdo.mp3"
  },
  "r_word_sarkany": {
    "text": "sárkány",
    "file": "audio/voice/r_word_sarkany.mp3"
  },
  "r_word_torta": {
    "text": "torta",
    "file": "audio/voice/r_word_torta.mp3"
  },
  "r_word_dinnye": {
    "text": "görögdinnye",
    "file": "audio/voice/r_word_dinnye.mp3"
  },
  "r_word_var": {
    "text": "vár",
    "file": "audio/voice/r_word_var.mp3"
  },
  "r_word_pohar": {
    "text": "pohár",
    "file": "audio/voice/r_word_pohar.mp3"
  },
  "r_word_madar": {
    "text": "madár",
    "file": "audio/voice/r_word_madar.mp3"
  },
  "r_word_eger": {
    "text": "egér",
    "file": "audio/voice/r_word_eger.mp3"
  },
  "r_word_hoember": {
    "text": "hóember",
    "file": "audio/voice/r_word_hoember.mp3"
  },
  "r_word_naptar": {
    "text": "naptár",
    "file": "audio/voice/r_word_naptar.mp3"
  },
  "r_word_szamar": {
    "text": "szamár",
    "file": "audio/voice/r_word_szamar.mp3"
  },
  "r_word_vodor": {
    "text": "vödör",
    "file": "audio/voice/r_word_vodor.mp3"
  },
  "r_word_sator": {
    "text": "sátor",
    "file": "audio/voice/r_word_sator.mp3"
  },
  "r_word_kosar": {
    "text": "kosár",
    "file": "audio/voice/r_word_kosar.mp3"
  },
  "r_word_alma": {
    "text": "alma",
    "file": "audio/voice/r_word_alma.mp3"
  },
  "r_word_cica": {
    "text": "cica",
    "file": "audio/voice/r_word_cica.mp3"
  },
  "r_word_kutya": {
    "text": "kutya",
    "file": "audio/voice/r_word_kutya.mp3"
  },
  "r_word_labda": {
    "text": "labda",
    "file": "audio/voice/r_word_labda.mp3"
  },
  "r_word_baba": {
    "text": "baba",
    "file": "audio/voice/r_word_baba.mp3"
  },
  "r_word_banan": {
    "text": "banán",
    "file": "audio/voice/r_word_banan.mp3"
  },
  "r_phrase_roka": {
    "text": "vörös róka",
    "file": "audio/voice/r_phrase_roka.mp3"
  },
  "r_phrase_repa": {
    "text": "piros répa",
    "file": "audio/voice/r_phrase_repa.mp3"
  },
  "r_phrase_robot": {
    "text": "vidám robot",
    "file": "audio/voice/r_phrase_robot.mp3"
  },
  "r_phrase_ruha": {
    "text": "piros ruha",
    "file": "audio/voice/r_phrase_ruha.mp3"
  },
  "r_phrase_rozsa": {
    "text": "piros rózsa",
    "file": "audio/voice/r_phrase_rozsa.mp3"
  },
  "r_phrase_raketa": {
    "text": "repül a rakéta",
    "file": "audio/voice/r_phrase_raketa.mp3"
  },
  "r_phrase_radio": {
    "text": "szól a rádió",
    "file": "audio/voice/r_phrase_radio.mp3"
  },
  "r_phrase_rak": {
    "text": "apró rák",
    "file": "audio/voice/r_phrase_rak.mp3"
  },
  "r_phrase_rizs": {
    "text": "forró rizs",
    "file": "audio/voice/r_phrase_rizs.mp3"
  },
  "r_phrase_roller": {
    "text": "gurul a roller",
    "file": "audio/voice/r_phrase_roller.mp3"
  },
  "r_phrase_virag": {
    "text": "piros virág",
    "file": "audio/voice/r_phrase_virag.mp3"
  },
  "r_phrase_korte": {
    "text": "érett körte",
    "file": "audio/voice/r_phrase_korte.mp3"
  },
  "r_phrase_perec": {
    "text": "kerek perec",
    "file": "audio/voice/r_phrase_perec.mp3"
  },
  "r_phrase_korona": {
    "text": "arany korona",
    "file": "audio/voice/r_phrase_korona.mp3"
  },
  "r_phrase_barack": {
    "text": "érett barack",
    "file": "audio/voice/r_phrase_barack.mp3"
  },
  "r_phrase_ceruza": {
    "text": "piros ceruza",
    "file": "audio/voice/r_phrase_ceruza.mp3"
  },
  "r_phrase_erdo": {
    "text": "sűrű erdő",
    "file": "audio/voice/r_phrase_erdo.mp3"
  },
  "r_phrase_sarkany": {
    "text": "repül a sárkány",
    "file": "audio/voice/r_phrase_sarkany.mp3"
  },
  "r_phrase_torta": {
    "text": "kerek torta",
    "file": "audio/voice/r_phrase_torta.mp3"
  },
  "r_phrase_dinnye": {
    "text": "érett görögdinnye",
    "file": "audio/voice/r_phrase_dinnye.mp3"
  },
  "r_phrase_var": {
    "text": "magas vár",
    "file": "audio/voice/r_phrase_var.mp3"
  },
  "r_phrase_pohar": {
    "text": "üres pohár",
    "file": "audio/voice/r_phrase_pohar.mp3"
  },
  "r_phrase_madar": {
    "text": "repül a madár",
    "file": "audio/voice/r_phrase_madar.mp3"
  },
  "r_phrase_eger": {
    "text": "apró egér",
    "file": "audio/voice/r_phrase_eger.mp3"
  },
  "r_phrase_hoember": {
    "text": "fehér hóember",
    "file": "audio/voice/r_phrase_hoember.mp3"
  },
  "r_phrase_naptar": {
    "text": "új naptár",
    "file": "audio/voice/r_phrase_naptar.mp3"
  },
  "r_phrase_szamar": {
    "text": "szürke szamár",
    "file": "audio/voice/r_phrase_szamar.mp3"
  },
  "r_phrase_vodor": {
    "text": "üres vödör",
    "file": "audio/voice/r_phrase_vodor.mp3"
  },
  "r_phrase_sator": {
    "text": "piros sátor",
    "file": "audio/voice/r_phrase_sator.mp3"
  },
  "r_phrase_kosar": {
    "text": "üres kosár",
    "file": "audio/voice/r_phrase_kosar.mp3"
  },
  "r_rhyme_roka_0": {
    "text": "Róka fut a réten át.",
    "file": "audio/voice/r_rhyme_roka_0.mp3"
  },
  "r_rhyme_roka_1": {
    "text": "Robot őrzi a répát.",
    "file": "audio/voice/r_rhyme_roka_1.mp3"
  },
  "r_rhyme_roka_2": {
    "text": "Ropi roppan, perec kerek.",
    "file": "audio/voice/r_rhyme_roka_2.mp3"
  },
  "r_rhyme_roka_3": {
    "text": "Velük játszik minden gyerek.",
    "file": "audio/voice/r_rhyme_roka_3.mp3"
  },
  "r_rhyme_kert_0": {
    "text": "Piros rózsa nyílik reggel.",
    "file": "audio/voice/r_rhyme_kert_0.mp3"
  },
  "r_rhyme_kert_1": {
    "text": "Robot locsol friss vízcseppel.",
    "file": "audio/voice/r_rhyme_kert_1.mp3"
  },
  "r_rhyme_kert_2": {
    "text": "Róka körben táncot jár.",
    "file": "audio/voice/r_rhyme_kert_2.mp3"
  },
  "r_rhyme_kert_3": {
    "text": "Ránk egy szép virágkert vár.",
    "file": "audio/voice/r_rhyme_kert_3.mp3"
  },
  "r_rhyme_sator_0": {
    "text": "Erre gyere, erre várunk!",
    "file": "audio/voice/r_rhyme_sator_0.mp3"
  },
  "r_rhyme_sator_1": {
    "text": "Erdő mellett sátrat állunk.",
    "file": "audio/voice/r_rhyme_sator_1.mp3"
  },
  "r_rhyme_sator_2": {
    "text": "Körte kerül a kosárba.",
    "file": "audio/voice/r_rhyme_sator_2.mp3"
  },
  "r_rhyme_sator_3": {
    "text": "Róka indul vacsorára.",
    "file": "audio/voice/r_rhyme_sator_3.mp3"
  },
  "r_rhyme_robot_0": {
    "text": "Rajzol a robot: kerek a nap.",
    "file": "audio/voice/r_rhyme_robot_0.mp3"
  },
  "r_rhyme_robot_1": {
    "text": "Piros ceruzát a kezébe kap.",
    "file": "audio/voice/r_rhyme_robot_1.mp3"
  },
  "r_rhyme_robot_2": {
    "text": "Rajzol egy rókát, rajzol egy várat.",
    "file": "audio/voice/r_rhyme_robot_2.mp3"
  },
  "r_rhyme_robot_3": {
    "text": "Rajzol az égre repülő madarat.",
    "file": "audio/voice/r_rhyme_robot_3.mp3"
  },
  "mese_map": {
    "text": "Szia! Ez itt Meseliget. Szedjünk almát, terítsünk meg, vagy induljunk együtt piknikezni!",
    "file": "audio/voice/mese_map.mp3"
  },
  "mese_start": {
    "text": "Piknikezni indulunk! Először adjuk fel a maci sapkáját és cipőjét!",
    "file": "audio/voice/mese_start.mp3"
  },
  "mese_dressed": {
    "text": "Felöltöztem! Most szedjünk almát a barátainknak!",
    "file": "audio/voice/mese_dressed.mp3"
  },
  "mese_serve": {
    "text": "Adj minden állatnak egy tányért! Koppints az állatok elé!",
    "file": "audio/voice/mese_serve.mp3"
  },
  "mese_served": {
    "text": "Mindenkinek jutott tányér! Kezdődhet a piknik!",
    "file": "audio/voice/mese_served.mp3"
  },
  "mese_more": {
    "text": "Még kell alma a kosárba. Tegyél bele még!",
    "file": "audio/voice/mese_more.mp3"
  },
  "mese_less": {
    "text": "Kicsit sok lett! Koppints a kosárban egy almára, és tedd vissza!",
    "file": "audio/voice/mese_less.mp3"
  },
  "mese_count_help": {
    "text": "Számoljunk együtt! A pöttyök mutatják, hány alma kell a kosárba.",
    "file": "audio/voice/mese_count_help.mp3"
  },
  "mese_plate_help": {
    "text": "Nézd, kinek nincs még tányérja! Koppints elé, és adj neki egyet!",
    "file": "audio/voice/mese_plate_help.mp3"
  },
  "mese_plate_more": {
    "text": "Valakinek még nincs tányérja. Nézzük meg együtt!",
    "file": "audio/voice/mese_plate_more.mp3"
  },
  "mese_finish": {
    "text": "Elkészült a piknik! Köszönöm a segítséget! Ezt a képet eltesszük emlékbe.",
    "file": "audio/voice/mese_finish.mp3"
  },
  "mese_free_finish": {
    "text": "Ügyesen segítettél! Pihenjünk meg, vagy játsszunk még!",
    "file": "audio/voice/mese_free_finish.mp3"
  },
  "mese_album": {
    "text": "Ezek a közös piknikjeink emlékei!",
    "file": "audio/voice/mese_album.mp3"
  },
  "mese_empty_album": {
    "text": "Itt lesz a közös piknikünk képe. Induljunk el egy kalandra!",
    "file": "audio/voice/mese_empty_album.mp3"
  },
  "mese_play_menu": {
    "text": "Etessük meg a macit, öltöztessük fel, keressünk képeket, vagy kiránduljunk Meseligetben!",
    "file": "audio/voice/mese_play_menu.mp3"
  },
  "mese_collect_1": {
    "text": "Tegyél egy almát a kosárba!",
    "file": "audio/voice/mese_collect_1.mp3"
  },
  "mese_collected_1": {
    "text": "Megvan az egy alma! Köszönöm!",
    "file": "audio/voice/mese_collected_1.mp3"
  },
  "mese_collect_2": {
    "text": "Tegyél két almát a kosárba!",
    "file": "audio/voice/mese_collect_2.mp3"
  },
  "mese_collected_2": {
    "text": "Megvan a két alma! Köszönöm!",
    "file": "audio/voice/mese_collected_2.mp3"
  },
  "mese_collect_3": {
    "text": "Tegyél három almát a kosárba!",
    "file": "audio/voice/mese_collect_3.mp3"
  },
  "mese_collected_3": {
    "text": "Megvan a három alma! Köszönöm!",
    "file": "audio/voice/mese_collected_3.mp3"
  },
  "mese_collect_4": {
    "text": "Tegyél négy almát a kosárba!",
    "file": "audio/voice/mese_collect_4.mp3"
  },
  "mese_collected_4": {
    "text": "Megvan a négy alma! Köszönöm!",
    "file": "audio/voice/mese_collected_4.mp3"
  },
  "mese_collect_5": {
    "text": "Tegyél öt almát a kosárba!",
    "file": "audio/voice/mese_collect_5.mp3"
  },
  "mese_collected_5": {
    "text": "Megvan a öt alma! Köszönöm!",
    "file": "audio/voice/mese_collected_5.mp3"
  },
  "mese_collect_6": {
    "text": "Tegyél hat almát a kosárba!",
    "file": "audio/voice/mese_collect_6.mp3"
  },
  "mese_collected_6": {
    "text": "Megvan a hat alma! Köszönöm!",
    "file": "audio/voice/mese_collected_6.mp3"
  },
  "mese_collect_7": {
    "text": "Tegyél hét almát a kosárba!",
    "file": "audio/voice/mese_collect_7.mp3"
  },
  "mese_collected_7": {
    "text": "Megvan a hét alma! Köszönöm!",
    "file": "audio/voice/mese_collected_7.mp3"
  },
  "mese_collect_8": {
    "text": "Tegyél nyolc almát a kosárba!",
    "file": "audio/voice/mese_collect_8.mp3"
  },
  "mese_collected_8": {
    "text": "Megvan a nyolc alma! Köszönöm!",
    "file": "audio/voice/mese_collected_8.mp3"
  },
  "mese_collect_9": {
    "text": "Tegyél kilenc almát a kosárba!",
    "file": "audio/voice/mese_collect_9.mp3"
  },
  "mese_collected_9": {
    "text": "Megvan a kilenc alma! Köszönöm!",
    "file": "audio/voice/mese_collected_9.mp3"
  },
  "mese_collect_10": {
    "text": "Tegyél tíz almát a kosárba!",
    "file": "audio/voice/mese_collect_10.mp3"
  },
  "mese_collected_10": {
    "text": "Megvan a tíz alma! Köszönöm!",
    "file": "audio/voice/mese_collected_10.mp3"
  },
  "teddy_alma": {
    "text": "Kérek almát.",
    "file": "audio/voice/teddy_alma.mp3"
  },
  "teddy_kifli": {
    "text": "Kérek kiflit.",
    "file": "audio/voice/teddy_kifli.mp3"
  },
  "teddy_kenyer": {
    "text": "Kérek kenyeret.",
    "file": "audio/voice/teddy_kenyer.mp3"
  },
  "teddy_tej": {
    "text": "Kérek tejet.",
    "file": "audio/voice/teddy_tej.mp3"
  },
  "teddy_viz": {
    "text": "Kérek vizet.",
    "file": "audio/voice/teddy_viz.mp3"
  },
  "dress_request_sapka": {
    "text": "Kérem a sapkát.",
    "file": "audio/voice/dress_request_sapka.mp3"
  },
  "dress_thanks_sapka": {
    "text": "Meleg a sapkám!",
    "file": "audio/voice/dress_thanks_sapka.mp3"
  },
  "dress_request_polo": {
    "text": "Kérem a pólót.",
    "file": "audio/voice/dress_request_polo.mp3"
  },
  "dress_thanks_polo": {
    "text": "Jó puha a pólóm!",
    "file": "audio/voice/dress_thanks_polo.mp3"
  },
  "dress_request_sal": {
    "text": "Kérem a sálat.",
    "file": "audio/voice/dress_request_sal.mp3"
  },
  "dress_thanks_sal": {
    "text": "Meleg a sálam!",
    "file": "audio/voice/dress_thanks_sal.mp3"
  },
  "dress_request_cipo": {
    "text": "Kérem a cipőt.",
    "file": "audio/voice/dress_request_cipo.mp3"
  },
  "dress_thanks_cipo": {
    "text": "Kényelmes a cipőm!",
    "file": "audio/voice/dress_thanks_cipo.mp3"
  },
  "word_viz": {
    "text": "víz",
    "file": "audio/voice/word_viz.mp3"
  },
  "word_anya": {
    "text": "anya",
    "file": "audio/voice/word_anya.mp3"
  },
  "word_apa": {
    "text": "apa",
    "file": "audio/voice/word_apa.mp3"
  },
  "word_auto": {
    "text": "autó",
    "file": "audio/voice/word_auto.mp3"
  },
  "word_labda": {
    "text": "labda",
    "file": "audio/voice/word_labda.mp3"
  },
  "word_cica": {
    "text": "cica",
    "file": "audio/voice/word_cica.mp3"
  },
  "word_alma": {
    "text": "alma",
    "file": "audio/voice/word_alma.mp3"
  },
  "word_kifli": {
    "text": "kifli",
    "file": "audio/voice/word_kifli.mp3"
  },
  "word_tej": {
    "text": "tej",
    "file": "audio/voice/word_tej.mp3"
  },
  "word_furdokad": {
    "text": "fürdőkád",
    "file": "audio/voice/word_furdokad.mp3"
  },
  "word_maci": {
    "text": "maci",
    "file": "audio/voice/word_maci.mp3"
  },
  "word_szia": {
    "text": "szia",
    "file": "audio/voice/word_szia.mp3"
  },
  "word_kutya": {
    "text": "kutya",
    "file": "audio/voice/word_kutya.mp3"
  },
  "word_baba": {
    "text": "baba",
    "file": "audio/voice/word_baba.mp3"
  },
  "word_nap": {
    "text": "nap",
    "file": "audio/voice/word_nap.mp3"
  },
  "word_hold": {
    "text": "hold",
    "file": "audio/voice/word_hold.mp3"
  },
  "word_fa": {
    "text": "fa",
    "file": "audio/voice/word_fa.mp3"
  },
  "word_virag": {
    "text": "virág",
    "file": "audio/voice/word_virag.mp3"
  },
  "word_kenyer": {
    "text": "kenyér",
    "file": "audio/voice/word_kenyer.mp3"
  },
  "word_kanal": {
    "text": "kanál",
    "file": "audio/voice/word_kanal.mp3"
  },
  "word_cipo": {
    "text": "cipő",
    "file": "audio/voice/word_cipo.mp3"
  },
  "word_sapka": {
    "text": "sapka",
    "file": "audio/voice/word_sapka.mp3"
  },
  "word_vonat": {
    "text": "vonat",
    "file": "audio/voice/word_vonat.mp3"
  },
  "word_busz": {
    "text": "busz",
    "file": "audio/voice/word_busz.mp3"
  },
  "phrase_kerek_vizet": {
    "text": "kérek vizet",
    "file": "audio/voice/phrase_kerek_vizet.mp3"
  },
  "phrase_meg_alma": {
    "text": "még alma",
    "file": "audio/voice/phrase_meg_alma.mp3"
  },
  "phrase_anya_gyere": {
    "text": "anya gyere",
    "file": "audio/voice/phrase_anya_gyere.mp3"
  },
  "phrase_apa_auto": {
    "text": "apa autó",
    "file": "audio/voice/phrase_apa_auto.mp3"
  },
  "phrase_nagy_labda": {
    "text": "nagy labda",
    "file": "audio/voice/phrase_nagy_labda.mp3"
  },
  "phrase_nem_kerem": {
    "text": "nem kérem",
    "file": "audio/voice/phrase_nem_kerem.mp3"
  },
  "number_1": {
    "text": "egy",
    "file": "audio/voice/number_1.mp3"
  },
  "quantity_auto_1": {
    "text": "egy autó",
    "file": "audio/voice/quantity_auto_1.mp3"
  },
  "question_auto_1": {
    "text": "Ezen a képen egy autó van. Keresd meg!",
    "file": "audio/voice/question_auto_1.mp3"
  },
  "quantity_labda_1": {
    "text": "egy labda",
    "file": "audio/voice/quantity_labda_1.mp3"
  },
  "question_labda_1": {
    "text": "Ezen a képen egy labda van. Keresd meg!",
    "file": "audio/voice/question_labda_1.mp3"
  },
  "quantity_alma_1": {
    "text": "egy alma",
    "file": "audio/voice/quantity_alma_1.mp3"
  },
  "question_alma_1": {
    "text": "Ezen a képen egy alma van. Keresd meg!",
    "file": "audio/voice/question_alma_1.mp3"
  },
  "number_2": {
    "text": "kettő",
    "file": "audio/voice/number_2.mp3"
  },
  "quantity_auto_2": {
    "text": "két autó",
    "file": "audio/voice/quantity_auto_2.mp3"
  },
  "question_auto_2": {
    "text": "Ezen a képen két autó van. Keresd meg!",
    "file": "audio/voice/question_auto_2.mp3"
  },
  "quantity_labda_2": {
    "text": "két labda",
    "file": "audio/voice/quantity_labda_2.mp3"
  },
  "question_labda_2": {
    "text": "Ezen a képen két labda van. Keresd meg!",
    "file": "audio/voice/question_labda_2.mp3"
  },
  "quantity_alma_2": {
    "text": "két alma",
    "file": "audio/voice/quantity_alma_2.mp3"
  },
  "question_alma_2": {
    "text": "Ezen a képen két alma van. Keresd meg!",
    "file": "audio/voice/question_alma_2.mp3"
  },
  "number_3": {
    "text": "három",
    "file": "audio/voice/number_3.mp3"
  },
  "quantity_auto_3": {
    "text": "három autó",
    "file": "audio/voice/quantity_auto_3.mp3"
  },
  "question_auto_3": {
    "text": "Ezen a képen három autó van. Keresd meg!",
    "file": "audio/voice/question_auto_3.mp3"
  },
  "quantity_labda_3": {
    "text": "három labda",
    "file": "audio/voice/quantity_labda_3.mp3"
  },
  "question_labda_3": {
    "text": "Ezen a képen három labda van. Keresd meg!",
    "file": "audio/voice/question_labda_3.mp3"
  },
  "quantity_alma_3": {
    "text": "három alma",
    "file": "audio/voice/quantity_alma_3.mp3"
  },
  "question_alma_3": {
    "text": "Ezen a képen három alma van. Keresd meg!",
    "file": "audio/voice/question_alma_3.mp3"
  },
  "number_4": {
    "text": "négy",
    "file": "audio/voice/number_4.mp3"
  },
  "quantity_auto_4": {
    "text": "négy autó",
    "file": "audio/voice/quantity_auto_4.mp3"
  },
  "question_auto_4": {
    "text": "Ezen a képen négy autó van. Keresd meg!",
    "file": "audio/voice/question_auto_4.mp3"
  },
  "quantity_labda_4": {
    "text": "négy labda",
    "file": "audio/voice/quantity_labda_4.mp3"
  },
  "question_labda_4": {
    "text": "Ezen a képen négy labda van. Keresd meg!",
    "file": "audio/voice/question_labda_4.mp3"
  },
  "quantity_alma_4": {
    "text": "négy alma",
    "file": "audio/voice/quantity_alma_4.mp3"
  },
  "question_alma_4": {
    "text": "Ezen a képen négy alma van. Keresd meg!",
    "file": "audio/voice/question_alma_4.mp3"
  },
  "number_5": {
    "text": "öt",
    "file": "audio/voice/number_5.mp3"
  },
  "quantity_auto_5": {
    "text": "öt autó",
    "file": "audio/voice/quantity_auto_5.mp3"
  },
  "question_auto_5": {
    "text": "Ezen a képen öt autó van. Keresd meg!",
    "file": "audio/voice/question_auto_5.mp3"
  },
  "quantity_labda_5": {
    "text": "öt labda",
    "file": "audio/voice/quantity_labda_5.mp3"
  },
  "question_labda_5": {
    "text": "Ezen a képen öt labda van. Keresd meg!",
    "file": "audio/voice/question_labda_5.mp3"
  },
  "quantity_alma_5": {
    "text": "öt alma",
    "file": "audio/voice/quantity_alma_5.mp3"
  },
  "question_alma_5": {
    "text": "Ezen a képen öt alma van. Keresd meg!",
    "file": "audio/voice/question_alma_5.mp3"
  },
  "number_6": {
    "text": "hat",
    "file": "audio/voice/number_6.mp3"
  },
  "quantity_auto_6": {
    "text": "hat autó",
    "file": "audio/voice/quantity_auto_6.mp3"
  },
  "question_auto_6": {
    "text": "Ezen a képen hat autó van. Keresd meg!",
    "file": "audio/voice/question_auto_6.mp3"
  },
  "quantity_labda_6": {
    "text": "hat labda",
    "file": "audio/voice/quantity_labda_6.mp3"
  },
  "question_labda_6": {
    "text": "Ezen a képen hat labda van. Keresd meg!",
    "file": "audio/voice/question_labda_6.mp3"
  },
  "quantity_alma_6": {
    "text": "hat alma",
    "file": "audio/voice/quantity_alma_6.mp3"
  },
  "question_alma_6": {
    "text": "Ezen a képen hat alma van. Keresd meg!",
    "file": "audio/voice/question_alma_6.mp3"
  },
  "number_7": {
    "text": "hét",
    "file": "audio/voice/number_7.mp3"
  },
  "quantity_auto_7": {
    "text": "hét autó",
    "file": "audio/voice/quantity_auto_7.mp3"
  },
  "question_auto_7": {
    "text": "Ezen a képen hét autó van. Keresd meg!",
    "file": "audio/voice/question_auto_7.mp3"
  },
  "quantity_labda_7": {
    "text": "hét labda",
    "file": "audio/voice/quantity_labda_7.mp3"
  },
  "question_labda_7": {
    "text": "Ezen a képen hét labda van. Keresd meg!",
    "file": "audio/voice/question_labda_7.mp3"
  },
  "quantity_alma_7": {
    "text": "hét alma",
    "file": "audio/voice/quantity_alma_7.mp3"
  },
  "question_alma_7": {
    "text": "Ezen a képen hét alma van. Keresd meg!",
    "file": "audio/voice/question_alma_7.mp3"
  },
  "number_8": {
    "text": "nyolc",
    "file": "audio/voice/number_8.mp3"
  },
  "quantity_auto_8": {
    "text": "nyolc autó",
    "file": "audio/voice/quantity_auto_8.mp3"
  },
  "question_auto_8": {
    "text": "Ezen a képen nyolc autó van. Keresd meg!",
    "file": "audio/voice/question_auto_8.mp3"
  },
  "quantity_labda_8": {
    "text": "nyolc labda",
    "file": "audio/voice/quantity_labda_8.mp3"
  },
  "question_labda_8": {
    "text": "Ezen a képen nyolc labda van. Keresd meg!",
    "file": "audio/voice/question_labda_8.mp3"
  },
  "quantity_alma_8": {
    "text": "nyolc alma",
    "file": "audio/voice/quantity_alma_8.mp3"
  },
  "question_alma_8": {
    "text": "Ezen a képen nyolc alma van. Keresd meg!",
    "file": "audio/voice/question_alma_8.mp3"
  },
  "number_9": {
    "text": "kilenc",
    "file": "audio/voice/number_9.mp3"
  },
  "quantity_auto_9": {
    "text": "kilenc autó",
    "file": "audio/voice/quantity_auto_9.mp3"
  },
  "question_auto_9": {
    "text": "Ezen a képen kilenc autó van. Keresd meg!",
    "file": "audio/voice/question_auto_9.mp3"
  },
  "quantity_labda_9": {
    "text": "kilenc labda",
    "file": "audio/voice/quantity_labda_9.mp3"
  },
  "question_labda_9": {
    "text": "Ezen a képen kilenc labda van. Keresd meg!",
    "file": "audio/voice/question_labda_9.mp3"
  },
  "quantity_alma_9": {
    "text": "kilenc alma",
    "file": "audio/voice/quantity_alma_9.mp3"
  },
  "question_alma_9": {
    "text": "Ezen a képen kilenc alma van. Keresd meg!",
    "file": "audio/voice/question_alma_9.mp3"
  },
  "number_10": {
    "text": "tíz",
    "file": "audio/voice/number_10.mp3"
  },
  "quantity_auto_10": {
    "text": "tíz autó",
    "file": "audio/voice/quantity_auto_10.mp3"
  },
  "question_auto_10": {
    "text": "Ezen a képen tíz autó van. Keresd meg!",
    "file": "audio/voice/question_auto_10.mp3"
  },
  "quantity_labda_10": {
    "text": "tíz labda",
    "file": "audio/voice/quantity_labda_10.mp3"
  },
  "question_labda_10": {
    "text": "Ezen a képen tíz labda van. Keresd meg!",
    "file": "audio/voice/question_labda_10.mp3"
  },
  "quantity_alma_10": {
    "text": "tíz alma",
    "file": "audio/voice/quantity_alma_10.mp3"
  },
  "question_alma_10": {
    "text": "Ezen a képen tíz alma van. Keresd meg!",
    "file": "audio/voice/question_alma_10.mp3"
  }
};
