// These ids join the shared voice manifest. The game uses only prerecorded-clip ids.
export const WORKSHOP_CLIPS = {
  workshop_menu: 'Itt Műhelyliget! Válogasd a tárgyakat, folytasd a mintát, vagy hozd egyensúlyba a mérleget! A három gyémánt nehezebb feladatot jelent.',
  workshop_level_1: 'Felfedező. Egyszerűbb minták és kisebb mennyiségek várnak.',
  workshop_level_2: 'Gondolkodó. Több tulajdonságot és a rudak számát is figyeld!',
  workshop_level_3: 'Tervező. Több szabály működik egyszerre. Haladj lépésenként!',
  workshop_sort_1: 'A tárgyakat színük szerint válogasd! Koppints egy tárgyra, majd a hozzá illő tálcára! A tárgy és a tálca színjele segít. A tálcáról vissza is veheted a tárgyat.',
  workshop_sort_2: 'Most a szín és a forma együtt mutatja a helyet. Válassz egy tárgyat, majd koppints a hozzá illő tálcára! A tárgyakat át is rendezheted.',
  workshop_sort_3: 'A megadott méretű tárgyakat szín és forma szerint válogasd a tálcákra! A másik méretű tárgyak a levélre kerülnek. Koppints a tárgyra, majd a helyére!',
  workshop_only_big: 'Csak a nagy tárgyak kerülnek a színes tálcákra. A kis tárgyakat a levélre tedd!',
  workshop_only_small: 'Csak a kis tárgyak kerülnek a színes tálcákra. A nagy tárgyakat a levélre tedd!',
  workshop_sort_hint1: 'A tárgy és a tálca színjele megegyezik. A nehezebb feladatban a formát és a megadott méretet is figyeld!',
  workshop_sort_hint2: 'A napocskás tárggyal folytasd! Nézd meg a színjelét és a formáját, majd válassz tálcát!',
  workshop_sort_hint3: 'A napocskás tárgy a napocskás tálcára illik. Koppints a tárgyra, majd arra a tálcára!',
  workshop_sort_retry: 'Néhány tárgynak még keresünk helyet. Figyeld a jeleket, és rendezd át őket! A lépéseket vissza is vonhatod.',
  workshop_sort_done: 'Minden tárgy megtalálta a helyét! Rendezett lett a válogatókert. Szép munka!',
  workshop_pattern_1: 'Figyeld az ismétlődő mintát! Koppints egy üres helyre, majd válassz rá egy formát a készletből! A kitöltött helyet később át is cserélheted.',
  workshop_pattern_2: 'A minta néhány helye üres. Az elején látod az ismétlődő egységet. Koppints egy üres helyre, és válassz rá formát! Minden hely illeszkedjen a mintához!',
  workshop_pattern_3: 'Két szín váltakozik, a forma hármasával ismétlődik. A kettőt együtt figyeld! Koppints egy üres helyre, majd válassz rá formát a készletből!',
  workshop_pattern_hint1: 'A minta elején kiemeltem az ismétlődő elemeket. Kövesd a sorrendjüket a következő helyeken is!',
  workshop_pattern_hint2: 'A minta alatt külön is látod az ismétlődő egységet. A napocskás helyet töltsd ki vele!',
  workshop_pattern_hint3: 'A napocskás forma a napocskás helyre illik. Koppints rá a formakészletben!',
  workshop_pattern_retry: 'Néhány elem még hiányzik, vagy másként folytatja a mintát. Figyeld az ismétlődést, és cseréld át, amit szeretnél!',
  workshop_pattern_done: 'Minden elem illeszkedik! Végigfut a színes minta a műhelyen. Szép munka!',
  workshop_balance_1: 'A bal oldalon lévő mennyiséget rudakkal rakd ki a jobb oldalon! Egy pötty egy egység. Koppints egy rúdra a készletben! A jobb oldalról a rúdra koppintva visszaveheted.',
  workshop_balance_2: 'Két különböző hosszúságú rudat tegyél a jobb oldalra! Együtt pontosan annyit érjenek, mint a bal oldal. Vissza is vehetsz egy rudat, és kipróbálhatsz másikat.',
  workshop_balance_3: 'Három különböző hosszúságú rudat válassz! Mindegyik hosszúságból csak egy van. A három együtt pontosan annyit érjen, mint a bal oldal. Rendezd át őket, amíg egyensúlyba kerül a mérleg!',
  workshop_balance_hint1: 'Egy pötty egy egység. Hasonlítsd össze a két oldalt! A hosszabb rúd többet ér.',
  workshop_balance_hint2: 'Megmutattam, mennyi hiányzik, vagy mennyivel van több a jobb oldalon. A nehezebb feladatban különböző rudakat válassz, a megadott darabszámban!',
  workshop_balance_hint3: 'A napocskás rúd mutatja a következő lépést. A készletből beteheted, a jobb oldalról visszaveheted. Így tovább alakíthatod az egyensúlyt.',
  workshop_add_rod: 'Tegyél be egy ilyen hosszúságú rudat!',
  workshop_take_rod: 'Vegyél vissza egy ilyen hosszúságú rudat!',
  workshop_target: 'A bal oldalon ennyi egység van.',
  workshop_balance_retry: 'A rudakat még átrendezheted. Figyeld a mennyiséget és a megadott darabszámot! A lépéseket vissza is vonhatod.',
  workshop_balance_done: 'A két oldal egyensúlyban van! Megtaláltad az összeillő rudakat. Szép munka!',
  workshop_ready: 'Minden a helyén van. Koppints a Kész gombra!',
};
['nulla', 'egy', 'kettő', 'három', 'négy', 'öt', 'hat', 'hét', 'nyolc', 'kilenc', 'tíz', 'tizenegy', 'tizenkettő', 'tizenhárom', 'tizennégy', 'tizenöt'].forEach((text, number) => { WORKSHOP_CLIPS[`workshop_n_${number}`] = text; });
