import { readFile, writeFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { words } from '../game-data.js';
import { VOICE_CLIPS } from '../voice-library.js';

const root = new URL('../', import.meta.url);
const frontendFiles = (await readdir(root, { withFileTypes: true }))
  .filter(entry => entry.isFile() && /\.(js|css)$/.test(entry.name) && !['sw.js', 'service-worker-runtime.js'].includes(entry.name))
  .map(entry => entry.name);
const files = [
  'index.html', ...frontendFiles,
  'app.webmanifest', 'icons/icon.svg', 'icons/apple-touch-icon.png', 'icons/icon-192.png', 'icons/icon-512.png',
  ...words.map(word => `audio/${word.id}.mp3`),
  ...Object.values(VOICE_CLIPS).map(clip => clip.file),
].sort();
const hash = content => createHash('sha256').update(content).digest('hex');
const assets = await Promise.all([...new Set(files)].map(async file => ({ file, sha256: hash(await readFile(new URL(file, root))) })));
const runtime = await readFile(new URL('service-worker-runtime.js', root), 'utf8');
const version = hash(JSON.stringify(assets) + runtime).slice(0, 16);
const output = `// Generated by npm run build-offline. Do not edit this file directly.\nconst CACHE_VERSION = ${JSON.stringify(version)};\nconst ASSETS = ${JSON.stringify(assets, null, 2)};\n\n${runtime}`;
const target = new URL('sw.js', root);
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8').catch(() => '') !== output) {
    throw new Error('Offline bundle is out of date. Run npm run build-offline.');
  }
} else {
  await writeFile(target, output);
}
console.log(`Offline bundle: ${assets.length} files · ${version}`);
