import { readFile, writeFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { words } from '../game-data.js';
import { VOICE_CLIPS } from '../voice-library.js';
import { ANIMAL_BOOK_PAGES } from '../animal-book-data.js';
import { AUDIOBOOKS } from '../audiobook-data.js';

const root = new URL('../', import.meta.url);
const frontendFiles = (await readdir(root, { withFileTypes: true }))
  .filter(entry => entry.isFile() && /\.(js|css)$/.test(entry.name) && !['sw.js', 'service-worker-runtime.js'].includes(entry.name))
  .map(entry => entry.name);
const files = [
  'index.html', 'refresh.html', ...frontendFiles,
  'assets/furfang-fox.png',
  'animal-book-audio.json',
  ...ANIMAL_BOOK_PAGES.flatMap(page => [page.image.replace(/^\.\//, ''), ...page.animals.map(animal => `audio/animals/${animal.id}.mp3`)]),
  'app.webmanifest', 'icons/icon.svg', 'icons/apple-touch-icon.png', 'icons/icon-192.png', 'icons/icon-512.png',
  ...words.map(word => `audio/${word.id}.mp3`),
  ...Object.values(VOICE_CLIPS).map(clip => clip.file),
].sort();
const hash = content => createHash('sha256').update(content).digest('hex');
const assets = await Promise.all([...new Set(files)].map(async file => ({ file, sha256: hash(await readFile(new URL(file, root))) })));
// Publish long stories, but do not download them during installation of the games.
const optionalAssets = await Promise.all(AUDIOBOOKS.map(async story => {
  const sha256 = hash(await readFile(new URL(story.file, root)));
  if (sha256 !== story.sha256) throw Error(`Unverified audiobook: ${story.id}`);
  return { file: story.file, sha256 };
}));
const runtime = await readFile(new URL('service-worker-runtime.js', root), 'utf8');
const version = hash(JSON.stringify(assets) + JSON.stringify(optionalAssets) + runtime).slice(0, 16);
const output = `// Generated by npm run build-offline. Do not edit this file directly.\nconst CACHE_VERSION = ${JSON.stringify(version)};\nconst ASSETS = ${JSON.stringify(assets, null, 2)};\nconst OPTIONAL_ASSETS = ${JSON.stringify(optionalAssets, null, 2)};\n\n${runtime}`;
const target = new URL('sw.js', root);
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8').catch(() => '') !== output) {
    throw new Error('Offline bundle is out of date. Run npm run build-offline.');
  }
} else {
  await writeFile(target, output);
}
console.log(`Offline bundle: ${assets.length} files · ${version}`);
